NOISSUE - Add attribute map for twin retrieval
absmach/magistrala pull request #1027
Opened 2020-02-03 18:08 UTC by darkodraskovic

Signed-off-by: Darko Draskovic <darko.draskovic@gmail.com>

### What does this do?
Adds a method for twin - channel/subtopic attribute map in order to dissociate twin entity from thing publisher. 

Currently, twin has to be associated with a thing and twin is identified via message publisher (id of the thing twin is associated to). We want that twin be identified solely by a channel and subtopic: if a twin has an attribute uniquely defined by a channel and subtopic, then twin is concerned by the corresponding message.

This makes it possible to construct a twin that picks up messages from any channel and any subtopic and is not relient on the concept of Mainflux thing.

2020-02-03 18:11 UTC, drasko requested changes

2020-02-03 18:11 UTC, drasko commented on twins/mongodb/twins.go
> +// func (tr *twinRepository) RetrieveAllByAttribute(ctx context.Context, chanid string, subtopic string) ([]twins.Twin, error) {
Dead code?

2020-02-04 21:21 UTC, mteodor commented on twins/service.go
> +	SaveStates(*mainflux.Message) error
why pointer

2020-02-04 21:22 UTC, mteodor commented on twins/nats/subscriber.go
> +		ps.logger.Error(fmt.Sprintf("State save failed: %s", err))
shouldnt this be err.Error()

2020-02-04 21:27 UTC, mteodor commented on twins/service.go
>  				delete(st.Payload, k)
delete while iterate ?

2020-02-04 21:28 UTC, drasko approved these changes
LGTM

2020-02-04 22:25 UTC, manuio approved these changes
LGTM

2020-02-04 22:25 UTC, merged