NOISSUE -Add tests that run on Merge
absmach/magistrala pull request #103
Opened 2023-12-01 14:20 UTC by Musilah

# What type of PR is this?

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [X] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
This allows all tests to run on Push to Main especially e2e Tests

## Which issue(s) does this PR fix/relate to?

- Resolves None

## Have you included tests for your changes?

- [ ] Yes
- [X] No

## Did you document any new/modified feature?

- [ ] Yes
- [X] No

### Notes

2023-12-01 17:05 UTC, dborovcanin requested changes

2023-12-03 16:45 UTC, Musilah commented on .github/workflows/ci.yml
> +          go tool cover -html=coverage.out -o coverage.html
To ensure that only the tests that are changed in a PR are run again. The `dorny/paths-filter@v2` needed this format to work. But I kept the same format on push to main so that all tests are run

2023-12-03 17:10 UTC, dborovcanin requested changes

2023-12-04 17:32 UTC, dborovcanin requested changes

2023-12-04 17:32 UTC, dborovcanin commented on .github/workflows/ci.yml
> +          go test --race -v -count=1 -coverprofile=coverage/bootstrap.out ./bootstrap/...
A couple of lines above, please keep `Test` in the name lowercase.

2023-12-04 19:25 UTC, dborovcanin approved these changes

2023-12-04 19:26 UTC, merged