Update mqtt adapter imports
absmach/magistrala pull request #1081
Opened 2020-03-23 17:04 UTC by nmarcetic

Signed-off-by: Nikola Marcetic <n.marcetic86@gmail.com>

### What does this do?
It updates mqtt adapter imports and adds mproxy WebSocket init. 
### Which issue(s) does this PR fix/relate to?
NA
### List any changes that modify/break current functionality
NA
### Have you included tests for your changes?
NA
### Did you document any new/modified functionality?
NA
### Notes
NA

2020-03-23 17:21 UTC, drasko submitted a review, later dismissed
LGTM

2020-03-24 07:57 UTC, manuio requested changes

2020-03-24 07:57 UTC, manuio commented on cmd/mqtt/main.go
> +
rm this blank line

2020-03-24 08:00 UTC, manuio requested changes

2020-03-24 08:00 UTC, manuio commented on mqtt/adapter.go
> +func (e *Event) AuthConnect(c *session.Client) error {
Fix `AuthConenct` inside this function

2020-03-24 08:01 UTC, manuio requested changes

2020-03-24 08:01 UTC, manuio commented on cmd/mqtt/main.go
>  	logger.Info(fmt.Sprintf("Starting MQTT proxy on port %s ", cfg.mqttPort))
Rm the white space after `%s`

2020-03-24 08:01 UTC, manuio commented on cmd/mqtt/main.go
> +	logger.Info(fmt.Sprintf("Starting MQTT over WS  proxy on port %s ", cfg.httpPort))
Rm the white space after %s

2020-03-24 09:54 UTC, dborovcanin approved these changes

2020-03-24 10:07 UTC, manuio approved these changes
LGTM

2020-03-24 10:07 UTC, merged