MF-1099 - Add email subdomain validator
absmach/magistrala pull request #1101
Opened 2020-04-06 17:08 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

Resolves #1099

2020-04-06 17:22 UTC, drasko requested changes

2020-04-06 17:22 UTC, drasko commented on users/users.go
> +	if len(hs) == 3 {
Why 3? Can there be multiple subdomains (I do not know, but theorethically stere can be sub-subdomain)?

2020-04-06 19:15 UTC, drasko submitted a review, later dismissed
LGTM

2020-04-07 08:01 UTC, blokovi approved these changes

2020-04-07 08:16 UTC, dborovcanin approved these changes

2020-04-07 08:16 UTC, merged