NOISSUE - Fix default nats publisher subject
absmach/magistrala pull request #1153
Opened 2020-04-30 09:05 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

2020-04-30 09:06 UTC, blokovi submitted a review, later dismissed

2020-04-30 09:07 UTC, mteodor submitted a review, later dismissed

2020-04-30 09:31 UTC, drasko requested changes
I agree that sending `topic` when we already have `msg.channel` in `msg` is redundant, but @dusanb94 had a rationale in developing the interface and he must explain.

2020-04-30 14:20 UTC, mteodor submitted a review, later dismissed

2020-05-01 13:27 UTC, drasko requested changes

2020-05-01 13:27 UTC, drasko commented on transformers/senml/transformer.go
> +		time := v.Time
I would avoid the name `time`, as it relates to Go library name... I prefer `t` in this case.

2020-05-01 13:27 UTC, drasko commented on transformers/senml/transformer.go
> +			time = float64(msg.Created.GetSeconds()) + float64(msg.Created.GetNanos())/float64(1e9)
This looks like precision in seconds to me. If you wanted nanoseconds, you should probably do something like:
```go
float64(msg.Created.GetSeconds() * 1e9 + msg.Created.GetNanos())
```

2020-05-03 22:01 UTC, drasko requested changes

2020-05-04 09:39 UTC, dborovcanin submitted a review, later dismissed

2020-05-04 09:43 UTC, mteodor submitted a review, later dismissed

2020-05-04 09:51 UTC, dusanb94 commented
> I agree that sending `topic` when we already have `msg.channel` in `msg` is redundant, but @dusanb94 had a rationale in developing the interface and he must explain.

I decided to switch to topic-based pub-sub so that we can have a clean `Pub` and `Sub` interfaces. Also, we don't have to necessarily publish to the `msg.Channel` in the Publisher implementation, but rather let the one who uses publisher decide where to publish. This way, we keep specification (interface), implementation (NATS Pub and PubSub), and usage clean (the one who uses publisher chooses where to publish). Also, we should avoid modifying topic in the implementation, because of possible problems such as the one this PR resolves. We still have it in the `Publish` method implementation (adding channels prefix), though.

2020-05-04 10:32 UTC, dborovcanin approved these changes

2020-05-04 11:08 UTC, drasko approved these changes
LGTM

2020-05-04 11:14 UTC, merged