NOISSUE - Add subtopic to twin state payload key
absmach/magistrala pull request #1165
Opened 2020-05-05 17:36 UTC by darkodraskovic

Signed-off-by: Darko Draskovic <darko.draskovic@gmail.com>

Currently, state payload keys are identical to definition attribute names. This does not take into account subtopic contribution to the state payload and attribute semantics.

2020-05-05 17:46 UTC, manuio requested changes

2020-05-05 17:46 UTC, manuio commented on twins/service.go
> +		keyName = attr.Name + "/" + attr.Subtopic
Use `fmt.Sprintf()` please

2020-05-05 17:46 UTC, manuio commented on twins/service.go
> +	if len(attr.Subtopic) > 0 {
If `attr.Subtopic` is a string I would use `!= ""`

2020-05-06 06:15 UTC, darkodraskovic commented
Sorry, I realized that this is already covered by the possibility to give arbitrary names to attributes. Closing this pull request.

2020-05-06 06:15 UTC, closed without merging