MF-1154 - Move UUID provider to project root
absmach/magistrala pull request #1172
Opened 2020-05-12 14:21 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

Resolves #1154

2020-05-12 14:47 UTC, mteodor submitted a review, later dismissed
LGTM

2020-05-12 14:52 UTC, blokovi submitted a review, later dismissed

2020-05-12 16:16 UTC, drasko requested changes

2020-05-12 16:16 UTC, drasko commented on authn/service_test.go
> +	idp := mocks.NewUUIDProvider()
I do not like the idea to call this var `idp` any more

2020-06-02 10:37 UTC, mteodor submitted a review, later dismissed

2020-06-02 11:50 UTC, nmarcetic commented
@mainflux/maintainers Why not moving this to `/pkg` it's a great candidate as a shared package.

2020-06-02 12:10 UTC, manuio commented
@nmarcetic I'm not against. I also wanted to know where do you think that we should put uuid mock. In `pkg/uuid/mocks` directory or in a specific `pkg/mocks` directory?

2020-06-02 12:11 UTC, nmarcetic commented
> @nmarcetic I'm not against. I also wanted to know where do you think that we should put uuid mock. In `pkg/uuid/mocks` directory or in a specific `pkg/mocks` directory?

If those mocks are not sharable (e.g not used by there packages, but only by `/pkg/uuid`) then I would keep them under `/pkg/uuid`

2020-06-03 15:47 UTC, drasko approved these changes
LGTM

2020-06-03 16:44 UTC, nmarcetic approved these changes

2020-06-03 16:49 UTC, merged