MF-983 - Add HTTP query param to connections list endpoints to fetch non connected Things or Channels
absmach/magistrala pull request #1217
Opened 2020-07-10 15:27 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

Resolves #983

2020-07-13 13:10 UTC, mteodor requested changes
swagger needs update

2020-07-13 13:16 UTC, dusanb94 commented
@manuio Please update PR, CI is failing and the branch is out of date.

2020-07-16 09:21 UTC, nmarcetic commented
@manuio IMHO `connected` bool is much better than `disconnected`. If we have this query param, by default it should return all (booth conn/disconn) and if you pass query connected bool then filter and return filtered result.

2020-07-16 09:33 UTC, manuio commented
> @manuio IMHO `connected` bool is much better than `disconnected`. If we have this query param, by default it should return all (booth conn/disconn) and if you pass query connected bool then filter and return filtered result.

@nmarcetic do you mean to return connected by default? And disconnected if connected = false? If we return connected and disconnected we are returning all things :) I wanted a flag where the default value is false to simplify the code. Maybe we can find a better naming.

2020-07-16 09:42 UTC, nmarcetic commented
> > @manuio IMHO `connected` bool is much better than `disconnected`. If we have this query param, by default it should return all (booth conn/disconn) and if you pass query connected bool then filter and return filtered result.
> 
> @nmarcetic do you mean to return connected by default? And disconnected if connected = false? If we return connected and disconnected we are returning all things :) I wanted a flag where the default value is false to simplify the code. Maybe we can find a better naming.

Yes, return all things owned by user by default. then filter it with a query like &connected=true/false if you want. We have pagination. This would be the cleanest way.

2020-07-16 10:43 UTC, manuio commented
> > > @manuio IMHO `connected` bool is much better than `disconnected`. If we have this query param, by default it should return all (booth conn/disconn) and if you pass query connected bool then filter and return filtered result.
> > 
> > 
> > @nmarcetic do you mean to return connected by default? And disconnected if connected = false? If we return connected and disconnected we are returning all things :) I wanted a flag where the default value is false to simplify the code. Maybe we can find a better naming.
> 
> @manuio Yes, return all things owned by user by default. then filter it with a query like &connected=true/false if you want. We have pagination. This would be the cleanest way.

@nmarcetic Why would I specify a channel or thing ID (`things/<thing_id>/channels` or `channels/<channel_id>/things`) to fetch all existent things or channels? It's not really the same feature. I would keep it as it is but find a better naming. Maybe `off` instead of `disconnected`?

2020-07-16 10:49 UTC, nmarcetic commented
> `things/<thing_id>/channels` or `channels/<channel_id>/things`

@manuio Why would you specify ID (`things/<thing_id>/channels` or `channels/<channel_id>/things`) to fetch something that does not belong here :) like disconnected things/channels? I think something is definitely wrong with the design here.

Ok, keep it as is, I think `connected` bool is best (because of our internal terminology of connecting things to channel ). 
We can discuss about the design later with all @mainflux/maintainers

2020-07-21 13:05 UTC, dborovcanin requested changes
I agree with @nmarcetic that using `connected` param is better than `disconnected`.

2020-07-21 13:05 UTC, dusanb94 commented on things/postgres/things.go
> +  INNER JOIN connections co
Using `conn` instead of `co` is less ambiguous.

2020-07-21 13:05 UTC, dusanb94 commented on things/postgres/things.go
> +  FROM things th
You can use `switch` here, it's cleaner than using `if`.

2020-07-21 14:10 UTC, mteodor commented on things/postgres/channels.go
> +    INNER JOIN connections co ON ch.id = co.channel_id
this doesnt look properly aligned

2020-07-21 15:01 UTC, dborovcanin requested changes

2020-07-21 15:01 UTC, dusanb94 commented on things/postgres/things.go
> +	var q string
Same here.

2020-07-22 10:48 UTC, mteodor submitted a review, later dismissed

2020-07-22 10:49 UTC, dborovcanin requested changes

2020-07-22 10:49 UTC, dusanb94 commented on things/postgres/channels.go
> +	var q string
You can use `var q, qc string`.

2020-07-22 10:49 UTC, dusanb94 commented on things/postgres/channels.go
> +	case true:
Can you indent relative to `SELECT`, like:
```go
case true:
        q = `SELECT id, name, key, metadata
                FROM things th
                INNER JOIN connections conn
                ON th.id = conn.thing_id
                WHERE th.owner = :owner AND conn.channel_id = :channel
                ORDER BY th.id
                LIMIT :limit
                OFFSET :offset;`
        qc = `SELECT COUNT(*)
                 FROM things th
                 INNER JOIN connections conn
                 ON th.id = conn.thing_id
                 WHERE th.owner = $1 AND conn.channel_id = $2;`
```
It's just more readable and it's aligned to `init.go`.

2020-07-22 10:49 UTC, dusanb94 commented on things/postgres/things.go
> +	var q string
Same remark for indentation.

2020-07-23 11:21 UTC, dborovcanin approved these changes

2020-07-23 11:24 UTC, mteodor approved these changes

2020-07-26 20:39 UTC, drasko reviewed
LGTM

2020-07-26 20:47 UTC, merged