MG-31 - Fix pkg tests
absmach/magistrala pull request #123
Opened 2023-12-05 13:40 UTC by 1998-felix

# What type of PR is this?

## What does this do?
Fixes tests in pkg

## Which issue(s) does this PR fix/relate to?

- Related Issue #31 
- Resolves #

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2023-12-07 10:51 UTC, dborovcanin requested changes
CI for `pkg` is failing, this PR is supposed to fix it. Also, please check integration tests when running tDocker containers, it looks like we do not correctly stop them.

2023-12-07 12:54 UTC, dborovcanin requested changes
@1998-felix Once the PR is ready, don't forget to update tests with `pkg`  included, since it is temporarily disabled in #122.

2023-12-11 16:19 UTC, dborovcanin requested changes

2023-12-11 16:19 UTC, dborovcanin commented on pkg/sdk/go/users_test.go
> +			err:      errors.NewSDKErrorWithStatus(errors.Wrap(ErrFailedOwnerUpdate, ErrFailedOwnerUpdate), http.StatusInternalServerError),
This problem here is in error handling on the service side, so please fix them there, rather than adding an artificial error for the sake of making tests pass.

2023-12-11 16:49 UTC, 1998-felix commented on pkg/sdk/go/users_test.go
> +			err:      errors.NewSDKErrorWithStatus(errors.Wrap(ErrFailedOwnerUpdate, ErrFailedOwnerUpdate), http.StatusInternalServerError),
That is the error generated at the service layer. Can I wrap the errors generated at the service layer with sdk errors when they get to this layer?

2023-12-11 20:15 UTC, dborovcanin requested changes

2023-12-11 20:15 UTC, dborovcanin commented on pkg/sdk/go/users_test.go
> +var ErrFailedOwnerUpdate = errors.New("failed to update user owner")
Use `users.ErrFailedOwnerUpdate` here instead; it's OK to import external packages in tests.

2023-12-12 13:28 UTC, dborovcanin requested changes

2023-12-12 13:28 UTC, dborovcanin commented on Makefile
> +	go test -v --race -count 1 -tags test -coverprofile=coverage/coverage.out $$(go list ./... | grep -v 'postgres\|internal\|opcua\|consumers\|readers\|cmd')
Keep the order the same as in `DIRS`.

2023-12-12 15:09 UTC, merged