NOISSUE - Add new endpoint to retrieve configuration to be used as a template.
absmach/magistrala pull request #1242
Opened 2020-09-25 16:40 UTC by mteodor

### What does this do?

Adds new endpoint that will retrieve current provision template configuration as JSON.
It can be used in UI to populate configuration in a same way as `provision` service does

2020-09-25 16:59 UTC, manuio requested changes

2020-09-25 16:59 UTC, manuio commented on provision/service.go
> +
Rm this blank line

2020-09-25 16:59 UTC, manuio commented on provision/api/logging.go
> +			lm.logger.Warn(fmt.Sprintf("%s with error: %s.", message, err))
remove last `.`

2020-09-25 16:59 UTC, manuio commented on provision/api/logging.go
> +		lm.logger.Info(fmt.Sprintf("%s without errors.", message))
same here

2020-09-25 16:59 UTC, manuio commented on provision/swagger.yml
> +
why this blank lines?

2020-09-25 18:02 UTC, manuio approved these changes, later dismissed
LGTM

2020-09-28 11:01 UTC, manuio submitted a review, later dismissed
LGTM

2020-09-28 11:06 UTC, dusanb94 commented on provision/service.go
> +func (ps *provisionService) Mapping(token string) (interface{}, error) {
Maybe we can at least return `map[string]interface` instead of interface{}. It's of little use, but better than `interface{}`.

2020-09-28 11:31 UTC, manuio approved these changes

2020-09-29 08:25 UTC, dusanb94 approved these changes

2020-09-29 08:25 UTC, merged