NOISSUE - Generate SDK Mocks
absmach/magistrala pull request #127
Opened 2023-12-06 11:38 UTC by rodneyosodo

# What type of PR is this?

## What does this do?

This PR adds the generation of SDK mocks. This is quite useful for services depending on the SDK for example, bootstrap and certs service. This approach simplifies the testing process as initially, one would need to generate the things services, then the things server and finally use the things server URL on the SDK. This effective means that when testing other services you inherently test services that depend on the SDK which is not ideal. With SDK mocks you can mock the SDK rather than mocking dependent services.

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

Yes, I have included tests for my changes.

## Did you document any new/modified feature?

Yes, I have updated the documentation for the new feature.

### Notes
N/A

2023-12-07 14:11 UTC, SammyOina requested changes

2023-12-07 14:11 UTC, SammyOina commented on Makefile
> +	go generate ./...
it would be nice to have `make mocks` for development

2023-12-10 19:26 UTC, dborovcanin requested changes

2023-12-10 19:26 UTC, dborovcanin commented on .github/workflows/check-generated-files.yml
> +            echo "Generated mocks for SDK ./pkg/sdk/go/mocks.go are out of sync! Please run 'go generate ./...' and commit the changes."
Add a version to the report.

2023-12-15 08:23 UTC, dborovcanin approved these changes

2023-12-15 08:25 UTC, merged