NOISSUE - fix dates, change path construction
absmach/magistrala pull request #1300
Opened 2020-12-09 18:37 UTC by mteodor

### What does this do?

* Fix `created_at` and `updated_at` not being saved properly
* Change the way that path is constructed, instead of the name of the group being used group id will be used
```
select id, name, path from thing_groups;
                  id                  |  name   |                                   path                                    
--------------------------------------+---------+---------------------------------------------------------------------------
 18e63b43-b264-425b-9074-c4361225ed0b | group12 | 18e63b43_b264_425b_9074_c4361225ed0b
 98bcaebd-bd66-4635-a715-d3cf50831b8e | group12 | 18e63b43_b264_425b_9074_c4361225ed0b.98bcaebd_bd66_4635_a715_d3cf50831b8e
 da3592bb-6a51-49bd-b4be-a818cbd0fee4 | group13 | 18e63b43_b264_425b_9074_c4361225ed0b.da3592bb_6a51_49bd_b4be_a818cbd0fee4
```
* Name of the group can be changed

2020-12-09 19:32 UTC, drasko requested changes
This looks a bot complex... let's think if it is really needed.

Also - does name still stays unique? We should not demand that it is unique if we use IDs.

2020-12-16 15:13 UTC, manuio commented on things/postgres/groups.go
>  	Thing uuid.UUID `db:"thing_id"`
This should be `GroupID` and `ThingID`

2020-12-16 15:14 UTC, manuio commented on pkg/ulid/ulid.go
> +var _ mainflux.UUIDProvider = (*ulidProvider)(nil)
Should we rename this  to `mainflux.IDProvider` ?

2020-12-16 15:40 UTC, drasko requested changes

2020-12-16 15:40 UTC, drasko commented on things/service.go
> +	mfxulid "github.com/mainflux/mainflux/pkg/ulid"
Why `mfxulid` and not `ulidProvider` or `IDProvider`? Maybe we can also remove everything and use just `ulid`?

2020-12-16 18:47 UTC, drasko approved these changes, later dismissed
LGTM

2020-12-16 19:05 UTC, manuio approved these changes, later dismissed
LGTM

2020-12-16 21:40 UTC, dusanb94 commented on internal/groups/api/requests.go
> -		return groups.ErrNameInvariant
We should remove this error if it's not used elsewhere.

2020-12-17 12:41 UTC, dusanb94 approved these changes

2020-12-17 12:49 UTC, manuio approved these changes
LGTM

2020-12-17 16:08 UTC, drasko approved these changes
LGTM

2020-12-17 16:08 UTC, merged