MF-1329 - Add Python SDK
absmach/magistrala pull request #1330
Opened 2021-01-15 13:34 UTC by fbugarski

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
This pull request adds Python SDK.

### Which issue(s) does this PR fix/relate to?
Resolves #1329 

### List any changes that modify/break current functionality
Does not affect any current functionality.  

### Have you included tests for your changes?
Tests are not currently included, they will be added subsequently.

### Did you document any new/modified functionality?
Documentation will be added.

### Notes

2021-01-22 13:07 UTC, manuio commented on pkg/sdk/python/channels.py
> +    url = "http://localhost/channels"+'?'+'offset='+params['offset']+'&'+'limit='+params['limit']+'&'+'connected='+params['connected']
What if `params['offset']` is empty?

2021-01-26 07:44 UTC, manuio commented on pkg/sdk/python/channels.py
>      def channel_by_thing(self, thing_id, query_params, token):
This returns a list of channels so better call it `channels_by_thing` or `list_chanels_by_thing`

2021-04-20 19:39 UTC, drasko requested changes

2021-04-20 19:39 UTC, drasko commented on pkg/sdk/python/LICENSE.md
> +The MIT License (MIT)
No need for this license, we already have a license in the top-level Mainflux repo

2021-04-20 19:39 UTC, drasko commented on pkg/sdk/python/tests/test_version.py
> +
Kill these whitelines

2021-04-20 19:39 UTC, drasko commented on pkg/sdk/python/setup.cfg
> +    = src
This is strange - why not in the same line?

2021-04-20 19:39 UTC, drasko commented on pkg/sdk/python/functions/examples.py
> +# '''To start working with the Mainflux system, you need to create a user account'''
This will be needed to be uncommented in the end

2021-05-30 15:30 UTC, drasko requested changes

2021-05-30 15:30 UTC, drasko commented on pkg/sdk/python/setup.py
> +    name="example-pkg-fbugarski",
Name of the SDK is probably `mainflux`

2021-07-06 13:55 UTC, manuio commented on pkg/sdk/python/setup.py
> -        "License :: OSI Approved :: MIT License",
Maybe better to define the licence?

2021-07-06 13:55 UTC, manuio commented on pkg/sdk/python/functions/examples.py
> +from functions import SDK
This sounds too generic as naming

2021-08-02 18:54 UTC, drasko commented
Closing in favor of https://github.com/mainflux/sdk-py/pull/1 - Python SDK will live in a separate dedicated repo.

2021-08-02 18:54 UTC, closed without merging