Add READMEs to pkg packages
absmach/magistrala pull request #1352
Opened 2021-02-03 18:03 UTC by darkodraskovic

Signed-off-by: Darko Draskovic <darko.draskovic@gmail.com>

### What does this do?

Add `README.md` pages to the `pkg` packages.

### Which issue(s) does this PR fix/relate to?
Resolves #1298

2021-02-03 23:19 UTC, drasko requested changes

2021-02-03 23:19 UTC, drasko commented on pkg/README.md
> +The `pkg` directory (the current directory) contains a set of standalone packages that can be imported and used by any applications. The packages are specifically meant for the development of the Mai
`by any application`

2021-02-03 23:19 UTC, drasko commented on pkg/README.md
> +The `pkg` directory (the current directory) contains a set of standalone packages that can be imported and used by any applications. The packages are specifically meant for the development of the Mai
Also, as a reference, maybe you can take a look here at the explanation of the role of this standard directory: https://github.com/golang-standards/project-layout/tree/master/pkg

2021-02-03 23:19 UTC, drasko commented on pkg/auth/README.md
> +To identify a thing, you need a valid **thing key**. You retrieve thing's identity in the form **thing id**, that can be used for thing's and thing's connections' CRUD operations.
`thing connection's` probably?

2021-02-03 23:19 UTC, drasko commented on pkg/sdk/README.md
> +Currently, there is only a fully developed SDK in Go. SDK's in Python and JavaScript are on the road map and are currently in development.
I would remove this sentence, as once other SDK is merged, we'll forget to remove it.

2021-02-04 09:42 UTC, manuio commented on pkg/auth/README.md
> +To identify a thing, you need a valid **thing key**. You retrieve thing's identity in the form of a **thing id**. The latter is used in CRUD operations on things and their connections.
`thing ID`

2021-02-04 15:11 UTC, manuio approved these changes
LGTM

2021-02-04 19:04 UTC, drasko approved these changes

2021-02-04 19:04 UTC, merged