NOISSUE - Upgrade Mongo, Cassandra and Influx docker images
absmach/magistrala pull request #1354
Opened 2021-02-04 11:12 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

2021-02-04 13:30 UTC, dusanb94 approved these changes, later dismissed

2021-02-04 13:36 UTC, mteodor approved these changes, later dismissed

2021-02-04 16:37 UTC, blokovi approved these changes, later dismissed

2021-02-04 19:44 UTC, drasko requested changes

2021-02-04 19:44 UTC, drasko commented on consumers/writers/influxdb/setup_test.go
> +	container, err := pool.Run("influxdb", "1.8.3", cfg)
Why are we abandoning `alpine`? Goal is to keep all images as small as possible.

2021-02-05 10:58 UTC, blokovi approved these changes, later dismissed

2021-02-05 11:09 UTC, blokovi approved these changes

2021-02-05 11:32 UTC, drasko approved these changes
LGTM

2021-02-05 11:32 UTC, merged