NOISSUE - Add CanAccessChannelByOwner grpc endpoint
absmach/magistrala pull request #1366
Opened 2021-02-18 15:27 UTC by darkodraskovic

Signed-off-by: Darko Draskovic <darko.draskovic@gmail.com>

Add grpc support to things service to check if a given channel belongs to a given user.

2021-02-19 11:45 UTC, mteodor submitted a review, later dismissed

2021-02-19 15:32 UTC, manuio requested changes

2021-02-19 15:32 UTC, manuio commented on things/service_test.go
> +	_ = nonOwnedCh
Do we need this?

2021-02-19 15:32 UTC, manuio commented on things/service_test.go
> +	token2 := "1234"
Maybe you can define a const next to `token`

2021-02-22 11:15 UTC, manuio approved these changes
LGTM

2021-02-22 12:45 UTC, mteodor approved these changes

2021-02-22 18:41 UTC, drasko approved these changes
LGTM

2021-02-22 18:41 UTC, merged