NOISSUES: Implementation of Domains
absmach/magistrala pull request #14
Opened 2023-10-27 14:47 UTC by arvindh123

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
- Implementation of Domains 
- Rename spicedb relation from `admin` to `administrator` 
- Rename  spicedb permission from `administrator` to `admin`

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-11-03 09:08 UTC, dborovcanin requested changes

2023-11-06 06:39 UTC, arvindh123 commented on auth/domains.go
> +	Tags      []string         `json:"tags,omitempty"`
Yes @dborovcanin , It is needed to store domain related information,

2023-11-06 06:40 UTC, arvindh123 commented on auth.proto
> +  optional string domain_id = 2;
It is designed in such way that without domain you will able get tokem, but without subject. 
This allows user to login without mentioning the Domain, 
After logged in, user can change to any domain

2023-11-06 17:18 UTC, arvindh123 commented
ToDo
- list domain users 
- listing of entity in group level  eg: /groups/:groupID/users/:userID/things , /groups/:groupID/channels/:channelID/things, etc

2023-11-07 10:08 UTC, dborovcanin requested changes

2023-11-07 10:08 UTC, dborovcanin commented on auth/postgres/init.go
> +                        name        VARCHAR(254),
Remove duplicate `name` column.

2023-11-09 13:33 UTC, dborovcanin requested changes

2023-11-09 13:33 UTC, dborovcanin commented on auth/api/http/domains/transport.go
> +	dr.Post("", otelhttp.NewHandler(kithttp.NewServer(
We should start adding subroutes for policies, domains, and keys - so we have better strcutured API. We can do this in another PR, but in that case, please open an issue.

2023-11-09 13:33 UTC, dborovcanin commented on auth/api/http/policies/endpoint.go
> +		// ToDo:
Remove TODO comments. If necessary, open an issue.

2023-11-09 13:33 UTC, dborovcanin commented on auth/api/logging.go
> +func (lm *loggingMiddleware) Identify(ctx context.Context, key string) (id auth.Key, err error) {
Rename key param to `token`.

2023-11-09 13:33 UTC, dborovcanin commented on auth/postgres/init.go
> +					`CREATE TABLE IF NOT EXISTS policies_copy (
No need for `_copy` suffix.

2023-11-09 13:33 UTC, dborovcanin commented on auth/spicedb/policies.go
> +		return fmt.Errorf("no policies provided")
Extract the error.

2023-11-09 13:33 UTC, dborovcanin commented on auth/spicedb/policies.go
> +	case pr.SubjectType == auth.UserType && pr.ObjectType == auth.GroupType:
This is a lot. Can you simplify (split to multiple functions; create factory function for nested objects)?

2023-11-09 13:33 UTC, dborovcanin commented on auth/policies.go
> +	TokenKind      = "token"
Logically group to separate `const` blocks.

2023-11-09 13:33 UTC, dborovcanin commented on internal/groups/api/metrics.go
> +func (ms *metricsMiddleware) CreateGroup(ctx context.Context, token string, kind string, g groups.Group) (groups.Group, error) {
token, kind string

2023-11-09 13:33 UTC, dborovcanin commented on internal/groups/events/streams.go
> +func (es eventStore) CreateGroup(ctx context.Context, token string, kind string, group groups.Group) (groups.Group, error) {
token, kind string

2023-11-09 13:44 UTC, arvindh123 commented on auth/api/http/domains/transport.go
> +	dr.Post("", otelhttp.NewHandler(kithttp.NewServer(
Domains having subroute with `bone.Mux`
Policies and Keys are using `bone.Mux` , So Domains are also created with `bone.Mux` 
Create issue #30  for auth service for migrate from `bone` to `chi`

2023-11-10 08:54 UTC, dborovcanin requested changes

2023-11-10 08:54 UTC, dborovcanin commented on auth/postgres/domains.go
> +
Remove the empty line.

2023-11-10 08:54 UTC, dborovcanin commented on auth/postgres/domains.go
> +func (repo domainRepo) SavePolicyCopy(ctx context.Context, pc auth.PolicyCopy) error {
No need for `Copy` suffix. Add the comment with an explanation.

2023-11-10 08:54 UTC, dborovcanin commented on auth/service.go
> +	errPolicyCopy := svc.domains.SavePolicyCopy(ctx, PolicyCopy{
Why do we save policy on rollback?

2023-11-10 08:54 UTC, dborovcanin commented on auth/spicedb/policies.go
>  	var retErr error
Please remove label, we usually do not use them.

2023-11-10 11:05 UTC, dborovcanin requested changes

2023-11-10 11:08 UTC, arvindh123 commented on auth/spicedb/policies.go
> +func (pa *policyAgent) policyPreCondition(pr auth.PolicyReq) ([]*v1.Precondition, error) {
For some case only we need condition, reset of the cases no need conditions. So only returning nil, nil

2023-11-10 11:36 UTC, arvindh123 commented on auth/spicedb/policies.go
> +func (pa *policyAgent) policyPreCondition(pr auth.PolicyReq) ([]*v1.Precondition, error) {
For some case only we need condition, reset of the cases no need conditions. So only returning nil, nil

2023-11-10 12:15 UTC, dborovcanin requested changes

2023-11-10 12:15 UTC, dborovcanin commented on users/postgres/clients.go
> +	rows, err := repo.ClientRepository.DB.QueryContext(ctx, q, adminID)
Consider using something like:
```go
	q := "SELECT 1 FROM clients WHERE id = $1 AND role = $2"
	rows, err := repo.ClientRepository.DB.QueryContext(ctx, q, adminID, mgclients.AdminRole)
```
to avoid risk of hardcoding the enum value (i.e. if someone accidentially adds values to the begging of the `const` iota block).

2023-11-10 12:17 UTC, arvindh123 commented on users/postgres/clients.go
> +	rows, err := repo.ClientRepository.DB.QueryContext(ctx, q, adminID)
Got it

2023-11-10 15:59 UTC, dborovcanin approved these changes

2023-11-10 17:16 UTC, drasko requested changes

2023-11-10 17:16 UTC, drasko commented on cmd/test/main.go
> +	// grpcOpts, err := grpcutil.WithSystemCerts(grpcutil.SkipVerifyCA)
Dead code

2023-11-10 17:16 UTC, drasko commented on cmd/test/main.go
> +	// grpcOpts, err := grpcutil.WithSystemCerts(grpcutil.SkipVerifyCA)
Also - what is this file - why do we have test in the `cmd` dir?

2023-11-10 17:16 UTC, drasko commented on users/api/clients.go
> +	// So overwriting the permission given by queryPageParams function with default membership permission.
No need to capitalize second row of multi-row comment

2023-11-14 10:52 UTC, arvindh123 commented on cmd/test/main.go
> +	// grpcOpts, err := grpcutil.WithSystemCerts(grpcutil.SkipVerifyCA)
Sorry, I forgot to remove this file , Used to testing spicedb grpc client

2023-11-14 14:08 UTC, dborovcanin requested changes

2023-11-14 14:08 UTC, dborovcanin commented on auth/api/grpc/requests.go
> +	Domain      string
Remove commented code a few lines above.

2023-11-14 14:08 UTC, dborovcanin commented on auth/api/http/policies/endpoint.go
> +		if err := svc.AddPolicies(ctx, []auth.PolicyReq{}); err != nil {
Why do we have empty slice here?

2023-11-14 14:08 UTC, dborovcanin commented on users/api/clients.go
> +			updateClientRoleEndpoint(svc),
Since this reflects roles, please update to _/role_.

2023-11-14 14:29 UTC, arvindh123 commented on auth/api/http/policies/endpoint.go
> +		if err := svc.AddPolicies(ctx, []auth.PolicyReq{}); err != nil {
We don't have HTTP endpoints for now adding and removing policies directly in spicedb,
So to avoid error in code, just filled with empty slice

2023-11-14 14:32 UTC, dborovcanin commented on auth/api/http/policies/endpoint.go
> +		if err := svc.AddPolicies(ctx, []auth.PolicyReq{}); err != nil {
But why do we have the API in that case?

2023-11-14 15:15 UTC, dborovcanin approved these changes

2023-11-14 18:12 UTC, dborovcanin requested changes

2023-11-14 18:12 UTC, dborovcanin commented on docker/spicedb/schema.zed
> +	// These permission are made for only list purpose. It helps to list users have only particular permission excluding other higher and lower permission.
Rephrase: `These permissions are made for listing purposes. They enable listing users who have only particular permission excluding higher-level permissions`.

2023-11-14 18:12 UTC, dborovcanin commented on docker/spicedb/schema.zed
> +	// These permission are made for only list purpose. It helps to list users from external, users who are not in group but have permission on the group through parent group
Same.

2023-11-14 18:12 UTC, dborovcanin commented on docker/spicedb/schema.zed
> +  permission membership = administrator + member
Add an empty line at the end of the file.

2023-11-14 18:12 UTC, dborovcanin commented on internal/apiutil/errors.go
> +	ErrCommitTx = errors.New("failed to commit transaction")
This error is not used.

2023-11-14 18:15 UTC, dborovcanin commented on auth/api/http/policies/endpoint.go
> +		if err := svc.AddPolicies(ctx, []auth.PolicyReq{}); err != nil {
This API will be removed.

2023-11-15 08:46 UTC, rodneyosodo requested changes

2023-11-15 08:46 UTC, rodneyosodo commented on auth.proto
> +  optional string domain_id = 2;
Why do we need `domain_id` as part of the request? Since the token when it was issued either has a domain or not as part of its claim. We can reuse that information.

2023-11-15 08:46 UTC, rodneyosodo commented on auth.proto
> +message AddPoliciesRes { bool authorized = 1; }
`authorized` doesn't seem to fit in well here. Why not `added`?

2023-11-15 08:46 UTC, rodneyosodo commented on auth/keys.go
> +	User      string    `json:"user,omitempty"`
The `subject` should be `userID`. Why do we have separate `user` field?

2023-11-15 08:46 UTC, rodneyosodo commented on auth.proto
> +  rpc AddPolicies(AddPoliciesReq) returns (AddPoliciesRes) {}
Instead of having two methods `AddPolicy` and `AddPolicies` why not have one `AddPolicy` that takes in an array of policies? It can be one policy or multiple policies.

2023-11-15 08:46 UTC, rodneyosodo commented on auth/postgres/init.go
> +					`CREATE TABLE IF NOT EXISTS policies (
align

2023-11-15 08:46 UTC, rodneyosodo commented on internal/groups/postgres/groups.go
> +	fmt.Println(q)
Remove debug statement

2023-11-15 08:46 UTC, rodneyosodo commented on pkg/clients/clients.go
> +	Role        Role        `json:"role,omitempty"`   // 1 for admin, 0 for normal user
Do we need the user to have a role?

2023-11-15 08:46 UTC, rodneyosodo commented on users/service.go
> +	// We don't check the error or user id currently since we can register client with empty token
Remove comment

2023-11-15 08:52 UTC, arvindh123 commented on auth.proto
> +  optional string domain_id = 2;
It is used to change from one domain to another domain, 

Two cases: 

Case 1:
If user login only with username and password, Then issued token will not contain domain,
But this token can be use to create domain and list domain

Once the domain is created,  and if user want to switch to domain
send refresh token request with domain id in body

In response contains a new set of access token and refresh token of the request domain id 

Case 2 : 
From any domain you can change to any domain
For example:
If you have refresh token of domain_1
If you sent /refresh request with body  domain_2
you will get access and refresh token of domain_2

2023-11-15 08:59 UTC, arvindh123 commented on auth.proto
> +  rpc AddPolicies(AddPoliciesReq) returns (AddPoliciesRes) {}
Yes, It is planned to in separate PR. Issue is create here https://github.com/absmach/magistrala/issues/46

2023-11-15 09:01 UTC, arvindh123 commented on pkg/clients/clients.go
> +	Role        Role        `json:"role,omitempty"`   // 1 for admin, 0 for normal user
The role indicate `user` or `SuperAdmin` of Platform

2023-11-15 09:03 UTC, rodneyosodo commented on auth/keys.go
> +	User      string    `json:"user,omitempty"`
If a user is in multiple domains, do they have to be issued different tokens to a specific domain or not?

2023-11-15 09:07 UTC, rodneyosodo commented on auth.proto
> +  optional string domain_id = 2;
> Once the domain is created, and if user want to switch to domain send refresh token request with domain id in body

I think the refresh token is to refresh the access token given upon expiry hence the user should send an issue token request with the domain id.

2023-11-15 09:16 UTC, arvindh123 commented on auth/postgres/init.go
> +					`CREATE TABLE IF NOT EXISTS policies (
It looks like unaligned in github because of webview. 
But in code editor aligned with same tab spaces and looks aligned 
![image](https://github.com/absmach/magistrala/assets/30824765/2aa95cb8-de21-4051-8394-fc7a5483eb2e)

2023-11-15 09:39 UTC, arvindh123 commented on auth/keys.go
> +	User      string    `json:"user,omitempty"`
In Spicedb all the users relations not created with user id 
Instead user relations are create with user id + domain id 

If the relation are stored with user id then list and authz could not identified from which domain context user is doing
So for this purpose a unique user id is user for each domains 
This unique user id is create by combining user id + domain id  

For Example: 
If user_1 is member of domain_1

If user_1 create a thing_1 in domain_1 

In spicedb the policy is stored like 

thing_1@admin#user:domain_1_user_1

So the Subject contains `domain_1_user_1` which is **unique `user id` of `user_1` for `domain_1`** 

 
```json
{
  "domain": "c0af944a-0648-4641-be5d-0e836fc63e7f",
  "exp": 1700058830,
  "iat": 1700040830,
  "iss": "magistrala.auth",
  "sub": "c0af944a-0648-4641-be5d-0e836fc63e7f_66cc6320-cace-4bf6-acfc-bb14dc6bc48c",
  "type": 0,
  "user": "66cc6320-cace-4bf6-acfc-bb14dc6bc48c"
}
```

In the above jwt claims 
user id  : ` "user": "66cc6320-cace-4bf6-acfc-bb14dc6bc48c"`
doamin id  : `  "domain": "c0af944a-0648-4641-be5d-0e836fc63e7f",`
Subject : user id + doamin id  =   `"sub": "c0af944a-0648-4641-be5d-0e836fc63e7f_66cc6320-cace-4bf6-acfc-bb14dc6bc48c",`

2023-11-15 09:50 UTC, arvindh123 commented on auth.proto
> +  optional string domain_id = 2;
We have user + domain claim in token, If user want to change from no domain to a domain or  for one domain to another domain it is used. Otherwise user need to provide user name and password for changing domain. To have smooth user experience it is added at refresh token.


For example. If new user login , since new user there will be no domain and create new domain. 
Once the new domain is created , user could not view or do any action on the domain with same token 

To do so, user need send refresh token with domain id  , 

if domain id is not provided in refresh request then again user need to logout and login with domain ID 
When user is logged out, user could not get domain id, because user could not list domains, which  requires token for authn and authz

2023-11-15 09:51 UTC, arvindh123 commented on users/service.go
> +	// We don't check the error or user id currently since we can register client with empty token
done

2023-11-15 09:51 UTC, arvindh123 commented on internal/groups/postgres/groups.go
> +	fmt.Println(q)
done

2023-11-15 10:47 UTC, arvindh123 commented on auth.proto
> +message AddPoliciesRes { bool authorized = 1; }
Can we do it in separate PR ? . Because for policies we need remove single policy add/delete operation and also need  to provide HTTP endpoints.

2023-11-15 10:52 UTC, rodneyosodo commented on auth.proto
> +message AddPoliciesRes { bool authorized = 1; }
Okay

2023-11-15 11:04 UTC, rodneyosodo commented on auth/keys.go
> +	User      string    `json:"user,omitempty"`
Yes. This will work but the issue is that the `subject` should be the user and the `domain` should be a separate claim. Hence when we do identify or authorization we can extract both `user` and `domain` if present. https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2 This is because a user can have multiple domains or not domains hence in the real sense `user+domain` is not a complete representation of the subject claim as per the spec.

2023-11-15 11:10 UTC, rodneyosodo commented on auth.proto
> +  optional string domain_id = 2;
I just read the spec https://datatracker.ietf.org/doc/html/rfc6749#section-1.5 and it is totally fine since we are obtaining a narrower scope hence we can use Refresh Token to issue new Token.

2023-11-15 11:47 UTC, dborovcanin approved these changes

2023-11-15 11:47 UTC, dborovcanin commented on auth.proto
> +  optional string domain_id = 2;
Though a token without a domain is not particularly useful, this is acceptable. Refresh scenarios will almost always happen with the domain, but let's keep it flexible.

2023-11-15 11:52 UTC, rodneyosodo approved these changes
LGTM

2023-11-16 14:39 UTC, merged