NOISSUE - Update the /disconnect endpoint HTTP method as POST
absmach/magistrala pull request #1438
Opened 2021-07-12 09:27 UTC by buraksekili

Signed-off-by: Burak Sekili <buraksekili@gmail.com>

### What does this do?
This PR updates the HTTP request method of the `/disconnect` endpoint (from `DELETE` to `POST`). According to [OpenAPI specification](https://swagger.io/specification/#operationRequestBody):

> The requestBody is only supported in HTTP methods where the HTTP 1.1 specification RFC7231 has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague, requestBody SHALL be ignored by consumers.

Since the `DELETE` method does not have explicitly defined semantics, It is updated as the `POST` method.

Furthermore, this PR adds OpenAPI specifications for the Swagger UI.

### Which issue(s) does this PR fix/relate to?
None
### List any changes that modify/break current functionality
The HTTP request method of the `/disconnect` endpoint is updated.

### Have you included tests for your changes?
The current tests are updated based on the new method.

### Did you document any new/modified functionality?
The documentation will be added.

### Notes

2021-07-12 09:51 UTC, manuio requested changes

2021-07-12 09:51 UTC, manuio commented on api/things.yml
> +        $ref: "#/components/requestBodies/DisConnCreateReq"
Can we use `DisconnReq` here?

2021-07-12 10:36 UTC, manuio approved these changes
LGTM

2021-07-13 10:46 UTC, blokovi approved these changes

2021-07-13 11:31 UTC, drasko reviewed
LGTM

2021-07-13 11:31 UTC, merged