MF-1454 - Add initial policies regarding Group access
absmach/magistrala pull request #1467
Opened 2021-10-01 15:06 UTC by buraksekili

Signed-off-by: Burak Sekili <buraksekili@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
This PR is WIP
### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2021-10-12 07:31 UTC, mteodor commented on api/auth.yml
> +      summary: Adds access rights for user group on thing group.
I think we need a bit rephrasing here to make it  more clear, maybe
`Assign access rights on list of thing groups to user group with groupId ( or maybe userGroupId)`

2021-10-12 07:31 UTC, mteodor commented on api/auth.yml
> +  /groups/{groupId}/share:
maybe use `{userGroupId}`

2021-10-12 07:32 UTC, mteodor commented on api/auth.yml
> +    ShareGroupAccessReqSchema:
Can we make somehow a commnet that these ids are  thing group ids

2021-10-12 07:34 UTC, mteodor commented on auth/api/logging.go
> +func (lm *loggingMiddleware) ShareAccessRight(ctx context.Context, token, thingGroupID, userGroupID string) (err error) {
maybe `AssignAccesRights` is better naming here

2021-10-12 07:38 UTC, mteodor commented on auth/api/http/groups/requests.go
> +	ThingGroupID string `json:"thing_group_id"`
isnt this an array?

2021-10-12 07:42 UTC, buraksekili commented on auth/api/http/groups/requests.go
> +	ThingGroupID string `json:"thing_group_id"`
No. Currently, one `user group` can be shared with one `thing group`. Should the `user group` be shared with multiple `things groups`?

2021-10-12 10:56 UTC, dborovcanin requested changes

2021-10-12 10:56 UTC, dborovcanin commented on auth/api/http/groups/endpoint.go
> +
Remove the empty line.

2021-10-12 10:56 UTC, dborovcanin commented on auth/api/http/groups/endpoint.go
> +		if err := svc.AssignAccessRights(ctx, req.token, req.ThingGroupID, req.userGroupID); err != nil {
Consider renaming to include `group` in the method name to make it more self-explanatory.

2021-10-12 10:56 UTC, dborovcanin commented on auth/api/http/groups/requests.go
> +	ThingGroupID string `json:"thing_group_id"`
Let's keep it like it is, and we can add list share in the future.

2021-10-12 10:56 UTC, dborovcanin commented on auth/api/http/groups/transport.go
> +	mux.Post("/groups/:groupID/share", kithttp.NewServer(
Maybe `/groups/:userGroupID/share`. Make a distinction between the User and Thing group.

2021-10-12 10:56 UTC, dborovcanin commented on auth/api/logging.go
> +//go:build !test
What's this build tag for?

2021-10-12 10:56 UTC, dborovcanin commented on auth/service.go
> +	return fmt.Sprintf("%s:%s#%s", namespace, object, relation)
No need to wrap, use `fmt.Sprintf` directly.

2021-10-12 10:56 UTC, dborovcanin commented on auth/service.go
> +	if groupType == "things" {
Extract `things` to constant.

2021-10-15 23:44 UTC, drasko requested changes

2021-10-15 23:44 UTC, drasko commented on auth/api/http/groups/transport.go
> +	mux.Post("/groups/:userGroupID/share", kithttp.NewServer(
Why `userGroupID` and how it is different than `groupID`?

2021-10-16 07:43 UTC, buraksekili commented on auth/api/http/groups/transport.go
> +	mux.Post("/groups/:userGroupID/share", kithttp.NewServer(
Apart from the naming, there is no difference between `userGroupID` and `groupID`. But `userGroupID` is more exploratory than `groupID` because `groupID` sounds like that any id belonging to any group is okay. However, the parameter only requires a user group ID. So, in the essence, both are group IDs.

2021-10-17 00:02 UTC, drasko commented on auth/api/http/groups/transport.go
> +	mux.Post("/groups/:userGroupID/share", kithttp.NewServer(
Why do we need this endpoint? We said that there is no difference between groups, i.e. that they are generic containers - they can hold users, or things, mechanism is the same. They have just different type eventually, but group is group - you can putt apples in it, or whatever - it is generic.

2021-10-17 07:40 UTC, mteodor commented on auth/api/http/groups/transport.go
> +	mux.Post("/groups/:userGroupID/share", kithttp.NewServer(
than `userGroupID` must be `subjectGroupID`

2021-10-17 11:51 UTC, buraksekili commented on auth/api/http/groups/transport.go
> +	mux.Post("/groups/:userGroupID/share", kithttp.NewServer(
> Why do we need this endpoint? We said that there is no difference between groups, i.e. that they are generic containers - they can hold users, or things, mechanism is the same. They have just different type eventually, but group is group - you can putt apples in it, or whatever - it is generic.

This endpoint takes two groups ID (one from parameter, one from body). Then, creates following policy:

`Each member of a group (received from parameter, userGroupID) is allowed to access to the group received from the request body (thing group)`

as;

`<thing_group_id>#access@(members:<user_group_id>#member)`.

Therefore, we need this endpoint to allow one group member to access other group members.

I'll rename `userGroupID` to `subjectGroupID`.

2021-10-25 09:49 UTC, dborovcanin requested changes

2021-10-25 09:49 UTC, dborovcanin commented on things/postgres/things.go
> +		// "owner":    owner,
Remove commented code.

2021-10-25 11:27 UTC, dborovcanin approved these changes

2021-10-26 04:08 UTC, arvindh123 approved these changes

2021-10-26 04:24 UTC, drasko approved these changes
LGTM

2021-10-26 04:24 UTC, merged

2021-10-26 04:25 UTC, drasko commented
Merged! Thanks @buraksekili for this great contribution!