NOISSUE - Refactor single-user mode
absmach/magistrala pull request #1471
Opened 2021-10-07 10:46 UTC by dborovcanin

Signed-off-by: dusanb94 <dusan.borovcanin@mainflux.com

### What does this do?
This pull request refactors single-user mode for Things service.

### Which issue(s) does this PR fix/relate to?
There is no such issue.

### List any changes that modify/break current functionality
There are no such changes.

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
Yes. Docs explaining single-user mode are added.

### Notes
N/A

2021-10-07 17:33 UTC, drasko requested changes

2021-10-07 17:33 UTC, drasko commented on cmd/twins/main.go
> +	localusers "github.com/mainflux/mainflux/things/auth"
My only cocncern is should this one be called `auth`, because again when we take a look at `things` folder in a couple of months and when we see `auth` - will we know it is a Single-User Mode related module? I was confused like this with previous naming, which was `user`.

So just one thing to conside - should it be something like `singleuser` (or something like this, self-documenting), or we leave `auth` (I am fine with `auth` also, just challenging the solution a bit).

2021-10-07 17:33 UTC, drasko commented on things/README.md
> +In constrained environments, sometimes it makes sense to run Things service as a standalone to reduce network traffic and simplify deployment. This means that Things service
I think a more detailed documentation in the `mainflux/docs` repo is needed, with detailed explication how this single-user mode is deployed (Dockerfile) and used.

I.e. - there should be a dedicated chapter (or subsection in Authorization) for Single-User Mode, so that people see and understand that this feature exists (otherwise, it is unnoticed).

2021-10-08 09:12 UTC, mteodor commented on things/README.md
> +In constrained environments, sometimes it makes sense to run Things service as a standalone to reduce network traffic and simplify deployment. This means that Things service
yes, but one paragraph is sufficient for this, since you just set the environment variables and one example how `things` api is used then, additionally advise to remove auth service from compose when using this mode

2021-10-08 11:47 UTC, dborovcanin commented on cmd/twins/main.go
> +	localusers "github.com/mainflux/mainflux/things/auth"
I actually spent some time thinking about the naming and I decided to go with `auth` and `single_user` for go files. The reason is that this **is** implementation of `auth` for `single_user`. It is not ideal, but I find it a bit less confusing than `users`. Also, `standalone` sounds a bit better to me than `single_user`, but I did not want to rename env vars to provide backward compatibility. @drasko What do you think about that `auth` and `standalone`?

2021-10-08 11:50 UTC, dborovcanin commented on things/README.md
> +In constrained environments, sometimes it makes sense to run Things service as a standalone to reduce network traffic and simplify deployment. This means that Things service
I agree with @mteodor, I'd say this is good enough for service README. I'll add suggestion for removing `auth` from compose and we can add more details in a separate section in docs.

2021-10-11 09:08 UTC, dborovcanin commented on things/README.md
> +In constrained environments, sometimes it makes sense to run Things service as a standalone to reduce network traffic and simplify deployment. This means that Things service
I renamed `single-user` to `standalone`, please review.

2021-10-11 13:21 UTC, drasko approved these changes
LGTM

2021-10-11 14:08 UTC, merged