MF-1468 - Fix ThingsURL in Certs Service
absmach/magistrala pull request #1474
Opened 2021-10-11 12:51 UTC by smartyfi

### What does this do?
Certs Service  fails to contact the Things Service
### Which issue(s) does this PR fix/relate to?
Resolves #1468

### List any changes that modify/break current functionality
no breaks as default value for ThingsURL is http://things:8182
while new MF_CERTS_THINGS_LOCATION env variable added 

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2021-10-11 16:26 UTC, drasko requested changes

2021-10-11 16:26 UTC, drasko commented on cmd/certs/main.go
> +	envThingsURL      = "MF_CERTS_THINGS_LOCATION"
I do not like the fact that this is called `MF_CERTS_THINGS_LOCATION` and not `MF_CERTS_THINGS_URL` like in other cases. Also - if this is just Things service URL, should it not be just MF_THINGS_URL.

Can you please check how this is handled in other services and align.

2021-10-11 18:25 UTC, smartyfi commented
i tried to match the provision service same syntax 
MF_PROVISION_USERS_LOCATION=http://users:8180
MF_PROVISION_THINGS_LOCATION=http://things:8182

but digging around more i noticed it is related to initaite the SDK, other services looks like MF_SDK_BASE_URL
so i would recommend to go with MF_SDK_THINGS_URL
what do you think ?

2021-10-11 18:56 UTC, drasko commented on cmd/certs/main.go
> +	envThingsURL      = "MF_CERTS_THINGS_LOCATION"
I think that it actually should be `MF_CERTS_URL`, but I let @mteodor and @dusanb94 confirm.

2021-10-12 09:40 UTC, dborovcanin commented
> i tried to match the provision service same syntax MF_PROVISION_USERS_LOCATION=http://users:8180 MF_PROVISION_THINGS_LOCATION=http://things:8182
> 
> but digging around more i noticed it is related to initaite the SDK, other services looks like MF_SDK_BASE_URL so i would recommend to go with MF_SDK_THINGS_URL what do you think ?

Since the usage of SDK is transparent from the end-user perspective, `MF_SDK_*` does not bring too much value. We should probably change it in the Bootstrap service, as well. The same goes for Provision svc: instead of `MF_PROVISION_USERS_LOCATION` simply `MF_THINGS_URL` I understand that some of these env vars can overlap when running locally (and that's why we added these prefixes), but I'd say that we should simplify. You'll have to specify service config when running it anyway, and simplification wins. So, I'd always use `MF_THINGS_URL`, `MF_USERS_URL`, `MF_<SVC>_URL`... What do you think, @mainflux/maintainers?

2021-10-14 21:59 UTC, drasko commented
@smartyfi can you please apply suggestions that @dusanb94 proposed and push forward this useful PR.

2021-10-14 22:30 UTC, smartyfi commented
updated env variable to MF_THINGS_URL

2021-10-15 22:12 UTC, drasko approved these changes
LGTM

2021-10-15 22:26 UTC, merged

2021-10-15 22:26 UTC, drasko commented
Merged! Thanks @smartyfi for the contribution.

2021-10-16 11:26 UTC, manuio commented on cmd/certs/main.go
> +	defThingsURL      = "http://things:8182"
Tabulation is not good here

2021-10-16 11:26 UTC, manuio commented on cmd/certs/main.go
> +	envThingsURL     = "MF_THINGS_URL"
Same here

2021-10-16 11:26 UTC, manuio commented on cmd/certs/main.go
> +		thingsURL:    mainflux.Env(envThingsURL, defThingsURL),
and here