MF-1443 - Add policies
absmach/magistrala pull request #1482
Opened 2021-10-25 12:00 UTC by dborovcanin

### What does this do?
This pull request introduces the initial version of policy support.

### Which issue(s) does this PR fix/relate to?
This pull request resolves #1443.

### List any changes that modify/break current functionality
Current access control is rewritten to use [Keto](https://github.com/ory/keto) implementation of [Google Zanzibar](https://research.google/pubs/pub48190/) authorization system. Please take a look at the issue description for more information. 

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
Yes.

### Notes
This is the initial version that introduces new access control to Mainflux and breaks compatibility with old versions. That is, we're yet to provide migration tools for a seamless transition to using policies. Manual transition can be done using the API provided in this pull request.

2021-10-25 16:49 UTC, tzzed reviewed
Hi @buraksekili and @dusanb94 kudos to you both.
I let myself to make a review about your PR I have some suggestions.

2021-10-25 16:49 UTC, tzzed commented on auth/api/http/policies/requests.go
> +var actions = [...]string{
You can use a map, `map[string]Action` that allows you to have a O(1) search a policy and create an efficient lookup function.

2021-10-25 16:49 UTC, tzzed commented on auth/api/grpc/endpoint.go
> +		return deletePolicyRes{deleted: true}, err
you can return `deletePolicyRes{deleted: true}, nil` instead of err.

2021-10-25 16:49 UTC, tzzed commented on auth/api/http/policies/requests.go
> +		if action := parsePolicy(policy); action > Member || action < Create {
If you use map as I suggested to you above it will let you to avoid this kind of check.

2021-10-25 16:49 UTC, tzzed commented on auth/service.go
> +	var errs error
I think it could be interesting to use [uber multierr](https://github.com/uber-go/multierr)

2021-10-25 16:49 UTC, tzzed commented on cmd/users/main.go
> +				return err
It will be more efficient to have a multi err here by chaining `err` from `auth.Authorize` and `auth.AddPolicy()`

2021-10-26 04:31 UTC, drasko requested changes

2021-10-26 04:31 UTC, drasko commented on auth/api/grpc/endpoint.go
> +		return deletePolicyRes{deleted: true}, err
I agree with this one - please put `nil` here because it indicates to the reader that if you arrived to this point in the code, there is no error. Code will be more self-documenting.

2021-10-26 06:47 UTC, arvindh123 commented on cmd/users/main.go
> +	if c.adminCreatesUser != "" {
It will be better if `c.adminCreatesUser` is compare with some constant string rather compare with `""` empty string
Example :
```suggestion
	if c.adminCreatesUser != "true" {
```

2021-10-26 06:47 UTC, arvindh123 commented on cmd/users/main.go
> +	if c.adminCreatesUser != "" {
It will be better if `c.adminCreatesUser` is compare with some constant string instead of comparing with `""` empty string
Example :
```suggestion
	if c.adminCreatesUser != "true" {
```

2021-10-26 06:54 UTC, arvindh123 commented on cmd/users/main.go
> +	if c.adminCreatesUser != "" {
So if admin only need to create users , 
then variable `MF_ONLY_ADMIN_CREATES_USER` should set to `true`
Or Can be make its as `Boolean`.?

2021-10-26 07:19 UTC, arvindh123 commented on docker/docker-compose.yml
> +      - DSN=postgresql://${MF_KETO_DB_USER}:${MF_KETO_DB_PASS}@keto-db:${MF_KETO_DB_PORT}/${MF_KETO_DB}?sslmode=disable
I think sslmode might required in future ,can be made it as env var 
similar to auth DB, 
Its possible to make like this env var
`MF_KETO_DB_SSL_MODE`
`MF_KETO_DB_SSL_CERT`
`MF_KETO_DB_SSL_KEY`
`MF_KETO_DB_SSL_ROOT_CERT`

2021-10-26 08:15 UTC, buraksekili commented on cmd/users/main.go
> +	if c.adminCreatesUser != "" {
The user configures the environment variables on the `.env` file and can write any arbitrary string as a value for a particular environment variable. I think, forcing a user to write a fixed value for the environment variable is not convenient. Of course, both ways will work in the end.

What I've done here is that if the user writes any value for the MF_ONLY_ADMIN_CREATES_USER (which eventually makes `c.adminCreatesUser != ""` true), it means that the only admin is capable to create new users.

2021-10-26 21:18 UTC, dborovcanin commented on cmd/users/main.go
> +				return err
In this case, i's OK to ignore the first error - it just indicates that the admin user does not have an admin policy.

2021-10-26 21:22 UTC, dborovcanin commented on docker/docker-compose.yml
> +      - DSN=postgresql://${MF_KETO_DB_USER}:${MF_KETO_DB_PASS}@keto-db:${MF_KETO_DB_PORT}/${MF_KETO_DB}?sslmode=disable
Created an [issue](https://github.com/mainflux/mainflux/issues/1485) for this.

2021-10-26 22:22 UTC, drasko approved these changes
LGTM

2021-10-26 22:38 UTC, merged

2021-10-26 22:39 UTC, drasko commented
WOW! Merged this huge one!

Thanks a lot @buraksekili and @dusanb94 for this wonderful contribution!