NOISSUE - Update naming of env variable
absmach/magistrala pull request #1484
Opened 2021-10-26 09:52 UTC by buraksekili

Signed-off-by: Burak Sekili <buraksekili@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
This PR updates name of the `MF_ONLY_ADMIN_CREATES_USER` environment variable to `MF_USERS_ALLOW_SELF_SIGNED` that is responsible for controlling who can create a new user. 

By default, it has a `"true"` value which means everybody can create a new user. If the user sets it to another string (other than an empty string), only the admin rather than everybody can create a new user. 

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2021-10-26 09:54 UTC, dborovcanin requested changes

2021-10-26 09:54 UTC, dborovcanin commented on cmd/users/main.go
> +	userSelfSigned string
This should be bool.

2021-10-26 09:55 UTC, buraksekili commented on cmd/users/main.go
> +	userSelfSigned string
okay, i will update it now

2021-10-26 15:01 UTC, dborovcanin approved these changes

2021-10-26 22:30 UTC, drasko requested changes

2021-10-26 22:30 UTC, drasko commented on cmd/users/main.go
> +	defUserSelfSigned = "true" // By default, everybody can create a user. Otherwise, only admin can create a user.
Instead of `selfSigned` please use `selfRegister`, so avoid confusion with signatures.

2021-10-27 08:07 UTC, buraksekili commented on cmd/users/main.go
> +	defUserSelfSigned = "true" // By default, everybody can create a user. Otherwise, only admin can create a user.
Updated to `selfRegister`.

2021-10-27 09:58 UTC, drasko approved these changes
LGTM

2021-10-27 09:58 UTC, merged