NOISSUE- fix renaming of mainflux-server to magistrala-server
absmach/magistrala pull request #15
Opened 2023-10-30 08:07 UTC by ianmuchyri

### What does this do?
Fix renaming of `mainflux-server.crt` and `mainflux-server.key` to `magistrala-server.crt `and `magistrala-server.key` respectively. This solves this issue encountered when trying to run nginx:
```
2023-10-30 10:31:01 2023/10/30 07:31:01 [emerg] 12#12: cannot load certificate "/etc/ssl/certs/mainflux-server.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/ssl/certs/mainflux-server.crt, r) error:10000080:BIO routines::no such file)
2023-10-30 10:31:01 nginx: [emerg] cannot load certificate "/etc/ssl/certs/mainflux-server.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/ssl/certs/mainflux-server.crt, r) error:10000080:BIO routines::no such file)
```
### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality
None
### Have you included tests for your changes?
No
### Did you document any new/modified functionality?
No
### Notes

2023-10-30 08:10 UTC, rodneyosodo requested changes

2023-10-30 08:10 UTC, rodneyosodo commented on docker/ssl/Makefile
>  server_cert:
Generate the certs too.

2023-10-30 08:24 UTC, rodneyosodo approved these changes
LGTM

2023-10-30 11:17 UTC, SammyOina approved these changes

2023-11-01 12:02 UTC, dborovcanin approved these changes

2023-11-01 12:03 UTC, merged