NOISSUE - Add channel update
absmach/magistrala pull request #1501
Opened 2021-11-18 14:06 UTC by fbugarski

Signed-off-by: fbugarski <filipbugarski@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2021-11-19 01:56 UTC, drasko requested changes

2021-11-19 01:56 UTC, drasko commented on ui/web/template/channels.html
> +                          <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
id must be changed, does not make sense

2021-11-19 01:56 UTC, drasko commented on ui/api/endpoint.go
> +		fmt.Println("chanupd")
Better remove now all printfs, let's start cleaning the code.

2021-11-19 01:56 UTC, drasko commented on ui/api/transport.go
> +	fmt.Println("paspdapsdpaspdapsdpaspdpasdpaspdpasdapsdpaspdpasd")
OK to keep validation commented for now, but remove these printfs as they polute the code

2021-11-19 01:56 UTC, drasko commented on ui/service.go
> +	// fmt.Println(btpl.String())
Remove

2021-11-19 21:38 UTC, drasko requested changes

2021-11-19 21:38 UTC, drasko commented on ui/service.go
> +		fmt.Println("servisni")
Remove printfs

2021-11-19 21:38 UTC, drasko commented on ui/service.go
> -	// if err := gs.thingCache.Remove(ctx, tpl); err != nil {
Remove dead code

2021-11-19 21:38 UTC, drasko commented on ui/web/template/thing.html
> +            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#updatethModal">
Bad naming - should be `UpdateThingModal` maybe, otherwise it is hard to read.

2021-11-23 12:20 UTC, mteodor commented on ui/api/transport.go
> +	// if !strings.Contains(r.Header.Get("Content-Type"), contentType) {
remove comments

2021-11-23 12:21 UTC, mteodor commented on ui/service.go
> +	err := gs.sdk.DeleteThing(id, "123")
what is this `123`

2021-11-23 12:54 UTC, fbugarski commented on ui/service.go
> +	err := gs.sdk.DeleteThing(id, "123")
Single user token

2021-11-26 13:14 UTC, drasko requested changes

2021-11-26 13:14 UTC, drasko commented on ui/web/template/channels.html
> +                    <td><a href={{printf "/channels/%s" $c.ID}}>{{$c.ID}} </a></td>
Kill this space

2021-11-26 14:18 UTC, drasko approved these changes
LGTM

2021-11-26 14:18 UTC, merged