NOISSUE - Add docker-compose for UI
absmach/magistrala pull request #153
Opened 2023-12-14 11:44 UTC by ianmuchyri

# What type of PR is this?
This is a feature because it add the UI service to the docker-compose file

## What does this do?
Adds UI service as part of the core services that are built and ran during docker-compose

## Which issue(s) does this PR fix/relate to?
NOISSUE

- Related Issue #
- Resolves #

## Have you included tests for your changes?
No, because this involves docker-compose and .env files

## Did you document any new/modified feature?
No

### Notes

2023-12-14 12:10 UTC, rodneyosodo requested changes

2023-12-14 12:10 UTC, rodneyosodo commented on docker/docker-compose.yml
> +    image: ghcr.io/absmach/magistrala-ui:${MG_RELEASE_TAG}
Since this is open source should we redirect the registry to `docker_hub` here https://github.com/absmach/magistrala-ui/blob/main/.github/workflows/build.yml so that it aligns with other image repositories

2023-12-14 12:50 UTC, dborovcanin commented on docker/docker-compose.yml
> +    image: ghcr.io/absmach/magistrala-ui:${MG_RELEASE_TAG}
@ianmuchyri Please fix this one. Also, set up the CI to push images to the Docker hub when we merge PRs.

2023-12-14 14:16 UTC, ianmuchyri commented on docker/docker-compose.yml
> +    image: ghcr.io/absmach/magistrala-ui:${MG_RELEASE_TAG}
This is addressed in this pr https://github.com/absmach/magistrala-ui/pull/35

2023-12-15 16:10 UTC, dborovcanin approved these changes

2023-12-15 16:10 UTC, merged