MF-1516 - Fix API key issuing
absmach/magistrala pull request #1530
Opened 2021-12-17 13:41 UTC by fbugarski

Signed-off-by: Filip Bugarski <filipbugarski@gmail.com>

### What does this do?

### Which issue(s) does this PR fix/relate to?
Resolve #1516 

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2021-12-20 07:47 UTC, dusanb94 requested changes

2021-12-20 07:47 UTC, dusanb94 commented on auth/service.go
> +
Remove the empty line.

2021-12-20 07:47 UTC, dusanb94 commented on auth/service.go
> +
Same here.

2021-12-20 07:47 UTC, dusanb94 commented on auth/api/logging.go
> +//go:build !test
What's this update?

2021-12-21 08:11 UTC, dusanb94 submitted a review, later dismissed

2021-12-22 16:33 UTC, arvindh123 commented on auth/api/http/keys/endpoint_test.go
> +	uk := issueRequest{Type: auth.LoginKey}
`uk` can be changed to `lk`

2021-12-22 16:33 UTC, arvindh123 commented on auth/api/http/keys/endpoint_test.go
>  		{
Status Created case is missing

2021-12-22 16:33 UTC, arvindh123 commented on auth/service_test.go
>  			desc: "issue user key",
Description can be changed to `issue login key`

2021-12-22 16:33 UTC, arvindh123 commented on auth/service_test.go
>  			desc: "issue user key with no time",
Description shall  be changed to `login key`

2021-12-22 16:33 UTC, arvindh123 commented on auth/service_test.go
>  	assert.Nil(t, err, fmt.Sprintf("Issuing user key expected to succeed: %s", err))
`user key` shall  be changed to `login key`
 and in line number `187`

2021-12-23 08:19 UTC, fbugarski commented on auth/api/http/keys/endpoint_test.go
>  		{
https://github.com/mainflux/mainflux/pull/1530/files/239cd8e8bbbc46f76ea0f8da5c2a331c60c8a1a4#diff-855631aac9bb09a01068f36624d2f806e885c9e055b9a08f4c351d69adf16ccfR118

2021-12-23 08:23 UTC, fbugarski commented on auth/api/http/keys/endpoint_test.go
>  		{
Line 118

2021-12-23 13:44 UTC, arvindh123 commented on auth/api/http/keys/endpoint_test.go
>  		{
Line 118 have test for `ak`  - `api key` 
But in `master` the there is test case for `user key` aka `login key` 
https://github.com/mainflux/mainflux/blob/ad8b7ddf5afac43699f7080d006dd40de0559222/auth/api/http/keys/endpoint_test.go#L107

2021-12-24 10:39 UTC, fbugarski commented on auth/api/http/keys/endpoint_test.go
>  		{
You cant create login key over HTTP API anymore.

2021-12-24 13:17 UTC, dusanb94 approved these changes

2021-12-24 13:53 UTC, drasko approved these changes
LGTM

2021-12-24 13:53 UTC, merged