Use id instead of email
absmach/magistrala pull request #1533
Opened 2021-12-23 11:06 UTC by mteodor

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2021-12-26 11:58 UTC, arvindh123 commented on pkg/sdk/go/groups.go
> +<<<<<<< HEAD
Git merge lines in code , These lines have any purpose ?

2022-02-01 08:45 UTC, manuio requested changes

2022-02-01 08:45 UTC, manuio commented on pkg/sdk/go/users_test.go
> +	// auth := mocks.NewAuthService(map[string]users.User{userEmail: user}, mockAuthzDB)
Should we remove this commented code?

2022-02-01 08:45 UTC, manuio commented on users/api/endpoint_test.go
> +	tkn, _ := auth.Issue(context.Background(), &mainflux.IssueReq{Id: user.ID, Email: user.Email, Type: 0})
Check the error here please

2022-04-14 11:06 UTC, manuio requested changes

2022-04-14 11:06 UTC, manuio commented on cli/users.go
> +			if len(args) < 2 || len(args) > 2 {
Why not `if len(args) != 2` ?

2022-05-24 23:24 UTC, drasko commented
@mteodor this looks very nice. We will review as soon as we finish with these broker abstractions.

2022-06-29 10:15 UTC, mteodor commented
> @mteodor this looks very nice. We will review as soon as we finish with these broker abstractions.

@drasko I hoped that this would be merged before Vidovdan so I could celebrate properly, but to no avail

2022-10-26 17:29 UTC, mteodor commented
closed due to inactivity

2022-10-26 17:29 UTC, closed without merging