MF-1535 - Add API keys functions to SDK
absmach/magistrala pull request #1536
Opened 2021-12-30 16:06 UTC by fbugarski

### What does this do?
Add API keys functions to SDK
### Which issue(s) does this PR fix/relate to?
Resolves #1535 

### List any changes that modify/break current functionality

### Have you included tests for your changes?
No
### Did you document any new/modified functionality?
No
### Notes

2021-12-30 16:29 UTC, drasko requested changes

2021-12-30 16:29 UTC, drasko commented on pkg/sdk/go/sdk.go
> +//Member represents mainflux member.
Space after `//`

2021-12-30 16:30 UTC, drasko commented
@fbugarski there are conflicts on this branch that must be resolved

2022-01-05 20:04 UTC, drasko requested changes

2022-01-05 20:04 UTC, drasko commented on pkg/sdk/go/sdk.go
> +// Member represents mainflux member.
This is unclear? What is `mainflux member`? You mean `group member`?

2022-01-05 20:04 UTC, drasko commented on pkg/sdk/go/requests.go
> +// It is not possible to issue Reset key using HTTP API.
This is a confusing comment. This comment is supposed to describe what is implemented below, but looks like it does not.

2022-01-05 20:04 UTC, drasko commented on pkg/sdk/go/sdk.go
> +	// Issue issues a new Key, returning its token value alongside.
Do we need to capitalize `Key` in this comment? Maybe simple `key` would be more appropriate?

2022-01-05 20:04 UTC, drasko commented on pkg/sdk/go/sdk.go
> +	// RetrieveKey retrieves data for the Key identified by the provided ID, that is issued by the user identified by the provided key.
In the upper comment you worte `id`, and here `ID`. Please stay consistent.

2022-01-06 16:18 UTC, drasko approved these changes
LGTM

2022-01-10 09:39 UTC, manuio approved these changes
LGTM

2022-01-12 12:24 UTC, dusanb94 approved these changes
@fbugarski Please don't forget to open an issue for SDK API keys tests.

2022-01-12 12:24 UTC, merged