MF-1582 - Fix lora-adapter MQTT clien
absmach/magistrala pull request #1583
Opened 2022-03-21 15:18 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

### What does this do?
Fix the lora-adapter MQTT client
### Which issue(s) does this PR fix/relate to?
Resolves #1582

2022-03-21 19:09 UTC, mteodor submitted a review, later dismissed

2022-03-23 22:41 UTC, drasko requested changes

2022-03-23 22:41 UTC, drasko commented on cmd/lora/main.go
> +	defLoraMsgTimeout = "30s" // 30 seconds
Consider removing this comment, it is obvious what `30s` means if the variable is called `...Timeout`

2022-03-27 13:26 UTC, dusanb94 requested changes

2022-03-27 13:26 UTC, dusanb94 commented on lora/mqtt/sub.go
> +	if err := s.Error(); s.Wait() && err != nil {
I would suggest using `WaitTimeout` to prevent infinite wait.

2022-03-29 09:31 UTC, mteodor approved these changes

2022-04-11 11:42 UTC, drasko approved these changes
LGTM

2022-04-11 11:52 UTC, dusanb94 approved these changes

2022-04-11 11:52 UTC, merged