NOISSUE - Implementation of  Group Delete
absmach/magistrala pull request #161
Opened 2023-12-15 13:14 UTC by arvindh123

# What type of PR is this?
Implements Group Delete

## What does this do?

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2023-12-15 13:37 UTC, rodneyosodo requested changes

2023-12-15 13:37 UTC, rodneyosodo commented on internal/groups/events/streams.go
> +	_, err := es.delete(ctx, groups.Group{ID: id})
This should have a different operation name

2023-12-15 13:37 UTC, rodneyosodo commented on auth/api/grpc/requests.go
> +	// if req.Subject == "" || req.SubjectType == "" {
Uncomment

2023-12-15 13:37 UTC, rodneyosodo commented on internal/groups/postgres/groups.go
> +	q := "UPDATE groups AS g SET parent_id = NULL WHERE g.parent_id = $1 ;"
Shouldn't this be done at the database level with something like a trigger?

2023-12-15 16:13 UTC, arvindh123 commented on internal/groups/postgres/groups.go
> +	q := "UPDATE groups AS g SET parent_id = NULL WHERE g.parent_id = $1 ;"
`FOREIGN KEY (parent_id) REFERENCES groups (id) ON DELETE SET NULL`

`ON DELETE SET NULL` will be replacement for this function

2023-12-15 16:26 UTC, arvindh123 commented on internal/groups/postgres/groups.go
> +	q := "UPDATE groups AS g SET parent_id = NULL WHERE g.parent_id = $1 ;"
Resolved

2023-12-15 16:30 UTC, arvindh123 commented on auth/api/grpc/requests.go
> +	// if req.Subject == "" || req.SubjectType == "" {
Created issue, I will do in seperate PR https://github.com/absmach/magistrala/issues/170

2023-12-15 16:33 UTC, rodneyosodo commented on auth/api/grpc/requests.go
> +	// if req.Subject == "" || req.SubjectType == "" {
You can remove the code block and let it return nil

2023-12-15 16:35 UTC, rodneyosodo requested changes

2023-12-15 16:35 UTC, rodneyosodo commented on internal/groups/events/events.go
> +	groupDelete          = groupPrefix + "delete"
Also change `groupRemove` to `groupChangeStatus`

2023-12-15 16:45 UTC, arvindh123 commented on internal/groups/events/events.go
> +	groupDelete          = groupPrefix + "delete"
done

2023-12-15 16:45 UTC, arvindh123 commented on auth/api/grpc/requests.go
> +	// if req.Subject == "" || req.SubjectType == "" {
done

2023-12-18 08:23 UTC, rodneyosodo requested changes
Also, the internal implementation of groups should take `streamID` as a parameter so that when it is being used for users case it is `magistrala.users` and for things it is `magistrala.things`.

Also SDK and CLI functions are missing

2023-12-18 08:23 UTC, rodneyosodo commented on bootstrap/events/consumer/streams.go
> +		rce := decodeDeleteChannel(msg)
```suggestion
		dce := decodeDeleteChannel(msg)
```

2023-12-18 08:23 UTC, rodneyosodo commented on internal/groups/events/events.go
> -	_ events.Event = (*removeGroupEvent)(nil)
Also add a type check for  `deleteGroupEvent`

2023-12-18 13:19 UTC, rodneyosodo requested changes

2023-12-18 13:19 UTC, rodneyosodo commented on cli/channels.go
> +			if err != nil {
Inline

2023-12-18 13:19 UTC, rodneyosodo commented on cli/groups.go
> +			err := sdk.DeleteGroup(args[0], args[1])
Same

2023-12-18 13:29 UTC, rodneyosodo approved these changes
LGTM

2023-12-19 10:38 UTC, dborovcanin requested changes

2023-12-19 10:38 UTC, dborovcanin commented on internal/groups/service.go
> +	}
Is it possible to execute these in a single request to the Auth? I.e. create a separate gRPC endpoint for this?

2023-12-19 12:00 UTC, dborovcanin commented on internal/groups/service.go
> +	}
Opened relevant issue: #188.

2023-12-19 12:00 UTC, dborovcanin approved these changes

2023-12-19 12:01 UTC, merged