NOISSUE - Add identify thing method to SDK
absmach/magistrala pull request #1617
Opened 2022-06-14 16:00 UTC by 0x6f736f646f

Signed-off-by: 0x6f736f646f <blackd0t@protonmail.com>

### What does this do?
Adds identify thing to SDK

### Which issue(s) does this PR fix/relate to?
N/A

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
N/A

2022-06-14 17:19 UTC, manuio requested changes, later dismissed

2022-06-14 17:19 UTC, manuio commented on cli/things.go
> +		Long:  "Validates thing's key and returns it's ID if key is valid",
`returns its ID`

2022-06-14 17:19 UTC, manuio commented on pkg/sdk/go/things.go
> +	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(data))
Are you sure that this HTTP endpoint exist in Things service?

2022-06-14 17:38 UTC, 0x6f736f646f commented on pkg/sdk/go/things.go
> +	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(data))
No

2022-06-14 17:46 UTC, manuio commented on pkg/sdk/go/things.go
> +	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(data))
If I remember well it only exist for gRPC

2022-06-14 17:53 UTC, 0x6f736f646f commented on pkg/sdk/go/things.go
> +	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(data))
What about it reference [here](https://api.mainflux.io/?urls.primaryName=things.yml#/identity/post_identify)

2022-06-16 09:13 UTC, dusanb94 requested changes
What's the purpose of this PR? There is no `identify` HTTP endpoint and for a reason - there should not be such an endpoint. How did you test the code before sending a PR?

2022-06-16 13:23 UTC, 0x6f736f646f commented
> What's the purpose of this PR? There is no `identify` HTTP endpoint and for a reason - there should not be such an endpoint. How did you test the code before sending a PR?

I saw it [here](https://api.mainflux.io/?urls.primaryName=things.yml#/identity/post_identify)

2022-06-16 14:23 UTC, dusan-borovcanin reviewed
We do actually have an API for this. While I don't see many use cases for it to work with CLI, let's add tests and support it, since there is an exposed API for this feature.

2022-06-22 17:16 UTC, dusan-borovcanin requested changes

2022-06-22 17:16 UTC, dborovcanin commented on pkg/sdk/go/things.go
> +	datareq := identifyThingReq{Token: key}
`idReq := identifyThingReq{Token: key}`

2022-06-22 17:16 UTC, dborovcanin commented on pkg/sdk/go/things_test.go
> +			thingKey: "123e4567-e89b-12d3-a456-000000000001",
Where does this key come from?

2022-06-23 18:54 UTC, dusan-borovcanin approved these changes

2022-06-24 14:28 UTC, drasko approved these changes
LGTM

2022-06-24 14:31 UTC, merged