MF-1197-MQTT tests
absmach/magistrala pull request #1622
Opened 2022-06-24 13:07 UTC by zzokki81

### What does this do?
Added MQTT unit tests

### Which issue(s) does this PR fix/relate to?
`Resolves #1197 ` 

### List any changes that modify/break current functionality

### Have you included tests for your changes?
MQTT unit tests

### Did you document any new/modified functionality?
No
### Notes

2022-06-27 09:10 UTC, manuio requested changes

2022-06-27 09:10 UTC, manuio commented on mqtt/handler_test.go
> +			desc:    "should return error if client is nil",
The description should explain the test that you are doing not the error that is supposed to return. In this case it can be `Handle message without active session`.

Same for all other description

2022-06-27 09:10 UTC, manuio commented on mqtt/mocks/client.go
> +
kill this blank line

2022-06-27 09:12 UTC, manuio requested changes

2022-06-27 09:12 UTC, manuio commented on mqtt/handler_test.go
> +func TestHandler_AuthConnect(t *testing.T) {
Rename the method `TestAuthConnect`

2022-06-27 09:12 UTC, manuio commented on mqtt/handler_test.go
> +func TestHandler_AuthPublish(t *testing.T) {
Rename `TestAuthPublish`

2022-06-28 08:43 UTC, manuio requested changes

2022-06-28 08:43 UTC, manuio commented on mqtt/handler_test.go
> +		err := setupTest().AuthSubscribe(tc.client, tc.topic)
Create the session handler outside the for loop: `handler := createHandler()`

2022-06-28 08:43 UTC, manuio commented on mqtt/handler_test.go
> +			desc:   "Handle subscribe authorization on client without active session",
Avoid repeting `Handle subscribe authorization on client` for all descriptions. For example here `Subscribe without active session` would be enough

2022-06-28 15:42 UTC, manuio requested changes

2022-06-28 15:42 UTC, manuio commented on mqtt/handler_test.go
> +
remove this blank line

2022-06-28 15:42 UTC, manuio commented on mqtt/handler_test.go
> +				Username: "testUsername",
create a global const and use it in all tests

2022-06-28 15:44 UTC, manuio requested changes

2022-06-28 15:44 UTC, manuio commented on mqtt/handler_test.go
> +			desc: "connect when id is invalid",
`connect with valid id`

2022-06-28 15:44 UTC, manuio commented on mqtt/handler_test.go
> +			err:  errors.New("thing identify error"),
Remove this error and use one from the package. If there is no error in the package maybe you can change a bit the code and wrap the returned error with a new one.

2022-06-28 15:44 UTC, manuio commented on mqtt/handler_test.go
> +			desc: "connect when username is invalid",
`connect with valid password and invalid username`

2022-06-28 15:44 UTC, manuio commented on mqtt/handler_test.go
> +			desc: "connect with right username and password",
`connect with valid username and password"`

2022-07-04 13:58 UTC, manuio requested changes

2022-07-04 13:58 UTC, manuio commented on mqtt/handler_test.go
> +	"testing"
Move this 2 packets to the top

2022-07-04 13:58 UTC, manuio commented on mqtt/handler_test.go
> +	usernameOK = "ok"
Why not to use a single user for the tests?

2022-07-05 16:45 UTC, manuio requested changes

2022-07-05 16:45 UTC, manuio commented on mqtt/handler_test.go
> +		panic(err)
Replace it by something like `log.Fatalf("Could not create logger: %s", err))`

2022-07-06 11:11 UTC, manuio requested changes

2022-07-06 11:11 UTC, manuio commented on mqtt/handler_test.go
> +	username        = "username"
Since we are using thingID as MQTT username it would be better to use an uuid here:
```
	thingID  = "thingID"
```

2022-07-06 11:11 UTC, manuio commented on mqtt/handler_test.go
> +	invalidUsername = "invalidUsername"
`invalidID = "invalidID"`

2022-07-06 11:11 UTC, manuio commented on mqtt/handler_test.go
> +	var payload = []byte("payload")
Use a valid payload. For example `[]byte("[{"n":"test-name", "v": 1.2}]")`

2022-07-06 11:11 UTC, manuio commented on mqtt/handler_test.go
> +			err:     errNilClient,
It's not realted to this PR but can you change this error name please? `errInactiveSession` for example

2022-07-06 11:11 UTC, manuio commented on mqtt/handler_test.go
> +	eventStore := redis.NewEventStore(redisClient, "")
No need to create a real even store. Use a mock instead. The only method to implement is the one reaturning the client ID: `ID()`

2022-07-08 12:06 UTC, manuio requested changes

2022-07-08 12:06 UTC, manuio commented on mqtt/handler_test.go
> +			desc: "connect with valid id",
`connect with invalid password"` 

Maybe you can add another test with empty client ID?

2022-07-08 12:06 UTC, manuio commented on mqtt/handler_test.go
> +			desc:    "publish without active session",
`publish with inactive client`

2022-07-08 12:06 UTC, manuio commented on mqtt/handler_test.go
> +			desc:    "publish with active session, valid topic and payload",
`publish with malformed topic`

2022-07-08 14:07 UTC, manuio requested changes

2022-07-13 07:47 UTC, manuio requested changes

2022-07-13 07:47 UTC, manuio commented on mqtt/handler_test.go
> +			topic:    "topic",
Use a valid topic here to be sure that the error comes from the inactive session

2022-07-13 07:47 UTC, manuio commented on mqtt/handler_test.go
> +			desc:     "publish with invalid channel parts",
This should be `publish with invalid topic`

2022-07-13 07:47 UTC, manuio commented on mqtt/handler_test.go
> +			expected: "published with client_id " + clientID + " to the topic: " + "topic",
Create a variable for this error

2022-07-13 07:47 UTC, manuio commented on mqtt/handler_test.go
> +			expected: "failed to subscribe: " + errMissingClient.Error(),
Create an error for `failed to subscribe:`

2022-07-14 09:02 UTC, manuio requested changes

2022-07-14 09:02 UTC, manuio commented on mqtt/handler.go
> +		h.logger.Warn("failed to publish connect event: " + err.Error())
I'd change this `Warn` by `Error` and create a const for the message

2022-07-14 09:05 UTC, manuio requested changes

2022-07-14 09:05 UTC, manuio commented on mqtt/handler.go
> +		h.logger.Warn("failed to publish disconnect event: " + err.Error())
Same here. `logger.Error` and create a const for the message. Also, test it

2022-07-20 08:14 UTC, manuio requested changes

2022-07-20 08:14 UTC, manuio commented on mqtt/handler_test.go
> +				Password: []byte("password"),
Use `password` const here

2022-07-20 08:14 UTC, manuio commented on mqtt/handler_test.go
> +			err:  nil,
Is it normal to don't return error if client ID is empty?

2022-07-20 08:17 UTC, manuio requested changes

2022-07-20 08:17 UTC, manuio commented on mqtt/handler_test.go
> +	var invalidTopic = "invalidTopic"
This var is used in several tests, create a const instead.

2022-08-18 19:29 UTC, manuio requested changes

2022-08-18 19:29 UTC, manuio commented on mqtt/handler_test.go
> +		{
`publish successfully` test is missing

2022-08-18 19:29 UTC, manuio commented on mqtt/handler_test.go
> +			desc:     "connect with valid session",
`connect with active session` would be more consistent with previous message

2022-08-18 19:29 UTC, manuio commented on mqtt/handler_test.go
> +			expected: fmt.Sprint(errors.Wrap(mqtt.ErrFailedConnect, mqtt.ErrClientNotInitialized).Error()),
use `err: errors.Wrap(mqtt.ErrFailedConnect, mqtt.ErrClientNotInitialized)` here and extract the string latter

2022-08-18 19:29 UTC, manuio commented on mqtt/handler_test.go
> +		expected string
`err`

2022-08-18 19:29 UTC, manuio commented on mqtt/handler_test.go
> +	buf.Reset()
I'd rename `buf` `logBuffer`

2022-08-19 15:26 UTC, manuio approved these changes, later dismissed
LGTM

2022-08-22 10:42 UTC, dborovcanin requested changes
Testing using log messages is usually not a good idea. While it makes sense for some methods, we definitely should not spin Redis for each `newHandler` call, and we should use an error message to compare (see error wrapping), not hardcoded log constants.

2022-08-22 10:42 UTC, dborovcanin commented on mqtt/handler_test.go
> +	container, err := pool.Run("redis", "5.0-alpine", nil)
Spinning a new Docker container for each `newHandler` call is not a good idea. Why do we even use Redis and not mock for events?

2022-08-23 09:24 UTC, manuio approved these changes, later dismissed
LGTM

2022-09-13 10:18 UTC, dborovcanin requested changes
This obscure testing of logs pointed out potential flows in mProxy. Also, we should definitely decouple mutual dependency between Mainflux and mProxy (mProxy is using Mainflux errors, while Mainflux is using mProxy in MQTT adapter).

2022-09-13 10:18 UTC, dborovcanin commented on mqtt/handler.go
> +	LogErrFailedPublishToMsgBroker     = "failed to publish to mainflux message broker: "
Put log messages to a separate `const` block.

2022-09-13 10:18 UTC, dborovcanin commented on mqtt/handler.go
> +	errMalformedSubtopic               = errors.New("malformed subtopic")
Is this error covered by tests?

2022-09-13 10:18 UTC, dborovcanin commented on mqtt/handler_test.go
> +	logBuffer     = bytes.Buffer{}
Add a comment, something like:
Test log messages for cases the handler does not provide a return value.

2022-09-30 09:10 UTC, manuio approved these changes, later dismissed
LGTM

2022-11-17 10:56 UTC, dborovcanin requested changes
While checking the log message is a quirky way to test - for some methods that don't return errors but log them - that's the only way. I left only one cosmetical remark and we can merge.

2022-11-17 10:56 UTC, dborovcanin commented on mqtt/handler.go
> +	protocol                           = "mqtt"
Keep `protocol` as a separate constant, since this is a block for logging constants.

2022-11-17 12:33 UTC, manuio approved these changes
LGTM

2022-11-17 13:21 UTC, dborovcanin approved these changes

2022-11-21 13:40 UTC, drasko approved these changes
LGTM

2022-11-21 13:40 UTC, merged

2022-11-21 13:41 UTC, drasko commented
Merged! Thanks @zzokki81. This was a nice solution with log analysis, but we should improve in the future by adding return values to the handlers. Issue opened for tracking here: https://github.com/ultravioletrs/issues/issues/109

2022-11-21 13:47 UTC, dborovcanin commented
The main improvement would be adding return errors where it's missing, and using pubsub mocks to check if pubsub methods are called for successful flow (rather than checking for info logs). Also, moving the logger from the handler implementation to the logging wrapper/middleware is a good idea.

2022-11-21 13:49 UTC, drasko commented
Issue to track: https://github.com/mainflux/mproxy/issues/31