MF-888 - Add groups tests
absmach/magistrala pull request #1629
Opened 2022-07-19 13:58 UTC by zzokki81

### What does this do?
Added SDK tests
### Which issue(s) does this PR fix/relate to?
Resolves #888 

### List any changes that modify/break current functionality

### Have you included tests for your changes?
SDK Tests
### Did you document any new/modified functionality?
No
### Notes

2022-08-11 13:48 UTC, manuio requested changes

2022-08-11 13:48 UTC, manuio commented on pkg/sdk/go/bootstrap_test.go
> +			desc: "view a config with wrong credentials",
`invalid token` is probably clearer

2022-08-11 13:48 UTC, manuio commented on pkg/sdk/go/bootstrap_test.go
> +			desc:   "update config with wrong credentials",
I'd keep `update config with invalid token`

2022-08-11 13:48 UTC, manuio commented on pkg/sdk/go/bootstrap_test.go
> +			desc:   "update config  with empty token",
There are 2 white spaces after `config`

2022-08-11 13:48 UTC, manuio commented on pkg/sdk/go/bootstrap_test.go
> +			desc:       "update cert with with wrong credentials",
Same here

2022-08-11 13:48 UTC, manuio commented on pkg/sdk/go/bootstrap_test.go
> +			desc:  "remove config with wrong credentials",
and here

2022-08-15 15:30 UTC, manuio requested changes

2022-08-15 15:30 UTC, manuio commented on pkg/sdk/go/certs.go
>  	Valid      string `json:"valid"`
You can remove `Valid` field since it's replaced by `TTL`

2022-08-15 15:30 UTC, manuio commented on pkg/sdk/go/certs_test.go
> +			keyBits: 2048,
Create a const and use it in all cases

2022-08-15 15:30 UTC, manuio commented on pkg/sdk/go/responses.go
> +type PageRes struct {
Is this really needed?

2022-08-16 10:52 UTC, manuio requested changes

2022-08-16 10:52 UTC, manuio commented on pkg/sdk/go/keys_test.go
> +			desc:     "Issue a new key",
`issue` would be more consistent here

2022-08-16 10:52 UTC, manuio commented on pkg/sdk/go/certs_test.go
> +			desc:    "issue new cert with no thing id",
`emtpy thing ID"`

2023-02-10 07:57 UTC, dborovcanin commented
@zzokki81 Can you, please, resolve conflicts so we can review the PR?

2023-02-14 14:44 UTC, zzokki81 commented
There was changes in SDK



> @zzokki81 Can you, please, resolve conflicts so we can review the PR?
Sure, I'll take a look at that.

2024-06-26 06:06 UTC, arvindh123 approved these changes, later dismissed

2024-10-18 13:07 UTC, dborovcanin commented
This PR has some interesting ideas, but it's been out of date with no signs of any updates, so I'm closing it.

2024-10-18 13:07 UTC, closed without merging