NOISSUE - Combining Query Parameters
absmach/magistrala pull request #1631
Opened 2022-07-25 19:47 UTC by 0x6f736f646f

Signed-off-by: b1ackd0t <blackd0t@protonmail.com>

### What does this do?
Combines the query parameters to PageMetadata such that we don't need to pass Offset, Limit e.t.c but we pass the PageMetadata that contains these fields

### Which issue(s) does this PR fix/relate to?
N/A

### List any changes that modify/break current functionality
Combines the different query parameters to one struct, `PageMetadata`

### Have you included tests for your changes?
Yes

### Did you document any new/modified functionality?
No

### Notes
N/A

2022-09-05 11:17 UTC, mteodor approved these changes, later dismissed

2022-09-20 15:19 UTC, dborovcanin commented
Please resolve conflicts so we can review.

2023-01-04 13:08 UTC, dborovcanin requested changes
Check if you updated all the cases of SDK usage. I see some errors in the Provision service (where we don't have tests, so please test manually).

2023-01-04 15:41 UTC, dborovcanin approved these changes

2023-01-05 16:19 UTC, drasko approved these changes
LGTM

2023-01-05 16:20 UTC, merged