MF-1636 - add certs endpoints test
absmach/magistrala pull request #1637
Opened 2022-08-10 15:18 UTC by zzokki81

Signed-off-by: zzokki81 <zoran.rebic@outlook.com>

### What does this do?
Added tests for certs endpoints
### Which issue(s) does this PR fix/relate to?
Resolves #1636

### List any changes that modify/break current functionality
N/A
### Have you included tests for your changes?
Certs endpoint tests
### Did you document any new/modified functionality?
No
### Notes
N/A

2022-08-15 18:39 UTC, manuio requested changes

2022-08-15 18:39 UTC, manuio commented on certs/api/endpoint_test.go
> +		require.Nil(t, err, fmt.Sprintf("Saving config expected to succeed: %s.\n", err))
I'd say `Certificate issuing` instead of `Saving config`

2022-08-15 18:39 UTC, manuio commented on certs/api/endpoint_test.go
> +			desc:        "issue new cert  with invalid request format",
Fix the double white space

2022-08-15 18:39 UTC, manuio commented on certs/api/endpoint_test.go
> +			desc:   "list all certs with invalid limit ",
Remove the white space at the end of the sentence

2022-08-15 18:39 UTC, manuio commented on certs/api/endpoint_test.go
> +			desc:   "list certificate data with wrong certID",
`with invalid certificate ID`

2022-08-15 18:39 UTC, manuio commented on certs/api/endpoint_test.go
> +			desc:   "list certificate data with no certID",
`with empty cerificatet ID`

2022-08-15 18:39 UTC, manuio commented on certs/api/endpoint_test.go
> +			desc:   "list certs serial ID's for wrong thing",
`with invalid thing ID`

2022-08-15 18:39 UTC, manuio commented on certs/api/endpoint_test.go
> +	neThingID := addReq
I'd use `wrongAddReq`

2022-08-15 18:39 UTC, manuio commented on certs/api/endpoint_test.go
> +			desc:        "issue new cert for non existing thing id",
`thing ID`

2022-08-16 09:46 UTC, manuio requested changes

2022-08-16 09:46 UTC, manuio commented on certs/api/endpoint_test.go
> +			desc:   "list certificate data with empty certID",
`empty certificate ID`

2024-10-18 13:09 UTC, dborovcanin commented
This PR has some interesting ideas, but it's been out of date with no signs of any updates, so I'm closing it. @nyagamunene Please take a look and consider this for MG Certs service tests in a different PR.

2024-10-18 13:09 UTC, closed without merging