MF-1644 - Initial Postman Commit
absmach/magistrala pull request #1645
Opened 2022-08-16 19:37 UTC by EddahMurrey

Signed-off-by: atrox <edamurrey@outlook.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Adds mainflux postman collection
### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)
Resolves #1644 
### List any changes that modify/break current functionality
None
### Notes
N/A

2022-08-16 22:07 UTC, drasko requested changes
@EddahMurrey please rename directory to `postman`, it is simpler (no need for `collection`).

Additionally - this looks good, but it also looks huge. Can we break this into different JSON files, one per microservice?

Also, if we break it like this - will we be capable to load multiple of those at the same time in Postman (not have to load one by one, where pone would remove previous)?

@dborovcanin looks like Postman can easily import multiple Swagger files and create collection: https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#importing-api-specifications. If this is the case, do we even need Postman collections in the repo (since it can be easily generated from Swagger files)?

2022-08-17 10:37 UTC, EddahMurrey commented
@drasko I think we can be able to load multiple files at the same time. Did you mean like the below picture?
![Screenshot from 2022-08-17 12-34-43](https://user-images.githubusercontent.com/23095882/185098466-78643718-8f41-4552-9cfb-e9743d985df3.png)

2022-08-17 15:33 UTC, drasko commented
> @drasko I think we can be able to load multiple files at the same time. Did you mean like the below picture?

Yes - exactly like this.

Then, I would definitely propose that we break this big collection into smaller ones - one per microservice used in Mainflux.

2022-08-17 15:36 UTC, drasko requested changes
This is good, just a few corrections:
1. We use the plural in the service name `things`, `users`, etc...
2. Some of the API functionalities are part of another microservice and should be in the same collection - for example `channels` are part of `things` microservice

2022-08-18 21:09 UTC, drasko requested changes

2022-08-18 21:09 UTC, drasko commented on api/postman/groups.json
>  {
I think Groups and API Key are currently part of Auth microservice

2022-08-22 11:14 UTC, dborovcanin commented
> @dborovcanin looks like Postman can easily import multiple Swagger files and create collection: https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#importing-api-specifications. If this is the case, do we even need Postman collections in the repo (since it can be easily generated from Swagger files)?

@drasko @EddahMurrey Since that's the case, we probably do not need a separate collection(s). It will only make it more complex to maintain and keep them in sync. However, in that case, we should revisit and update OpenAPI docs and add examples to them - so Postman can generate nice and usable out-of-box collections.

2022-09-05 11:06 UTC, mteodor commented
will this be used for testing?

2022-10-26 09:35 UTC, dborovcanin commented
> will this be used for testing?

Since we already have Openapi files, and they can be imported into Postman, we decided to improve the examples there and drop this pull request.

2022-10-26 09:35 UTC, closed without merging