MF-1654 - Fix Topic Parsing in RabbitMQ Broker
absmach/magistrala pull request #1655
Opened 2022-09-16 13:59 UTC by 0x6f736f646f

### What does this do?
Fixes topic parsed when using rabbitmq message broker

### Which issue(s) does this PR fix/relate to?
Resolves #1654 

### List any changes that modify/break current functionality
- Instead of using direct exchange in rabbitmq this change implements topic based routing of messages
- Parses NATS topic to rabbitmq understandable topic

### Have you included tests for your changes?
Yes

### Did you document any new/modified functionality?
No

### Notes
Possible issue was topic structure difference between NATS and RabbitMQ. The system was initially built with NATS topic configuration. RabbitMQ accepts # as wildcard to match more words (e.g., a routing pattern of "channels.<channel_id>.#" matches any routing keys beginning with "channels.<channel_id>.messages" and "channels.<channel_id>.<any_other_subtopic>").
With this problem I would suggest to change to Topic exchange rather than Direct exchange as currently used. This is because with topic exchange we can even poll messages from all subtopics.
This now brings a challenge when using different brokers based on the wild cards of each broker. This is because nats and rabbitmq use different wildcard to match any topic for instance in nats it it > while in rabbitmq it is #. I suggest we have one main message format used by mainflux then the different brokers reformat the topic when publishing and subscribing or unsubscribing. Another way would be to have every broker have a way to format its message so that other services can call it. For instance during mqtt forwarding and also when parsing URL to topic and subtopic.

2022-09-21 13:24 UTC, dborovcanin commented on pkg/messaging/rabbitmq/pubsub.go
> +	_, err := ps.ch.QueueDeclare(topic, true, false, false, false, nil)
Inline: `if _, err := ....`

2022-09-28 23:12 UTC, drasko requested changes

2022-09-28 23:12 UTC, drasko commented on pkg/messaging/rabbitmq/publisher.go
> +			DeliveryMode: 2,
What are those magic numbers? These need to be numerical constants, defined at the top of the file with comments explaining their meaning.

2022-10-21 08:55 UTC, dborovcanin approved these changes

2022-10-21 10:06 UTC, drasko approved these changes
LGTM

2022-10-21 10:06 UTC, merged