MF-1678 - Fetching users returns an invalid status code response
absmach/magistrala pull request #1679
Opened 2022-12-05 12:35 UTC by arvindh123

Signed-off-by: Arvindh <arvindh91@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Fix the http response code and response body for unauthorized get request to list users endpoint   

### Which issue(s) does this PR fix/relate to?
Resolves #1678    

### List any changes that modify/break current functionality
It fixes the status code response for `/users` endpoint of Users service.

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2022-12-06 08:11 UTC, manuio submitted a review, later dismissed
LGTM

2022-12-07 11:11 UTC, dborovcanin requested changes

2022-12-07 11:11 UTC, dborovcanin commented on users/service_test.go
> +		"list users of non existence ": {
`list using non-existent user`

2022-12-07 11:15 UTC, dborovcanin approved these changes

2022-12-07 11:22 UTC, drasko approved these changes
LGTM

2022-12-07 11:31 UTC, merged