MF-1455 - Update Versions of Protobuf
absmach/magistrala pull request #1704
Opened 2023-01-16 15:15 UTC by rodneyosodo

Signed-off-by: rodneyosodo <socials@rodneyosodo.com>

### What does this do?
Updates versions of protobuf

### Which issue(s) does this PR fix/relate to?
Resolves #1455

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
N/A

2023-01-26 09:45 UTC, dborovcanin requested changes

2023-01-26 09:45 UTC, dborovcanin commented on Makefile
> +	protoc -I. --go_out=. --go_opt=paths=source_relative pkg/messaging/*.proto
The line above (gRPC part) is still using gogo Probufs (gofast_out).

2023-01-27 11:28 UTC, dborovcanin approved these changes

2023-01-27 11:33 UTC, dborovcanin submitted a review, later dismissed

2023-02-01 23:24 UTC, drasko requested changes

2023-02-01 23:24 UTC, drasko commented on pkg/transformers/senml/transformer_test.go
> +	// 82AD2169626173652D6E616D6522F956402369626173652D756E6974200A24F9490025F9564000646E616D650164756E697406F95CB0036331323307F958B002F9514005F94900AA2169626173652D6E616D6522F956402369626173652D756E697
What is this? Some dead code? Or a regular comment?

2023-02-02 12:07 UTC, rodneyosodo commented on pkg/transformers/senml/transformer_test.go
> +	// 82AD2169626173652D6E616D6522F956402369626173652D756E6974200A24F9490025F9564000646E616D650164756E697406F95CB0036331323307F958B002F9514005F94900AA2169626173652D6E616D6522F956402369626173652D756E697
It was initially there

2023-02-02 12:16 UTC, drasko approved these changes
LGTM

2023-02-02 17:27 UTC, dborovcanin approved these changes

2023-02-02 17:28 UTC, merged

2023-07-05 08:46 UTC, rodneyosodo commented
Resolves https://github.com/mainflux/mainflux/issues/1287