MF-1698 - Add Fatal in Mainflux logger
absmach/magistrala pull request #1721
Opened 2023-02-11 20:46 UTC by AryanGodara

Signed-off-by: aryan <aryangodara03@gmail.com>

### Which issue(s) does this PR fix/relate to?
Resolves https://github.com/mainflux/mainflux/issues/1698

### List any changes that modify/break current functionality
Nil
### Have you included tests for your changes?
No
### Did you document any new/modified functionality?
No
### Notes
Nil

2023-02-17 12:20 UTC, rodneyosodo approved these changes, later dismissed

2023-02-20 10:56 UTC, dborovcanin requested changes

2023-02-20 10:56 UTC, dborovcanin commented on logger/level.go
> +	Fatal Level = iota + 1
There is no need for a new log level. Let's make fatal always exit.

2023-02-21 10:15 UTC, dborovcanin approved these changes

2023-02-21 12:02 UTC, drasko approved these changes
LGTM

2023-02-21 12:02 UTC, merged