MF-1720 - Improve Test Reports
absmach/magistrala pull request #1727
Opened 2023-02-18 16:12 UTC by AryanGodara

### What does this do?
Updates test files, for better test reports, and overall making test functions more uniform.
### Which issue(s) does this PR fix/relate to?
Resolves #1720

2023-02-24 08:43 UTC, rodneyosodo requested changes
Should we move to `assert.Nil` or stick to `require.Nil` ?

2023-02-24 10:20 UTC, rodneyosodo requested changes
@AryanGodara move from `require.Nil` to `assert.Nil` where necessary. I am still seeing it under boostrap tests among others

2023-03-15 15:42 UTC, dborovcanin submitted a review, later dismissed

2023-03-20 10:46 UTC, rodneyosodo requested changes
Feel free to ignore comments on `auth` services. As it will change later on. My suggestion is if a variable is used downstream, for instance when we are testing `RetrieveAll` we need to used `require` when creating entities the later on when testing `RetrieveAll` we use `assert`

2023-03-20 10:46 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
- L132, L135, L138 should be require since we are using them downstream
- same to L201

2023-03-20 10:46 UTC, rodneyosodo commented on auth/jwt/token_test.go
> +	assert.Nil(t, err, fmt.Sprintf("issuing key expected to succeed: %s", err))
This should be revert to require as the token variable is used downstream

2023-03-20 10:46 UTC, rodneyosodo commented on auth/jwt/token_test.go
> +	assert.Nil(t, err, fmt.Sprintf("issuing user key expected to succeed: %s", err))
This should be revert to require as the token variable is used downstream

2023-03-20 10:46 UTC, rodneyosodo commented on auth/jwt/token_test.go
> +	assert.Nil(t, err, fmt.Sprintf("issuing expired key expected to succeed: %s", err))
This should be revert to require as the token variable is used downstream

2023-03-20 10:46 UTC, rodneyosodo commented on auth/postgres/groups_test.go
> +	assert.Nil(t, err, fmt.Sprintf("got unexpected error: %s", err))
This should be reverted to `require`. As we want the groupID.

2023-03-20 10:46 UTC, rodneyosodo commented on auth/postgres/groups_test.go
>  	usrID, err := idProvider.ID()
Use `generateGroupID`

2023-03-20 10:46 UTC, rodneyosodo commented on auth/postgres/groups_test.go
>  	wrongID, err := ulidProvider.ID()
Use `generateGroupID`

2023-03-20 10:46 UTC, rodneyosodo commented on auth/postgres/groups_test.go
>  	uid, err := idProvider.ID()
Use `generateGroupID`

2023-03-20 10:46 UTC, rodneyosodo commented on auth/postgres/groups_test.go
>  	require.Nil(t, err, fmt.Sprintf("group id unexpected error: %s", err))
Remove one of them

2023-03-20 10:46 UTC, rodneyosodo commented on bootstrap/api/endpoint_test.go
> +	assert.Nil(t, err, fmt.Sprintf("Saving config expected to succeed: %s.\n", err))
revert back to `require` as saved it used downstream

2023-03-20 10:46 UTC, rodneyosodo commented on bootstrap/postgres/configs_test.go
> +	assert.Nil(t, err, fmt.Sprintf("Got unexpected error: %s.\n", err))
revert as it is used downstream

2023-03-20 10:46 UTC, rodneyosodo commented on bootstrap/postgres/configs_test.go
> +	assert.Nil(t, err, fmt.Sprintf("Saving config expected to succeed: %s.\n", err))
revert as it is used downstream

2023-03-20 10:46 UTC, rodneyosodo commented on bootstrap/postgres/configs_test.go
> +	assert.Nil(t, err, fmt.Sprintf("Got unexpected error: %s.\n", err))
revert as it is used downstream

2023-03-20 10:46 UTC, rodneyosodo commented on bootstrap/postgres/configs_test.go
> +		assert.Nil(t, err, fmt.Sprintf("Got unexpected error: %s.\n", err))
revert as it is used downstream

2023-03-20 10:46 UTC, rodneyosodo commented on bootstrap/postgres/configs_test.go
> +		assert.Nil(t, err, fmt.Sprintf("Saving config expected to succeed: %s.\n", err))
revert as it is used downstream

2023-03-29 11:55 UTC, dborovcanin approved these changes, later dismissed

2023-04-06 11:32 UTC, dborovcanin approved these changes

2023-04-12 15:29 UTC, drasko approved these changes
LGTM

2023-04-12 15:30 UTC, merged