NOISSUE - Fix Provision CLI (Clients)
absmach/magistrala pull request #1731
Opened 2023-03-01 08:27 UTC by rodneyosodo

### What does this do?
Fix provision command in CLI with respect to clients

### Which issue(s) does this PR fix/relate to?
N/A

### List any changes that modify/break current functionality
It creates things and channels with enabled status

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
N/A

2023-03-16 23:19 UTC, SammyOina requested changes

2023-03-16 23:19 UTC, SammyOina commented on api/openapi/users.yml
>  paths:
good practice to set operation IDs

2023-03-16 23:19 UTC, SammyOina commented on api/openapi/users.yml
issue token request is wrong

2023-03-16 23:19 UTC, SammyOina commented on cmd/smpp-notifier/main.go
> +func newService(db *sqlx.DB, tracer trace.Tracer, auth policies.AuthServiceClient, c config, sc mfsmpp.Config, logger mflog.Logger) notifiers.Service {
pass s, sc and ec by pointer

2023-03-16 23:19 UTC, SammyOina commented on cmd/smtp-notifier/main.go
> +func newService(db *sqlx.DB, tracer trace.Tracer, auth policies.AuthServiceClient, c config, ec email.Config, logger mflog.Logger) notifiers.Service {
pass c and ec by pointer

2023-03-16 23:19 UTC, SammyOina commented on cmd/users/main.go
>  func newService(db *sqlx.DB, tracer trace.Tracer, c config, ec email.Config, logger mflog.Logger) (clients.Service, groups.GroupService, policies.PolicyService) {
pass c and ec by pointer

2023-03-16 23:19 UTC, SammyOina commented on consumers/notifiers/api/transport.go
> +func MakeHandler(svc notifiers.Service, logger logger.Logger) http.Handler {
import shadow for logger consider renaming

2023-03-16 23:19 UTC, SammyOina commented on consumers/notifiers/api/endpoint_test.go
>  	logger := logger.NewMock()
import shadow

2023-03-16 23:19 UTC, SammyOina commented on http/api/transport.go
> +func MakeHandler(svc adapter.Service, logger logger.Logger) http.Handler {
import shadow

2023-03-16 23:19 UTC, SammyOina commented on http/api/endpoint_test.go
>  	logger := logger.NewMock()
import shadow

2023-03-16 23:19 UTC, SammyOina commented on pkg/sdk/go/policies.go
> +func (sdk mfSDK) AddPolicy(p Policy, token string) errors.SDKError {
pass sdk and policy as pointers

2023-03-16 23:19 UTC, SammyOina commented on pkg/sdk/go/policies.go
> +func (sdk mfSDK) UpdatePolicy(p Policy, token string) errors.SDKError {
pass sdk and policy as pointers

2023-03-16 23:19 UTC, SammyOina commented on pkg/sdk/go/groups_test.go
> +	gmocks "github.com/mainflux/mainflux/users/groups/mocks"
repeated import

2023-03-16 23:19 UTC, SammyOina commented on pkg/sdk/go/groups_test.go
> +	logger := logger.NewMock()
import shadow

2023-03-16 23:19 UTC, SammyOina commented on pkg/sdk/go/message_test.go
>  	logger := logger.NewMock()
import shadow

2023-03-16 23:19 UTC, SammyOina commented on pkg/sdk/go/setup_test.go
>  func convertClientPage(p sdk.PageMetadata) clients.Page {
pass p as pointer

2023-03-16 23:19 UTC, SammyOina commented on pkg/sdk/go/setup_test.go
>  func convertGroup(g sdk.Group) groups.Group {
pass g as pointer

2023-03-16 23:19 UTC, SammyOina commented on pkg/sdk/go/setup_test.go
>  func convertClient(c sdk.User) clients.Client {
pass c as pointer

2023-03-16 23:19 UTC, SammyOina commented on things/policies/service.go
>  func (svc service) AuthorizeByKey(ctx context.Context, entityType string, p Policy) (string, error) {
pass svc and p as pointers

2023-03-16 23:19 UTC, SammyOina commented on things/policies/service.go
> +func (svc service) hasThing(ctx context.Context, p Policy) (string, error) {
pass p ad svc as pointers

2023-03-16 23:19 UTC, SammyOina commented on twins/api/http/transport.go
>  		kithttp.ServerErrorEncoder(apiutil.LoggingErrorEncoder(logger, encodeError)),
import shadow on logger

2023-03-16 23:19 UTC, SammyOina commented on twins/api/http/endpoint_twins_test.go
>  	logger := logger.NewMock()
import shadow

2023-03-16 23:19 UTC, SammyOina commented on twins/tracing/states.go
>  func (trm stateRepositoryMiddleware) Count(ctx context.Context, tw twins.Twin) (int64, error) {
pass tw as pointer

2023-03-16 23:19 UTC, SammyOina commented on twins/tracing/twins.go
>  func (trm twinRepositoryMiddleware) Save(ctx context.Context, tw twins.Twin) (string, error) {
pass tw as pointer

2023-03-16 23:19 UTC, SammyOina commented on twins/tracing/twins.go
>  func (trm twinRepositoryMiddleware) Update(ctx context.Context, tw twins.Twin) error {
pass tw as pointer

2023-03-16 23:19 UTC, SammyOina commented on twins/tracing/twins.go
>  func (tcm twinCacheMiddleware) Save(ctx context.Context, twin twins.Twin) error {
pass tw as pointer

2023-03-16 23:19 UTC, SammyOina commented on twins/tracing/twins.go
>  func (tcm twinCacheMiddleware) Update(ctx context.Context, twin twins.Twin) error {
pass twin as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/api/logging.go
>  func (lm *loggingMiddleware) RegisterClient(ctx context.Context, token string, client clients.Client) (c clients.Client, err error) {
pass client as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/api/logging.go
>  func (lm *loggingMiddleware) ListClients(ctx context.Context, token string, pm clients.Page) (cp clients.ClientsPage, err error) {
pass pm as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/api/logging.go
>  func (lm *loggingMiddleware) UpdateClient(ctx context.Context, token string, client clients.Client) (c clients.Client, err error) {
pass client as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/api/logging.go
>  func (lm *loggingMiddleware) UpdateClientTags(ctx context.Context, token string, client clients.Client) (c clients.Client, err error) {
pass client as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/api/logging.go
>  func (lm *loggingMiddleware) UpdateClientOwner(ctx context.Context, token string, client clients.Client) (c clients.Client, err error) {
pass client as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/api/logging.go
>  func (lm *loggingMiddleware) ListMembers(ctx context.Context, token, groupID string, cp clients.Page) (mp clients.MembersPage, err error) {
pass cp as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/api/logging.go
>  func (lm *loggingMiddleware) EnableClient(ctx context.Context, token string, id string) (c clients.Client, err error) {
```suggestion
func (lm *loggingMiddleware) EnableClient(ctx context.Context, token, id string) (c clients.Client, err error) {
```

2023-03-16 23:19 UTC, SammyOina commented on users/clients/api/logging.go
>  func (lm *loggingMiddleware) DisableClient(ctx context.Context, token string, id string) (c clients.Client, err error) {
```suggestion
func (lm *loggingMiddleware) DisableClient(ctx context.Context, token, id string) (c clients.Client, err error) {
```

2023-03-16 23:19 UTC, SammyOina commented on users/clients/postgres/clients.go
>  func (repo clientRepo) UpdateTags(ctx context.Context, client clients.Client) (clients.Client, error) {
pass client as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/postgres/clients.go
>  func (repo clientRepo) UpdateIdentity(ctx context.Context, client clients.Client) (clients.Client, error) {
pass client as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/postgres/clients.go
>  func (repo clientRepo) UpdateSecret(ctx context.Context, client clients.Client) (clients.Client, error) {
pass client as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/postgres/clients.go
>  func (repo clientRepo) UpdateOwner(ctx context.Context, client clients.Client) (clients.Client, error) {
pass client as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/postgres/clients.go
> +func (repo clientRepo) update(ctx context.Context, client clients.Client, query string) (clients.Client, error) {
pass client as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/service.go
>  func (svc service) ViewProfile(ctx context.Context, token string) (Client, error) {
pass svc as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/service.go
>  func (svc service) ListClients(ctx context.Context, token string, pm Page) (ClientsPage, error) {
pass svc and pm by pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/service.go
>  func (svc service) ResetSecret(ctx context.Context, resetToken, secret string) error {
pass svc as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/service.go
>  func (svc service) UpdateClientSecret(ctx context.Context, token, oldSecret, newSecret string) (Client, error) {
pass svc as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/service.go
>  func (svc service) ListMembers(ctx context.Context, token, groupID string, pm Page) (MembersPage, error) {
pass svc  by pointer

2023-03-16 23:19 UTC, SammyOina commented on users/clients/service.go
>  func (svc service) ListMembers(ctx context.Context, token, groupID string, pm Page) (MembersPage, error) {
pm as well

2023-03-16 23:19 UTC, SammyOina commented on users/clients/service.go
> +func (svc service) Identify(ctx context.Context, tkn string) (string, error) {
pass svc by pointer

2023-03-16 23:19 UTC, SammyOina commented on users/groups/api/logging.go
> +func (lm *loggingMiddleware) CreateGroup(ctx context.Context, token string, group groups.Group) (g groups.Group, err error) {
pass groupp as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/groups/api/logging.go
> +func (lm *loggingMiddleware) UpdateGroup(ctx context.Context, token string, group groups.Group) (g groups.Group, err error) {
pass group as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/groups/api/logging.go
>  func (lm *loggingMiddleware) ListGroups(ctx context.Context, token string, gp groups.GroupsPage) (cg groups.GroupsPage, err error) {
pass gp as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/groups/api/logging.go
>  func (lm *loggingMiddleware) EnableGroup(ctx context.Context, token string, id string) (g groups.Group, err error) {
```suggestion
func (lm *loggingMiddleware) EnableGroup(ctx context.Context, token, id string) (g groups.Group, err error) {
```

2023-03-16 23:19 UTC, SammyOina commented on users/groups/api/logging.go
>  func (lm *loggingMiddleware) DisableGroup(ctx context.Context, token string, id string) (g groups.Group, err error) {
```suggestion
func (lm *loggingMiddleware) DisableGroup(ctx context.Context, token, id string) (g groups.Group, err error) {
```

2023-03-16 23:19 UTC, SammyOina commented on users/groups/api/requests.go
>  func (req createGroupReq) validate() error {
pass req as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/groups/api/requests.go
>  func (req listGroupsReq) validate() error {
pass req as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/groups/tracing/tracing.go
>  func (tm *tracingMiddleware) CreateGroup(ctx context.Context, token string, g groups.Group) (groups.Group, error) {
pass g as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/groups/tracing/tracing.go
> +func (tm *tracingMiddleware) ListMemberships(ctx context.Context, token, clientID string, gm groups.GroupsPage) (groups.MembershipsPage, error) {
pass gm as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/groups/tracing/tracing.go
>  func (tm *tracingMiddleware) UpdateGroup(ctx context.Context, token string, g groups.Group) (groups.Group, error) {
pass g as pointer

2023-03-16 23:19 UTC, SammyOina commented on users/policies/service.go
>  func (svc service) ListPolicy(ctx context.Context, token string, pm Page) (PolicyPage, error) {
pass pm as pointer

2023-03-20 11:50 UTC, rodneyosodo commented on api/openapi/users.yml
Will be solved by https://github.com/mainflux/mainflux/pull/1741

2023-03-21 12:56 UTC, dborovcanin requested changes
@rodneyosodo Please resolve conflicts so we can review this one.

2023-03-21 13:12 UTC, osodor commented on api/openapi/users.yml
>  paths:
They are optional - https://swagger.io/docs/specification/paths-and-operations/

2023-03-21 13:59 UTC, dborovcanin approved these changes

2023-03-21 13:59 UTC, merged