NOISSUE - Move From Opentracing To Opentelemetry
absmach/magistrala pull request #1732
Opened 2023-03-01 08:35 UTC by rodneyosodo

### What does this do?
Moves tracing from opentracing to opentelemetry

### Which issue(s) does this PR fix/relate to?
N/A

### List any changes that modify/break current functionality
Migrating from OpenTracing
 
### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
N/A

2023-03-16 20:26 UTC, SammyOina requested changes

2023-03-16 20:26 UTC, SammyOina commented on things/groups/service.go
> -	if err := svc.authorize(ctx, token, thingsObjectKey, createKey); err != nil {
createKey is no longer used

2023-03-16 20:26 UTC, SammyOina commented on cmd/smpp-notifier/main.go
> +func newService(db *sqlx.DB, tracer trace.Tracer, auth policies.AuthServiceClient, c config, sc mfsmpp.Config, logger mflog.Logger) notifiers.Service {
consider passing c config and sc as pointers

2023-03-16 20:26 UTC, SammyOina commented on cmd/smtp-notifier/main.go
> +	svc := newService(db, tracer, auth, cfg, ec, logger)
consider passing ec as a pointer

2023-03-16 20:26 UTC, SammyOina commented on cmd/users/main.go
>  func newService(db *sqlx.DB, tracer trace.Tracer, c config, ec email.Config, logger mflog.Logger) (clients.Service, groups.GroupService, policies.PolicyService) {
consider passing c and ec as pointers

2023-03-16 20:26 UTC, SammyOina commented on consumers/notifiers/api/transport.go
> +func MakeHandler(svc notifiers.Service, logger logger.Logger) http.Handler {
import shadow on var logger, consider renaming

2023-03-16 20:26 UTC, SammyOina commented on http/api/transport.go
> +func MakeHandler(svc adapter.Service, logger logger.Logger) http.Handler {
import shadow on logger consider renaming

2023-03-16 20:26 UTC, SammyOina commented on http/api/endpoint_test.go
>  	logger := logger.NewMock()
import shadow consider renaming

2023-03-16 20:26 UTC, SammyOina commented on internal/clients/grpc/connect.go
>  	gogrpc "google.golang.org/grpc"
package imported twice

2023-03-16 20:26 UTC, SammyOina commented on things/policies/service.go
>  func (svc service) AuthorizeByKey(ctx context.Context, entityType string, p Policy) (string, error) {
pass svc as a pointer

2023-03-16 20:26 UTC, SammyOina commented on things/policies/service.go
>  func (svc service) AuthorizeByKey(ctx context.Context, entityType string, p Policy) (string, error) {
same for p

2023-03-16 20:26 UTC, SammyOina commented on things/policies/service.go
> +func (svc service) hasThing(ctx context.Context, p Policy) (string, error) {
pass svc and p as pointers

2023-03-16 20:26 UTC, SammyOina commented on twins/tracing/states.go
>  func (trm stateRepositoryMiddleware) Count(ctx context.Context, tw twins.Twin) (int64, error) {
pass tw as pointer

2023-03-16 20:26 UTC, SammyOina commented on twins/tracing/twins.go
>  func (trm twinRepositoryMiddleware) Save(ctx context.Context, tw twins.Twin) (string, error) {
pass tw as pointer

2023-03-16 20:26 UTC, SammyOina commented on twins/tracing/twins.go
>  func (trm twinRepositoryMiddleware) Save(ctx context.Context, tw twins.Twin) (string, error) {
pass tw as pointer

2023-03-16 20:26 UTC, SammyOina commented on twins/tracing/twins.go
>  func (tcm twinCacheMiddleware) Save(ctx context.Context, twin twins.Twin) error {
pass twin as a pointer

2023-03-16 20:26 UTC, SammyOina commented on twins/tracing/twins.go
>  func (tcm twinCacheMiddleware) Update(ctx context.Context, twin twins.Twin) error {
pass twin as a pointer

2023-03-20 08:25 UTC, rodneyosodo commented on things/groups/service.go
> -	if err := svc.authorize(ctx, token, thingsObjectKey, createKey); err != nil {
Fixed by https://github.com/mainflux/mainflux/pull/1735/files#diff-3dff6094885435c95da255d368cd9db5d2f8a1c188f633cc09434b330f46964a

2023-03-20 08:38 UTC, rodneyosodo commented on cmd/smpp-notifier/main.go
> +func newService(db *sqlx.DB, tracer trace.Tracer, auth policies.AuthServiceClient, c config, sc mfsmpp.Config, logger mflog.Logger) notifiers.Service {
They were not passed as pointers initially. I understand there might be some benefit of using pointer and not using pointers depending on the usecase. @dborovcanin is there any reason pointers were not used before?

2023-03-20 09:21 UTC, rodneyosodo commented on internal/clients/grpc/connect.go
>  	gogrpc "google.golang.org/grpc"
fixed

2023-03-20 11:28 UTC, dborovcanin commented on cmd/smpp-notifier/main.go
> +func newService(db *sqlx.DB, tracer trace.Tracer, auth policies.AuthServiceClient, c config, sc mfsmpp.Config, logger mflog.Logger) notifiers.Service {
We should avoid using pointers unless necessary for optimization or by design. There is no need to do it here.

2023-03-20 11:39 UTC, dborovcanin commented on cmd/users/main.go
>  func newService(db *sqlx.DB, tracer trace.Tracer, c config, ec email.Config, logger mflog.Logger) (clients.Service, groups.GroupService, policies.PolicyService) {
Same here. Passing config as a pointer can be dangerous because underlying values can be changed in unpredictable ways.

2023-03-20 11:40 UTC, dborovcanin commented on consumers/notifiers/api/transport.go
> +func MakeHandler(svc notifiers.Service, logger logger.Logger) http.Handler {
While it's not a point of this PR, this does make sense.

2023-03-20 11:44 UTC, rodneyosodo commented on http/api/endpoint_test.go
>  	logger := logger.NewMock()
We aren't using it anywhere else

2023-03-20 11:49 UTC, rodneyosodo commented on consumers/notifiers/api/transport.go
> +func MakeHandler(svc notifiers.Service, logger logger.Logger) http.Handler {
We aren't using it anywhere else

2023-03-20 11:49 UTC, SammyOina commented on cmd/smpp-notifier/main.go
> +func newService(db *sqlx.DB, tracer trace.Tracer, auth policies.AuthServiceClient, c config, sc mfsmpp.Config, logger mflog.Logger) notifiers.Service {
It's a suggestion for optimization, but it's not really what the PR is concerned about

2023-03-20 11:49 UTC, rodneyosodo commented on http/api/transport.go
> +func MakeHandler(svc adapter.Service, logger logger.Logger) http.Handler {
Removed as it isn't being used

2023-03-20 12:16 UTC, dborovcanin requested changes

2023-03-20 12:16 UTC, dborovcanin commented on consumers/notifiers/api/transport.go
> +func MakeHandler(svc notifiers.Service, logger logger.Logger) http.Handler {
Please open a ticket for that and let's do it in a separate PR.

2023-03-20 12:16 UTC, dborovcanin commented on internal/clients/jaeger/tracer.go
> +func NewTracer(svcName, url string) (*tracesdk.TracerProvider, error) {
Let's call it `NewProvider`, also rename the file to `provider.go`.

2023-03-20 12:16 UTC, dborovcanin commented on internal/postgres/tracing.go
> +	ctx, span := d.addSpanTags(ctx, "NamedQueryContext", query)
Way better than it used to be.

2023-03-21 11:03 UTC, dborovcanin commented
@rodneyosodo Please check CI report, there is a dead code.
```
things/groups/service.go:17:2: `createKey` is unused (deadcode)
```

2023-03-21 11:09 UTC, rodneyosodo commented
> @rodneyosodo Please check CI report, there is a dead code.
> 
> ```
> things/groups/service.go:17:2: `createKey` is unused (deadcode)
> ```

Fixed by https://github.com/mainflux/mainflux/pull/1735/files#diff-3dff6094885435c95da255d368cd9db5d2f8a1c188f633cc09434b330f46964a

2023-03-21 11:15 UTC, dborovcanin approved these changes

2023-03-21 11:15 UTC, merged