NOISSUE - Fix Authorization in Things Service
absmach/magistrala pull request #1733
Opened 2023-03-01 08:39 UTC by rodneyosodo

### What does this do?
Fixes duplication of entries both on cache and db
Fixes authorization by key for http-adapter and coap-adapter

### Which issue(s) does this PR fix/relate to?
NOISSUE

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
N/A

2023-03-09 14:03 UTC, SammyOina requested changes

2023-03-09 14:03 UTC, SammyOina commented on cmd/things/main.go
> +	auth, authHandler, err := authClient.Setup(envPrefix, "localhost:6831")
why not a config from env

2023-03-09 14:03 UTC, SammyOina commented on pkg/sdk/go/users_test.go
> +		repoCall := pRepo.On("CheckAdmin", mock.Anything, mock.Anything).Return(nil)
use mock anything of type

2023-03-09 14:05 UTC, SammyOina commented
Fix failing test @rodneyosodo

2023-03-09 14:11 UTC, rodneyosodo commented
> Fix failing test @rodneyosodo

Failing Tests are resolved by https://github.com/mainflux/mainflux/pull/1735

2023-03-09 14:12 UTC, rodneyosodo commented on cmd/things/main.go
> +	auth, authHandler, err := authClient.Setup(envPrefix, "localhost:6831")
This is fixed with https://github.com/mainflux/mainflux/pull/1732

2023-03-14 10:19 UTC, rodneyosodo commented on pkg/sdk/go/users_test.go
> +		repoCall := pRepo.On("CheckAdmin", mock.Anything, mock.Anything).Return(nil)
It accepts native types i.e `int`, `string`

2023-03-16 20:56 UTC, SammyOina approved these changes

2023-03-20 10:34 UTC, dborovcanin approved these changes

2023-03-20 10:34 UTC, merged