MF-512 - Change service Default ports
absmach/magistrala pull request #1737
Opened 2023-03-02 13:22 UTC by SammyOina

### What does this do?
Change the default ports on services, 7XXX for grpc and 9XXX for http. Default adapter ports remain unchanges

### Which issue(s) does this PR fix/relate to?
Resolves #512 

### List any changes that modify/break current functionality
Updated ports:
- auth http 9000
- auth grpc 7000
- provision http 9001
- things http 9002
- things auth http 9003
- things auth grpc 7001
- twins http 9004
- users http 9005
- bootstrap http 9006
- cassandra-reader http 9007
- cassandra-writer http 9008
- influxdb-reader http 9009
- influxdb-writer http 9010
- lora http 9011
- mongodb reader http 9012
- mongodb writer http 9013
- postgres-reader http 9014
- postgrs-writer http 9015
- smpp-notifier http 9016
- smtp-notifier http 9017
- timescale-reader http 9018
- timescale-writer http 9019

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-03-02 18:08 UTC, dborovcanin commented
Let's keep the most "important" (the most frequently used) services first:
Auth, Things, Users, (Adapters), Writers/Readers, Bootstrap, Notifiers, Provision, LoRA, Twins.
Other than that - this looks very good.

2023-03-08 13:21 UTC, rodneyosodo commented
> ### What does this do?
> Change the default ports on services, 7XXX for grpc and 9XXX for http. Default adapter ports remain unchanges
> 
> ### Which issue(s) does this PR fix/relate to?
> Resolves #512
> 
> ### List any changes that modify/break current functionality
> Updated ports:
> 
> service	HTTP port	GRPC port
> Auth	9000	7000
> Things	9001	
> Things - Auth	9002	7001
> Users	9003	
> Cassandra-reader	9004	
> Cassandra-writer	9005	
> influxdb-reader	9006	
> influxdb-writer	9007	
> mongodb reader	9008	
> mongodb writer	9009	
> postgres-reader	9010	
> postgres-writer	9011	
> timescale-reader	9012	
> timescale-writer	9013	
> bootstrap	9014	
> smpp-notifier	9015	
> smtp-notifier	9016	
> provision	9017	
> lora	9018	
> twins	9019	
> ### Have you included tests for your changes?
> No
> 
> ### Did you document any new/modified functionality?
> No
> 
> ### Notes

Certs ports isn't reflected

2023-03-08 13:23 UTC, rodneyosodo reviewed
Remember to update https://github.com/mainflux/docs

2023-03-08 13:30 UTC, rodneyosodo commented
@dborovcanin and @SammyOina What about this approach

- `900X` - Core HTTP Services
- `901X` - Addon Services
- `902X` - Readers
- `903X` - Writers

2023-03-09 14:15 UTC, dborovcanin commented
> @dborovcanin and @SammyOina What about this approach
> 
> * `900X` - Core HTTP Services
> * `901X` - Addon Services
> * `902X` - Readers
> * `903X` - Writers

I like the idea, and, while it's unlikely that we'll have more than 10 services per "scope", it's probably less confusing and more streamlined to pick the next free port.

2023-03-09 14:19 UTC, dborovcanin requested changes
@SammyOina Let's make Users 9000, Things 9001, and make `Auth` the largest 9xxx we have. The reason is #1716 - we'll remove `Auth` as of MF 0.14.

2023-03-10 13:16 UTC, SammyOina commented
> > ### What does this do?
> > Change the default ports on services, 7XXX for grpc and 9XXX for http. Default adapter ports remain unchanges
> > ### Which issue(s) does this PR fix/relate to?
> > Resolves #512
> > ### List any changes that modify/break current functionality
> > Updated ports:
> > service	HTTP port	GRPC port
> > Auth	9000	7000
> > Things	9001
> > Things - Auth	9002	7001
> > Users	9003
> > Cassandra-reader	9004
> > Cassandra-writer	9005
> > influxdb-reader	9006
> > influxdb-writer	9007
> > mongodb reader	9008
> > mongodb writer	9009
> > postgres-reader	9010
> > postgres-writer	9011
> > timescale-reader	9012
> > timescale-writer	9013
> > bootstrap	9014
> > smpp-notifier	9015
> > smtp-notifier	9016
> > provision	9017
> > lora	9018
> > twins	9019
> > ### Have you included tests for your changes?
> > No
> > ### Did you document any new/modified functionality?
> > No
> > ### Notes
> 
> Certs ports isn't reflected

certs port was originally unaltered, I'll change it in a new commit

2023-03-13 15:49 UTC, dborovcanin approved these changes, later dismissed

2023-03-13 16:10 UTC, rodneyosodo requested changes
Change also docs inside the repo for example `MF_THINGS_AUTH_GRPC_URL` 
- certs/README.md
- bootstrap/README.md
- cmd/provision/main.go L38, L39. L40
- coap/README.md
- consumers/notifiers/smtp/README.md
- http/README.md
- metrics/prometheus.yml
- mqtt/README.md
- pkg/transformers/json/README.md
- provision/README.md
- provision/configs/config.toml
- readers/*/README.md
- things/README.md
- things/api/auth/grpc/setup_test.go 
- tools/provision/provision.go - ReaderURL
- twins/README.md - MF_AUTH_GRPC_URL
- ws/README.md - MF_THINGS_AUTH_GRPC_URL

2023-03-14 08:54 UTC, rodneyosodo requested changes
Also change:
- auth/api/grpc/endpoint_test.go L27
- metrics/prometheus.yml L9

2023-03-14 11:39 UTC, dborovcanin approved these changes, later dismissed

2023-03-15 10:48 UTC, rodneyosodo requested changes

2023-03-15 10:48 UTC, rodneyosodo commented on metrics/prometheus.yml
> +    - targets: ['localhost:9002', 'localhost:9000', 'localhost:8080', 'localhost:8185', 'localhost:8186', 'localhost:9017', "localhost:5683", "localhost:8188"]
I have tested with this config and It works. I would suggest

```suggestion
    - targets: ['mainflux-things:9000',  'mainflux-users:9002', 'mainflux-auth:9020', 'mainflux-http:8185', 'mainflux-ws:8186', "mainflux-coap:5683"]
```

2023-03-15 12:44 UTC, rodneyosodo approved these changes

2023-03-15 12:58 UTC, rodneyosodo requested changes
Fix CI

2023-03-15 13:13 UTC, rodneyosodo approved these changes, later dismissed

2023-03-20 09:37 UTC, rodneyosodo approved these changes, later dismissed

2023-03-23 11:36 UTC, dborovcanin requested changes
Let's move the HTTP adapter to the standard port for HTTP protocol (80).

2023-03-23 13:59 UTC, rodneyosodo requested changes

2023-03-23 13:59 UTC, rodneyosodo commented on metrics/prometheus.yml
> +    - targets: ['mainflux-things:9000',  'mainflux-users:9002', 'mainflux-auth:9020', 'mainflux-http:8185', 'mainflux-ws:8186','mainflux-coap:5683']
@SammyOina also change here

2023-03-23 15:14 UTC, dborovcanin requested changes

2023-03-23 15:14 UTC, dborovcanin commented on http/README.md
> +| MF_HTTP_ADAPTER_PORT        | Service HTTP port                                             | 8008                  |
The default is 80.

2023-03-23 16:10 UTC, dborovcanin approved these changes

2023-03-23 20:54 UTC, drasko approved these changes
LGTM

2023-03-23 20:55 UTC, merged