NOISSUE - Remove Logger Import Shadowing
absmach/magistrala pull request #1748
Opened 2023-03-22 10:09 UTC by rodneyosodo

### What does this do?
Fixes import shadowing on logger

### Which issue(s) does this PR fix/relate to?
NOISSUE

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
N/A

2023-03-22 11:27 UTC, dborovcanin requested changes
Please update the branch.

2023-03-22 11:27 UTC, dborovcanin commented on pkg/messaging/brokers/brokers_rabbitmq.go
> +	mflog "github.com/mainflux/mainflux/logger"ogger"ogger"
?

2023-03-22 11:30 UTC, rodneyosodo commented on pkg/messaging/brokers/brokers_rabbitmq.go
> +	mflog "github.com/mainflux/mainflux/logger"ogger"ogger"
Fixed

2023-03-23 11:50 UTC, dborovcanin approved these changes

2023-03-23 11:50 UTC, merged