NOISSUE - add prometheus and grafana for metrics
absmach/magistrala pull request #1753
Opened 2023-03-27 19:54 UTC by SammyOina

### What does this do?
Add Prometheus and grafana for service metrics

### Which issue(s) does this PR fix/relate to?
None

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-03-28 07:04 UTC, rodneyosodo requested changes

2023-03-28 07:04 UTC, rodneyosodo commented on docker/addons/prometheus/docker-compose.yaml
> +    image: grafana/grafana
Add tag

2023-03-28 07:04 UTC, rodneyosodo commented on docker/addons/prometheus/docker-compose.yaml
> +      - ../metrics/prometheus.yml:/etc/prometheus/prometheus.yml
You can move this file here instead of it being at the root level of the repository

2023-03-28 07:04 UTC, rodneyosodo commented on docker/.env
> +#GRAFANA + PROMETHEUS
Add them under addons under L126

2023-03-28 07:04 UTC, rodneyosodo commented on docker/.env
> +MF_GRAFANA_ADMIN_USER=admin
```suggestion
MF_GRAFANA_ADMIN_USER=mainflux
```

2023-03-28 07:04 UTC, rodneyosodo commented on docker/.env
> +MF_GRAFANA_ADMIN_PASSWORD=grafana
```suggestion
MF_GRAFANA_ADMIN_PASSWORD=mainflux
```

2023-03-28 07:04 UTC, rodneyosodo commented on docker/.env
> +MF_GRAFANA_ADMIN_PASSWORD=grafana
add new line

2023-03-28 15:35 UTC, rodneyosodo requested changes

2023-03-28 15:35 UTC, rodneyosodo commented on docker/addons/prometheus/docker-compose.yaml
> +      - ./grafana:/etc/grafana/provisioning/datasources
Add new line

2023-03-28 15:35 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/datasource.yml
> +  editable: true
Add new line

2023-03-28 15:35 UTC, rodneyosodo commented on docker/.env
> +#GRAFANA + PROMETHEUS
```suggestion
### GRAFANA and PROMETHEUS
```

2023-03-28 22:02 UTC, rodneyosodo commented
Is it possible that you can provide some dashboard in `.json` also so that someone can import a basic monitoring dashboard?

2023-03-30 17:18 UTC, SammyOina commented
> Is it possible that you can provide some dashboard in `.json` also so that someone can import a basic monitoring dashboard?

Like creating a sample grafana dashboard? @rodneyosodo

2023-03-30 20:03 UTC, rodneyosodo commented
> > Is it possible that you can provide some dashboard in `.json` also so that someone can import a basic monitoring dashboard?
> 
> Like creating a sample grafana dashboard? @rodneyosodo

Yes

2023-04-11 07:58 UTC, rodneyosodo requested changes
Have a look at why only auth metrics are showing up and not the others in prometheus

2023-04-11 07:58 UTC, rodneyosodo commented on docker/addons/prometheus/docker-compose.yaml
> +
unindent new line

2023-04-11 07:58 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/datasource.yml
> +
unindent new line

2023-04-11 07:58 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/dashboard.yml
> +
unindent new line

2023-04-11 07:58 UTC, rodneyosodo commented on docker/addons/prometheus/docker-compose.yaml
> +        source: ./addons/prometheus/grafana/example-dashboard.json
```suggestion
        source: ./grafana/example-dashboard.json
```

2023-04-11 07:58 UTC, rodneyosodo commented on docker/addons/prometheus/docker-compose.yaml
> +        source: ./addons/prometheus/grafana/dashboard.yml
```suggestion
        source: ./grafana/dashboard.yml
```

2023-04-11 07:58 UTC, rodneyosodo commented on docker/addons/prometheus/docker-compose.yaml
> +        source: ./addons/prometheus/grafana/datasource.yml
```suggestion
        source: ./grafana/datasource.yml
```

2023-04-11 07:58 UTC, rodneyosodo commented on docker/addons/prometheus/docker-compose.yaml
> +        target: /etc/prometheus/prometheus/prometheus.yml
```suggestion
        target: /etc/prometheus/prometheus.yml
```

2023-04-11 07:58 UTC, rodneyosodo commented on docker/addons/prometheus/docker-compose.yaml
> +        source: ./addons/prometheus/metrics/prometheus.yml
```suggestion
        source: ./metrics/prometheus.yml
```

2023-04-11 09:26 UTC, dborovcanin requested changes
Add an empty line to the end of `yml` files.

2023-04-11 10:39 UTC, SammyOina commented
> Have a look at why only auth metrics are showing up and not the others in prometheus

now fixed

2023-04-11 12:19 UTC, SammyOina commented
> Add an empty line to the end of `yml` files.

Done

2023-04-11 13:46 UTC, dborovcanin requested changes
Please use `yml` over `yaml` extension to be in sync with other compose files.
Also, please improve existing Dashboard examples since most dashboards are empty due to the queries used.

2023-04-11 13:46 UTC, dborovcanin commented on docker/addons/prometheus/grafana/example-dashboard.json
> +  "title": "mainfllux",
Fix typo.

2023-04-12 09:33 UTC, rodneyosodo requested changes

2023-04-12 09:33 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
> +{
Add units to Allocated Bytes and also change the threshold

2023-04-12 09:33 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
> +    "list": [
For adapter request also add CoAP, MQTT, WS

2023-04-12 09:33 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
> +        "builtIn": 1,
For the Up time metric change to when it is 0 to display red. You can change the value mapping.
Something like this 
![image](https://user-images.githubusercontent.com/28790446/231414035-fbf6dc14-5a0a-448b-9d97-8801d1c11659.png)

2023-04-12 09:33 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
> +        "enable": true,
Add this for different services

![image](https://user-images.githubusercontent.com/28790446/231414689-74cda5f9-6fbb-4d90-97ec-c5707cda4bcd.png)

2023-04-12 15:45 UTC, rodneyosodo requested changes
Remove threshold from the request count

2023-04-12 15:53 UTC, rodneyosodo requested changes
Change the legends For example
![image](https://user-images.githubusercontent.com/28790446/231512202-1d36a0e3-750c-4f94-8f64-c6d3ece07beb.png)

2023-04-12 15:53 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
> +{
For total request can you implement something like this?

https://play.grafana.org/d/000000029/prometheus-demo-dashboard?orgId=1&refresh=5m

![image](https://user-images.githubusercontent.com/28790446/231512818-1ab55780-539b-432f-87bc-5680208f121f.png)

2023-04-13 08:55 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
> +{
Still not fixed

2023-04-13 08:57 UTC, rodneyosodo requested changes
![image](https://user-images.githubusercontent.com/28790446/231708409-9c094603-19bb-4956-bd5e-1695497b3ca2.png)

Check the output graph for total request. It don't think it is updating correctly

2023-04-13 10:35 UTC, rodneyosodo requested changes

2023-04-13 10:35 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
> +{
For the gauges can we remove limits. Since we don't have a good number for publish requests to an endpoint

2023-04-13 10:35 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
> +{
You can add rows to the panel for each service

![image](https://user-images.githubusercontent.com/28790446/231729469-e212d97c-f2d4-4823-9143-8c85903c0b1f.png)

2023-04-13 13:14 UTC, SammyOina commented on docker/addons/prometheus/grafana/example-dashboard.json
> +{
Each one has just one pannel, so it's really necessary

2023-04-14 08:11 UTC, rodneyosodo requested changes
Change threshold on allocated bytes
![image](https://user-images.githubusercontent.com/28790446/231985011-b44c28fd-3576-4181-938d-688e85a0b17c.png)

2023-04-14 08:14 UTC, SammyOina commented
> Change threshold on allocated bytes
> ![image](https://user-images.githubusercontent.com/28790446/231985011-b44c28fd-3576-4181-938d-688e85a0b17c.png)
> 

Do we know what is critical value? I'd rather just leave it to be static white always

2023-04-14 08:29 UTC, rodneyosodo requested changes
When I stop one container I still get allocated bytes

![image](https://user-images.githubusercontent.com/28790446/231989158-642590fe-b3b8-4b77-acbd-f8ef583b41f4.png)

2023-04-14 08:38 UTC, rodneyosodo commented
> When I stop one container I still get allocated bytes
> 
> ![image](https://user-images.githubusercontent.com/28790446/231989158-642590fe-b3b8-4b77-acbd-f8ef583b41f4.png)

This is resolved

2023-04-14 08:38 UTC, rodneyosodo approved these changes

2023-04-14 10:52 UTC, dborovcanin approved these changes

2023-04-14 10:58 UTC, drasko approved these changes
LGTM

2023-04-14 10:58 UTC, merged