MF-1771 - Add Quantiles to Latency Summary Metrics
absmach/magistrala pull request #1772
Opened 2023-04-19 15:35 UTC by charlie-jangala

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?

Configures Summary metrics created to track latency in Prometheus, so that they report latencies by quantiles (using the 50th, 90th and 99th quantiles)

This is just done by passing the quantiles in under the `Objectives` property when instantiating the Summary metric in Prometheus

### Which issue(s) does this PR fix/relate to?

Resolves #1771 

### List any changes that modify/break current functionality

No changes to current functionality, this change adds new metrics outputs from prometheus but makes no change to existing outputs

### Have you included tests for your changes?

No functional changes included, only metrics reporting changes, which have been tested operationally with a local build

### Did you document any new/modified functionality?

N/A

### Notes

2023-04-20 09:41 UTC, SammyOina submitted a review, later dismissed

2023-04-20 15:11 UTC, rodneyosodo submitted a review, later dismissed

2023-04-20 15:32 UTC, arvindh123 submitted a review, later dismissed

2023-04-21 08:28 UTC, dborovcanin approved these changes

2023-04-27 11:07 UTC, SammyOina approved these changes

2023-04-27 21:14 UTC, drasko requested changes

2023-04-27 21:14 UTC, drasko commented on internal/metrics.go
> +		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
I would prefer leaving comment that explains this magic numbers. Not everybody who reads the code know exactly Prometheus API/terminology without checking the reference - comment will save them some time.

2023-04-27 21:16 UTC, drasko commented
@charlie-jangala thanks for this. Can you please explain, with screenshot from Grafana if possible - what is obtained with those, what and how are those used for - so that we can have it for reference.

2023-04-27 22:25 UTC, drasko approved these changes
LGTM

2023-04-27 22:25 UTC, drasko commented
I'll leave references here:
- https://www.youtube.com/watch?v=3JdQOExKtUY
- https://promlabs.com/blog/2020/09/25/metric-types-in-prometheus-and-promql/#summary-metrics

2023-04-27 22:26 UTC, merged

2023-04-27 22:26 UTC, drasko commented
Merged, thanks @charlie-jangala

2023-04-27 22:47 UTC, charlie-jangala commented
> Merged, thanks @charlie-jangala

Thanks for the engagement all, and for sharing the explanatory resources above @drasko