NOISSUE - Add latency metrics to dashboard
absmach/magistrala pull request #1773
Opened 2023-04-20 10:40 UTC by SammyOina

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Bumps grafana version and add latency metrics to dashboard

### Which issue(s) does this PR fix/relate to?
Relates to #1772 

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-04-20 15:24 UTC, rodneyosodo requested changes

2023-04-20 15:24 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
>        {
Can we add request information to avoid confusion

![image](https://user-images.githubusercontent.com/28790446/233412936-8d98a8fe-4e04-4729-adf1-dbc4b3dae1f0.png)

2023-04-20 15:34 UTC, arvindh123 commented
LGTM

2023-04-20 15:35 UTC, arvindh123 submitted a review, later dismissed

2023-04-22 18:26 UTC, SammyOina commented on docker/addons/prometheus/grafana/example-dashboard.json
>        {
had both instant and range values, instant now not used

2023-04-24 07:04 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
>        {
For instance we have 2 0.5s. They have different meanings which aren't displayed on the legend

2023-04-24 07:46 UTC, rodneyosodo commented on docker/addons/prometheus/grafana/example-dashboard.json
>      "list": [
Let's not aggregate quantiles

2023-04-27 19:53 UTC, drasko approved these changes, later dismissed
LGTM

2023-04-28 07:58 UTC, rodneyosodo commented
You can use a query like this to replace the values with more readable format

```
label_replace(label_replace(label_replace(things_api_request_latency_microseconds, "quantile", "50th percentile", "quantile", "0.5"), "quantile", "90th percentile", "quantile", "0.9"), "quantile", "99th percentile", "quantile", "0.99")
```

Then on the legend you have it like

```
{{method}} - {{quantile}}
```

This will produce something like this

![image](https://user-images.githubusercontent.com/28790446/235089487-db868059-6b68-41a8-9596-c70114f6572b.png)

2023-05-02 11:16 UTC, rodneyosodo commented
Rebase with master so that this changes are reflected https://github.com/mainflux/mainflux/commit/3b84258a0ce034b615be0eb63bee297439ecce40

2023-05-02 11:22 UTC, rodneyosodo requested changes
Add units to the graphs to be something like this 
![image](https://user-images.githubusercontent.com/28790446/235652811-679ba665-39da-43bd-b311-47df74609393.png)

2023-05-03 06:38 UTC, rodneyosodo approved these changes
LGTM

2023-05-17 09:31 UTC, dborovcanin approved these changes

2023-05-24 22:14 UTC, drasko approved these changes
LGTM

2023-05-28 21:08 UTC, drasko approved these changes
LGTM

2023-05-28 21:08 UTC, merged