NOISSUE - Add Updated By Field
absmach/magistrala pull request #1777
Opened 2023-04-21 11:48 UTC by rodneyosodo

### What does this do?
Adds `updated_by` field for clients and groups

### Which issue(s) does this PR fix/relate to?
Resolves https://github.com/ultravioletrs/issues/issues/215

### List any changes that modify/break current functionality
Add `updated_by` field 

### Have you included tests for your changes?
Yes

### Did you document any new/modified functionality?
No

### Notes
N/A

2023-04-27 21:54 UTC, dborovcanin requested changes
Please resolve conflicts so we ca merge.

2023-05-02 10:52 UTC, rodneyosodo commented
CI is fixed by [`6e919ba` (#1781)](https://github.com/mainflux/mainflux/pull/1781/commits/6e919ba872434c328af544e22410687ea0a11490)

2023-05-02 13:24 UTC, dborovcanin requested changes

2023-05-02 13:24 UTC, dborovcanin commented on users/clients/postgres/clients.go
> +	q := `INSERT INTO clients (id, name, tags, owner, identity, secret, metadata, created_at, updated_at, updated_by, status, role)
No need for two cases. Just set the owner to nil if it's empty. Also, it makes sense to leave `updated_by` nullable and default to it on creation, indicating the Client has never been changed.

2023-05-02 13:24 UTC, dborovcanin commented on users/clients/postgres/clients.go
> +	q := `INSERT INTO clients (id, name, tags, owner, identity, secret, metadata, created_at, updated_at, updated_by, status, role)
The same goes for Things clients.

2023-05-08 09:38 UTC, dborovcanin approved these changes

2023-05-08 09:39 UTC, merged