NOISSUE - Trace consume operations
absmach/magistrala pull request #1778
Opened 2023-04-24 11:00 UTC by SammyOina

### What does this do?
Add tracing on consume operations

### Which issue(s) does this PR fix/relate to?
https://github.com/ultravioletrs/issues/issues/210

### List any changes that modify/break current functionality
none

### Have you included tests for your changes?
none

### Did you document any new/modified functionality?
no

### Notes

2023-04-28 08:45 UTC, rodneyosodo requested changes

2023-04-28 08:45 UTC, rodneyosodo commented on consumers/tracing/consumers.go
> +	span, _ := opentracing.StartSpanFromContextWithTracer(ctx, tracer, consumeAsyncOP)
```suggestion
	span, _ := opentracing.StartSpanFromContextWithTracer(ctx, tracer, operation)
```

2023-04-28 08:45 UTC, rodneyosodo commented on consumers/tracing/consumers.go
> +			mesSpan := createMessageSpan(ctx, tm.tracer, mes.Channel, mes.Subtopic, mes.Publisher, consumeBlockingOP)
Can we rename this `operation` to be different from the one at `L50`

2023-05-02 12:42 UTC, rodneyosodo requested changes
On second thought since `consumeBlockingOP` or `consumeAsyncOP` are in the same context with `consumeMessageOP` and when a client publishes a message `Channel` `Subtopic` and `Publisher` will be the same, why not combine the two into something like

```go
func (tm *tracingMiddlewareAsync) ConsumeAsync(ctx context.Context, messages interface{}) {
	var span opentracing.Span
	switch m := messages.(type) {
	case mfjson.Messages:
		firstMsg := m.Data[0]
		span, ctx = createMessageSpan(ctx, tm.tracer, firstMsg.Channel, firstMsg.Subtopic, firstMsg.Publisher, consumeAsyncOP)
		span.SetTag("number_of_messages", len(m.Data))
		defer span.Finish()
	case []senml.Message:
		firstMsg := m[0]
		span, ctx = createMessageSpan(ctx, tm.tracer, firstMsg.Channel, firstMsg.Subtopic, firstMsg.Publisher, consumeAsyncOP)
		span.SetTag("number_of_messages", len(m))
		defer span.Finish()
	}
	tm.consumerAsync.ConsumeAsync(ctx, messages)
}
```

2023-05-02 12:42 UTC, rodneyosodo commented on consumers/tracing/consumers.go
> +	span.SetTag("sub-topic", subTopic)
```suggestion
	if subTopic != "" {
		span.SetTag("sub-topic", subTopic)
	}
```

2023-05-03 07:12 UTC, rodneyosodo requested changes

2023-05-03 07:12 UTC, rodneyosodo commented on consumers/tracing/consumers.go
> +// NewAsync creates a new traced consumers.Blocking service
```suggestion
// NewAsync creates a new traced consumers.AsyncConsumer service
```

2023-05-03 07:12 UTC, rodneyosodo commented on consumers/tracing/consumers.go
> +// ConsumeBlocking  traces consume operations for each message.
reword the comment

2023-05-03 07:12 UTC, rodneyosodo commented on consumers/tracing/consumers.go
> +// ConsumeAsync traces consume operations for each message.
same

2023-05-03 12:44 UTC, rodneyosodo approved these changes, later dismissed
LGTM

2023-05-29 14:25 UTC, dborovcanin requested changes

2023-05-29 14:25 UTC, dborovcanin commented on consumers/tracing/consumers.go
> +		span.SetTag("sub-topic", subTopic)
"subtopic"

2023-05-29 14:41 UTC, drasko submitted a review, later dismissed
LGTM

2023-05-29 21:05 UTC, SammyOina commented
![image](https://github.com/mainflux/mainflux/assets/44265300/2710b125-09be-473e-8478-5eee8836bb03)
![image](https://github.com/mainflux/mainflux/assets/44265300/a56f368c-a89f-4b5d-88fe-25b971ca4718)

2023-05-29 21:05 UTC, SammyOina commented
![image](https://github.com/mainflux/mainflux/assets/44265300/2710b125-09be-473e-8478-5eee8836bb03)
![image](https://github.com/mainflux/mainflux/assets/44265300/a56f368c-a89f-4b5d-88fe-25b971ca4718)

2023-05-29 22:13 UTC, dborovcanin requested changes

2023-05-29 22:13 UTC, dborovcanin commented on consumers/tracing/consumers.go
> +		firstMsg := m.Data[0]
We need to check `m.Data` size before taking the first element.

2023-05-29 22:13 UTC, dborovcanin commented on consumers/tracing/consumers.go
> +		firstMsg := m[0]
Same here.

2023-05-29 22:13 UTC, dborovcanin commented on consumers/tracing/consumers.go
> +		firstMsg := m.Data[0]
And here.

2023-05-29 22:13 UTC, dborovcanin commented on consumers/tracing/consumers.go
> +		firstMsg := m[0]
And here.

2023-05-30 10:26 UTC, dborovcanin requested changes

2023-05-30 10:26 UTC, dborovcanin commented on consumers/tracing/consumers.go
> +	consumerAsync consumers.AsyncConsumer
Rename to `consumer`

2023-05-30 10:26 UTC, dborovcanin commented on consumers/tracing/consumers.go
> +	consumerBlock consumers.BlockingConsumer
Same here.

2023-05-30 10:26 UTC, dborovcanin commented on consumers/tracing/consumers.go
> +		if len(m.Data) >= 1 {
```suggestion
		if len(m.Data) > 0 {
```

2023-05-30 10:26 UTC, dborovcanin commented on consumers/tracing/consumers.go
> +		if len(m.Data) >= 1 {
Do the same for other checks.

2023-05-31 18:18 UTC, drasko approved these changes, later dismissed
LGTM

2023-06-14 12:45 UTC, drasko submitted a review, later dismissed
LGTM

2023-06-14 12:54 UTC, dborovcanin requested changes

2023-06-14 12:54 UTC, dborovcanin commented on consumers/writers/influxdb/consumer.go
> +func (repo *influxRepo) ConsumeBlocking(_ context.Context, message interface{}) error {
Why don't we reuse this context later when calling WriteAPI like:
```go
return repo.writeAPIBlocking.WritePoint(ctx, pts...)
```

2023-06-20 07:46 UTC, rodneyosodo commented on consumers/tracing/consumers.go
> +func createMessageSpan(ctx context.Context, tracer trace.Tracer, topic, subTopic, publisher, operation string, noMessages int) (context.Context, trace.Span) {
```suggestion
func (tm *tracingMiddlewareAsync) createMessageSpan(ctx context.Context, topic, subTopic, publisher, operation string, noMessages int) (context.Context, trace.Span) {
```
Instead of passing the tracer

2023-06-20 08:00 UTC, SammyOina commented on consumers/tracing/consumers.go
> +func createMessageSpan(ctx context.Context, tracer trace.Tracer, topic, subTopic, publisher, operation string, noMessages int) (context.Context, trace.Span) {
leads to code repetition for the blocking consumer interface

2023-06-20 08:24 UTC, rodneyosodo commented on consumers/tracing/consumers.go
> +func createMessageSpan(ctx context.Context, tracer trace.Tracer, topic, subTopic, publisher, operation string, noMessages int) (context.Context, trace.Span) {
I see

2023-06-20 08:25 UTC, rodneyosodo approved these changes
LGTM

2023-07-04 14:45 UTC, arvindh123 commented
I have tested local , 
LGTM

2023-07-13 13:41 UTC, rodneyosodo requested changes

2023-07-13 13:41 UTC, rodneyosodo commented on consumers/tracing/consumers.go
> +func createMessageSpan(ctx context.Context, tracer trace.Tracer, topic, subTopic, publisher, operation string, noMessages int) (context.Context, trace.Span) {
Follow spec by opentelemtry https://github.com/open-telemetry/semantic-conventions/blob/main/docs/messaging/messaging-spans.md . Example implementation of spans can be found here https://github.com/rodneyosodo/mainflux/blob/fd56ec2d8748fbda3014106b200e008af28b937a/pkg/messaging/tracing/publisher.go#L65C1-L87C2

2023-07-14 12:08 UTC, rodneyosodo requested changes

2023-07-14 12:08 UTC, rodneyosodo commented on consumers/tracing/consumers.go
>  	consumeAsyncOP    = "consume_async_op"
This operation name is not a standard operation name supported by open telemetry. I'd suggest something like
```go
consumeAsyncOP    = "receive_async" // This is not specified in the open telemetry spec.
```

2023-07-18 12:21 UTC, arvindh123 reviewed
I have tested all the reader and verified in Jaeger, 
Everthing works fine 
And 
Looks good to me execpt changes mentioned by @rodeny

2023-07-19 12:37 UTC, rodneyosodo commented on consumers/tracing/consumers.go
>  	consumeAsyncOP    = "consume_async_op"
@SammyOina also add the comments as it is not specified operation name

2023-07-19 13:12 UTC, drasko approved these changes
LGTM

2023-07-22 12:38 UTC, merged