NOISSUE - Enable Standalone Mode For Things
absmach/magistrala pull request #1784
Opened 2023-05-04 14:09 UTC by rodneyosodo

### What does this do?
It enables standalone mode for things i.e things can run independently from users if configured so.

### Which issue(s) does this PR fix/relate to?
Noissue

### List any changes that modify/break current functionality
Enables functionality of running things in standalone mode without `auth` service

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
N/A

2023-05-08 09:44 UTC, dborovcanin requested changes
Please resolve conflicts.

2023-05-11 14:27 UTC, SammyOina commented on docker/.env
> +MF_THINGS_STANDALONE_TOKEN=
Do these have defaults

2023-05-11 14:36 UTC, rodneyosodo commented on docker/.env
> +MF_THINGS_STANDALONE_TOKEN=
No. When configuring is when you set them.

2023-05-11 14:57 UTC, dborovcanin requested changes
Update README.md, as well.

2023-05-12 11:11 UTC, dborovcanin approved these changes

2023-05-12 11:11 UTC, merged