NOISSUE - Implement Thing Delete
absmach/magistrala pull request #179
Opened 2023-12-18 13:03 UTC by arvindh123

# What type of PR is this?
Implements thing delete

## What does this do?

## Have you included tests for your changes?

Yes, I have included tests for my changes.

## Did you document any new/modified feature?

No, Not Planned in this PR.

2023-12-19 12:39 UTC, ianmuchyri requested changes

2023-12-19 12:39 UTC, ianmuchyri commented on pkg/sdk/go/sdk.go
> +	// DeleteThing delete given thing id.
```suggestion
	// DeleteThing deletes a thing with the given id.
```

2023-12-19 12:39 UTC, ianmuchyri commented on things/api/http/responses.go
> +type changeStatusClientRes struct {
```suggestion
type changeClientStatusRes struct {
```

2023-12-19 12:39 UTC, ianmuchyri commented on things/postgres/clients.go
> +	// Delete deletes given client id
```suggestion
	// Delete deletes client with given id
```

2023-12-19 12:39 UTC, ianmuchyri commented on things/things.go
> +	// DeleteClient delete given client ID.
```suggestion
	// DeleteClient deletes client with given ID.
```

2023-12-19 14:15 UTC, arvindh123 commented on pkg/sdk/go/sdk.go
> +	// DeleteThing delete given thing id.
done

2023-12-19 14:15 UTC, arvindh123 commented on things/api/http/responses.go
> +type changeStatusClientRes struct {
done

2023-12-19 14:15 UTC, arvindh123 commented on things/postgres/clients.go
> +	// Delete deletes given client id
done

2023-12-19 14:15 UTC, arvindh123 commented on things/things.go
> +	// DeleteClient delete given client ID.
done

2023-12-19 14:28 UTC, ianmuchyri requested changes

2023-12-19 14:28 UTC, ianmuchyri commented on api/openapi/things.yml
> +      summary: Delete thing for given thing id.
```suggestion
      summary: Delete thing for a thing with the given id.
```

2023-12-19 14:28 UTC, ianmuchyri commented on api/openapi/things.yml
> +        Delete thing remove given thing id from repo
```suggestion
        Delete thing removes a thing with the given id from repo
```

2023-12-19 14:28 UTC, ianmuchyri commented on api/openapi/things.yml
> +        and removes all the policies related to thing.
```suggestion
        and removes all the policies related to this thing.
```

2023-12-19 14:33 UTC, rodneyosodo requested changes

2023-12-19 14:33 UTC, rodneyosodo commented on things/api/http/responses.go
> +type deleteClientRes struct{}
Add type check

2023-12-19 14:33 UTC, rodneyosodo commented on things/events/events.go
> +type removeClientEvent struct {
also add type check

2023-12-19 14:33 UTC, rodneyosodo commented on things/service.go
> +	if err := svc.clientCache.Remove(ctx, id); err != nil {
We can invalidate the cache i.e (below authorize check) after auth check on L438

2023-12-19 18:17 UTC, arvindh123 commented on things/service.go
> +	if err := svc.clientCache.Remove(ctx, id); err != nil {
done

2023-12-19 18:17 UTC, arvindh123 commented on things/events/events.go
> +type removeClientEvent struct {
done

2023-12-19 18:17 UTC, arvindh123 commented on things/api/http/responses.go
> +type deleteClientRes struct{}
done

2023-12-19 19:08 UTC, rodneyosodo requested changes

2023-12-19 19:08 UTC, rodneyosodo commented on api/openapi/things.yml
> +          $ref: "#/components/responses/ThingDeleteRes"
No need to reference this since it it only description
```suggestion
          description: Thing deleted.
```

2023-12-20 08:31 UTC, arvindh123 commented on api/openapi/things.yml
> +          $ref: "#/components/responses/ThingDeleteRes"
done

2023-12-20 08:34 UTC, rodneyosodo approved these changes

2023-12-20 16:46 UTC, ianmuchyri approved these changes

2023-12-20 18:55 UTC, dborovcanin approved these changes

2023-12-20 18:55 UTC, merged