MG-12 Improve Error Handling
absmach/magistrala pull request #18
Opened 2023-11-01 09:28 UTC by 1998-felix

### What does this do?
Improve error handling on Magistrala

### Which issue(s) does this PR fix/relate to?
Resolves https://github.com/absmach/magistrala/issues/12

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
None

### Did you document any new/modified functionality?
No

### Notes

2023-11-10 14:27 UTC, dborovcanin requested changes

2023-11-10 14:27 UTC, dborovcanin commented on internal/groups/postgres/groups.go
> +		return mggroups.Group{}, postgres.HandleError(err, repoerror.ErrCreateEntity)
Fix the order in the `postgres.HandleError` - it should be `wrapper`, followed by `error`. Don't forget to update function calls accordingly.

2023-11-14 10:31 UTC, dborovcanin requested changes

2023-11-14 10:31 UTC, dborovcanin commented on pkg/errors/repository/types.go
> +)
Inline `import "github.com/absmach/magistrala/pkg/errors"`.

2023-11-14 10:31 UTC, dborovcanin commented on pkg/errors/service/types.go
> +)
Same, inline.

2023-11-14 10:31 UTC, dborovcanin commented on pkg/errors/types.go
>  package errors
Add correct copyright headers.

2023-11-14 10:31 UTC, dborovcanin commented on pkg/errors/types.go
>  var (
What's the point of these "root" errors, since all the errors should be organized by "layers"?

2023-11-14 10:31 UTC, dborovcanin commented on pkg/clients/postgres/clients.go
>  	"github.com/absmach/magistrala/pkg/errors"
Repo packages should import only repo errors. Svc packages can import svc and repo errors, since there might be need to handle repo errors in svc.

2023-11-14 11:22 UTC, 1998-felix commented on pkg/errors/types.go
>  var (
These are just error definitions organised together so that the errors do not have to be defined in the file.

2023-11-14 11:24 UTC, 1998-felix commented on pkg/clients/postgres/clients.go
>  	"github.com/absmach/magistrala/pkg/errors"
The import is for the functions defined in the error package like Wrap and Contains.

2023-11-17 12:57 UTC, dborovcanin requested changes
Avoid using `apiutil` package in the service layer ([like here](https://github.com/1998-felix/magistrala/blob/6001cbafcc426657ad18f142da8c5fee5595e6c8/users/service.go#L108)).

2023-11-17 14:25 UTC, rodneyosodo requested changes

2023-11-17 14:25 UTC, rodneyosodo commented on internal/postgres/errors.go
>  		case errDuplicate:
As discussed -> postgres errors shouldn't be leaked to the end user hence there should be no error wrapping here

2023-11-20 08:43 UTC, rodneyosodo requested changes
As discussed in the meeting errors coming from external packages shouldn't be wrapped but handled properly. This is because they leak some information to the end user. For example https://github.com/1998-felix/magistrala/blob/d1af8dd3de50e7b35b77e12570d096ef93ba5cf1/auth/jwt/tokenizer.go#L62 this error should be handled. This applies to all repository errors

2023-11-20 08:43 UTC, rodneyosodo commented on auth/jwt/tokenizer.go
> +		return "", errors.Wrap(svcerror.ErrAuthentication, err)
This is a repository hence it should have `repoerror`.

2023-11-20 10:51 UTC, 1998-felix commented on auth/jwt/tokenizer.go
> +		return "", errors.Wrap(svcerror.ErrAuthentication, err)
I went with the inital design of grouping errors by layers, so authentication errors will occur on the service layer

2023-11-20 12:06 UTC, dborovcanin commented on auth/jwt/tokenizer.go
> +		return "", errors.Wrap(svcerror.ErrAuthentication, err)
Tokenizer itself is a layer for itself. The goal was to specify **layer-level** errors and **always** wrap all returned errors with them. However, since Service and Repo errors are way too similar across different services, we moved them to the shared errors package. Returning svc errors here will probably result in duplicate errors in svc, or more complex svc error handling (i.e. inspect if the error is `svcerr.ErrAuhtentication`). Let's export these errors the same way we export `ErrExpiry`.

2023-11-20 16:31 UTC, dborovcanin requested changes
Update error handling in the Auth service, as well.

2023-11-20 16:32 UTC, dborovcanin requested changes
We must not leak RPC errors to the end-users, either.

2023-11-20 16:43 UTC, dborovcanin requested changes

2023-11-20 16:43 UTC, dborovcanin commented on internal/postgres/errors.go
>  		case errDuplicate:
@WashingtonKK Please address this. These should be repo errors. Also, it would be good to use Wrap here, instead of replacing error, so we canhave rich log of what exactly happened (in case of multiple UNIQUE constraints, for example).

2023-11-20 16:43 UTC, dborovcanin commented on users/service.go
>  	}()
The line below `return svc.clients.Save(ctx, cli)`, in case of successfull defer, returns repo error from the svc layer.

2023-11-22 11:12 UTC, dborovcanin requested changes

2023-11-22 12:37 UTC, rodneyosodo requested changes
As discussed, errors from external packages i.e in coap or in certs `vault` should be handled properly rather than wrapping them. This is because they might leak sensitive information to the end user which is undesireable since we don't have control over them. For example for postgres 
```go
func HandleError(err error) error {
	pqErr, ok := err.(*pgconn.PgError)
	if ok {
		switch pqErr.Code {
		case errDuplicate:
			return repoerror.ErrConflict
		case errInvalid, errTruncation:
			return repoerror.ErrMalformedEntity
		case errFK:
			return repoerror.ErrCreateEntity
		}
	}

	// generic error is returned to avoid leaking
	// information about the database
	return fmt.Errorf("database error")
}
```

since if we get this error we return an error related to the same error with some information reducted.

2023-11-22 12:37 UTC, rodneyosodo commented on auth/spicedb/policies.go
> +		return errors.Wrap(repoerror.ErrMalformedEntity, errors.Wrap(errAddPolicies, err))
Errors from the repository or external packages should not leak to the end user. For example here. We should not wrap that error but rather return an error that says what has happened. For example

```suggestion
		return errors.Wrap(repoerror.ErrMalformedEntity, fmt.Errorf("failed to write relaionships"))
```

2023-11-22 14:53 UTC, dborovcanin requested changes

2023-11-22 15:00 UTC, dborovcanin commented
> As discussed, errors from external packages i.e in coap or in certs `vault` should be handled properly rather than wrapping them. This is because they might leak sensitive information to the end user which is undesireable since we don't have control over them. For example for postgres
> 
> ```go
> func HandleError(err error) error {
> 	pqErr, ok := err.(*pgconn.PgError)
> 	if ok {
> 		switch pqErr.Code {
> 		case errDuplicate:
> 			return repoerror.ErrConflict
> 		case errInvalid, errTruncation:
> 			return repoerror.ErrMalformedEntity
> 		case errFK:
> 			return repoerror.ErrCreateEntity
> 		}
> 	}
> 
> 	// generic error is returned to avoid leaking
> 	// information about the database
> 	return fmt.Errorf("database error")
> }
> ```
> 
> since if we get this error we return an error related to the same error with some information reduced.

@rodneyosodo @1998-felix Actually, wrapping in this case is OK. We want to log precise errors so we can debug them. We must not leak sensitive information, however. If we return `repoerr.ErrSomething`, we mask the actual error (say, where exactly the conflict occurred, and which unique constraint is violated). That being said, we must not return the whole trace to the end-user.

2023-11-22 15:44 UTC, dborovcanin requested changes
Let's move `errors.ErrInvalidStatus`, ` errors.ErrAuthentication`, `errors.ErrMalformedEntity`, and similar to svc errors.  Root errors should be removed; not necessarily in this PR, but we should start moving those errors elsewhere.

2023-11-23 07:12 UTC, arvindh123 commented on auth/postgres/domains.go
> +		return auth.Domain{}, errors.Wrap(repoerr.ErrCreateEntity, postgres.HandleError(err))
Does the function `postgres.HandleError(err, errors.ErrCreateEntity)` perform an equivalent task?

2023-11-23 07:13 UTC, arvindh123 commented on auth/postgres/domains.go
> +		return errors.Wrap(repoerr.ErrRemoveEntity, postgres.HandleError(err))
Does the function `postgres.HandleError(err, errors.ErrRemoveEntity)`  perform an equivalent task?

2023-11-23 07:58 UTC, 1998-felix commented on auth/postgres/domains.go
> +		return auth.Domain{}, errors.Wrap(repoerr.ErrCreateEntity, postgres.HandleError(err))
The updated function offers more context to the error

2023-11-23 08:36 UTC, dborovcanin commented on internal/postgres/errors.go
> +	return errors.New("database error")
Just wrap it with a new error like: `return errors.Wrap(ErrDB, err)`.

2023-11-23 08:52 UTC, arvindh123 commented
`api.EncodeError`  https://github.com/1998-felix/magistrala/blob/main/internal/api/common.go#L95-L141 , This function need to updates? ,I guess without this update we will get 500 server error

2023-11-23 10:11 UTC, arvindh123 commented
Error types declared here are still used ? 
https://github.com/1998-felix/magistrala/blob/c544bb15088344580de4b5d9e579a8ec41e1dc13/pkg/errors/types.go#L1-L66
I believe that service, repo, api errors are enough and this error type is no more needed 
Please correct me if I'm wrong 
If anywhere this error type is used, Then please change to appropriate error type ( service, repo, api error type) and remove these error type

2023-11-23 11:00 UTC, dborovcanin commented
> Error types declared here are still used ? https://github.com/1998-felix/magistrala/blob/c544bb15088344580de4b5d9e579a8ec41e1dc13/pkg/errors/types.go#L1-L66 I believe that service, repo, api errors are enough and this error type is no more needed Please correct me if I'm wrong If anywhere this error type is used, Then please change to appropriate error type ( service, repo, api error type) and remove these error type

@arvindh123 You are correct, these errors will be removed eventually. Please take a look here: https://github.com/absmach/magistrala/pull/18#pullrequestreview-1744726656.

2023-11-23 13:05 UTC, arvindh123 reviewed
LGTM

2023-11-23 13:49 UTC, dborovcanin requested changes

2023-11-23 13:49 UTC, dborovcanin commented on internal/api/common.go
> +		errors.Contains(err, repoerr.ErrMalformedEntity),
API layer should not import repo layer errors.

2023-11-23 14:34 UTC, dborovcanin requested changes

2023-11-23 23:51 UTC, dborovcanin approved these changes

2023-11-23 23:52 UTC, merged