MF-1510 - Add Event Sourcing on Users Service
absmach/magistrala pull request #1835
Opened 2023-06-28 14:55 UTC by rodneyosodo

Signed-off-by: rodneyosodo <blackd0t@protonmail.com>

### What does this do?
Emit events from `users` service

### Which issue(s) does this PR fix/relate to?
Resolves #1510

### List any changes that modify/break current functionality
Add event sourcing on `users` services. I have added for both `clients`, `groups` and `policies` sub-services

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
![image](https://github.com/mainflux/mainflux/assets/28790446/89fa2ed9-1382-4ed2-a821-b13a6149b1b8)

2023-07-04 09:53 UTC, SammyOina approved these changes
LGTM

2023-07-12 10:05 UTC, dborovcanin requested changes

2023-07-12 10:05 UTC, dborovcanin commented on cmd/users/main.go
> +	redisucache "github.com/mainflux/mainflux/users/clients/redis"
You can replace it with `ucache`, and do the same for `gcache` for groups and `pcache` for policies. (I will create a ticket to address this in all the `main.go` files)

2023-07-12 10:05 UTC, dborovcanin commented on things/clients/redis/streams.go
> +	thing, err := es.svc.UpdateClient(ctx, token, thing)
No need for this rename, we can keep the `clients` terminology.

2023-07-12 10:05 UTC, dborovcanin commented on things/groups/redis/streams.go
> +func (es eventStore) CreateGroups(ctx context.Context, token string, grps ...mfgroups.Group) ([]mfgroups.Group, error) {
With the same analogy, we could replace `token` -> `tkn`. For the time being, let's not rename (at least in this PR).

2023-07-17 08:35 UTC, dborovcanin requested changes
Please fix User events sourcing, CI is failing.

2023-08-01 14:15 UTC, drasko requested changes

2023-08-01 14:15 UTC, drasko commented on users/policies/redis/events.go
> +func (ae listPoliciesEvent) Encode() (map[string]interface{}, error) {
This should probably be `le`, not `ae`

2023-08-01 14:15 UTC, drasko commented on users/groups/redis/events.go
> +func (lce listGroupEvent) Encode() (map[string]interface{}, error) {
`le` would probably be better, or `lge`, I do not see where `c` comes from.

2023-08-01 15:39 UTC, drasko submitted a review, later dismissed
LGTM

2023-08-02 10:09 UTC, merged