Fix docker compose failing start issue
absmach/magistrala pull request #185
Opened 2018-03-15 14:22 UTC by Maxpeng92

#179

2018-03-15 15:26 UTC, drasko requested changes
Please drop the unused comments

2018-03-15 15:26 UTC, drasko commented on docker/docker-compose.yml
> +    #network_mode: bridge
Drop comments (dead code)

2018-03-15 15:26 UTC, drasko commented on docker/docker-compose.yml
> +    #network_mode: bridge
Same here

2018-03-15 15:26 UTC, drasko commented on docker/docker-compose.yml
> +    #network_mode: bridge
Same here

2018-03-15 16:13 UTC, drasko approved these changes
LGTM

2018-03-16 08:59 UTC, merged

2018-03-16 09:04 UTC, mijicd commented
Merged, since it is a slight improvement in compose, though it does not solve the problem.