NOISSUE - Add Tracing To Certs Service
absmach/magistrala pull request #1850
Opened 2023-07-05 18:15 UTC by rodneyosodo

Signed-off-by: rodneyosodo <blackd0t@protonmail.com>

### What does this do?
Add tracing to the certs service

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
- Added `context` to repository functions on Certs
- Use `NamedQueryContext` instead of `NamedQuery`

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
To be merged after #1849

2023-07-11 09:01 UTC, SammyOina requested changes

2023-07-11 09:01 UTC, SammyOina commented on cmd/certs/main.go
> +		if err := tp.Shutdown(context.Background()); err != nil {
```suggestion
		if err := tp.Shutdown(ctx); err != nil {
```

2023-07-11 11:19 UTC, SammyOina approved these changes

2023-07-12 09:02 UTC, dborovcanin approved these changes

2023-07-12 09:48 UTC, drasko approved these changes
LGTM

2023-07-12 09:48 UTC, merged