NOISSUE-Update invalid secret error handling
absmach/magistrala pull request #1856
Opened 2023-07-11 10:33 UTC by ianmuchyri

### What does this do?
Updates error handling to handle invalid secret
### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)
No issue
### List any changes that modify/break current functionality
None
### Have you included tests for your changes?
No
### Did you document any new/modified functionality?
No
### Notes

2023-07-11 11:10 UTC, rodneyosodo requested changes

2023-07-11 11:10 UTC, rodneyosodo commented on users/clients/service.go
> +		return mfclients.Client{}, errors.ErrSecretError
This should return the `IssueToken` error, then we make IssueToken errors more sensible. 

Something like

```suggestion
		return mfclients.Client{}, err
```

of wrap the error

```suggestion
		return mfclients.Client{}, errors.Wrap(errors.ErrAuthentication, err)
```

2023-07-11 11:10 UTC, rodneyosodo commented on pkg/errors/types.go
> +	ErrSecretError = New("invalid entity secret")
With Gmail as an example

![image](https://github.com/mainflux/mainflux/assets/28790446/a190dae5-e14f-407c-8517-e51536075cbd)

Something like

```suggestion
	ErrWrongSecretError = New("wrong secret")
```

2023-07-11 11:12 UTC, rodneyosodo commented on pkg/errors/types.go
> +	ErrSecretError = New("invalid entity secret")
Also, fix the comment. Add full stop at the end

2023-07-12 09:17 UTC, dborovcanin submitted a review, later dismissed

2023-07-12 11:07 UTC, rodneyosodo requested changes

2023-07-12 11:07 UTC, rodneyosodo commented on pkg/errors/types.go
> +	//ErrSecretError indicates an error with the entity secret.
```suggestion
	// ErrSecretError indicates wrong secret.
```

2023-07-12 11:26 UTC, drasko commented on pkg/errors/types.go
> +	//ErrSecretError indicates an error with the entity secret.
Please fix this

2023-07-12 11:27 UTC, drasko requested changes
Looks good, just a cosmetic fix of comment needed

2023-07-12 11:35 UTC, rodneyosodo commented on pkg/errors/types.go
> +	ErrSecretError = New("wrong secret")
```suggestion
	ErrWrongSecret = New("wrong secret")
```

2023-07-12 12:15 UTC, rodneyosodo requested changes

2023-07-12 12:15 UTC, rodneyosodo commented on pkg/errors/types.go
> +	//ErrWrongSecret indicates a wrong secret was provided.
```suggestion
	// ErrWrongSecret indicates a wrong secret was provided.
```

2023-07-12 12:18 UTC, rodneyosodo approved these changes
LGTM

2023-07-12 21:02 UTC, drasko approved these changes
LGTM

2023-07-12 21:03 UTC, merged