NOISSUE - Enable OwnerID Filtering For Admin
absmach/magistrala pull request #1857
Opened 2023-07-11 10:43 UTC by rodneyosodo

### What does this do?
Enable filtering by `ownerID` when the client logged in is the admin

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
- removes `disconnected` and `sharedby` tags on page
- change the default visibility from `mine` to `""` . This is now done at the service layer
- If the user is an admin they can be able to list clients that are shared with them, that they own, or all clients
### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
N/A

2023-07-11 11:39 UTC, SammyOina requested changes

2023-07-11 11:39 UTC, SammyOina commented on things/clients/service.go
> +	err = svc.checkAdmin(ctx, userID, thingsObjectKey, listRelationKey)
```suggestion
	
```

2023-07-11 11:39 UTC, SammyOina commented on things/clients/service.go
> +	switch {
```suggestion
	switch err = svc.checkAdmin(ctx, userID, thingsObjectKey, listRelationKey); err {
```

2023-07-11 11:39 UTC, SammyOina commented on things/clients/service.go
> +	case err == nil:
```suggestion
	case nil:
```

2023-07-11 11:39 UTC, SammyOina commented on things/clients/service.go
> +	case err != nil:
```suggestion
	default:
```

2023-07-11 12:14 UTC, SammyOina approved these changes
LGTM

2023-07-13 10:24 UTC, dborovcanin requested changes
Please fix DCO.

2023-07-13 13:36 UTC, dborovcanin approved these changes

2023-07-13 13:43 UTC, drasko approved these changes
LGTM

2023-07-13 14:27 UTC, merged