NOISSUE - Check For Policy Action Before Adding Policies
absmach/magistrala pull request #1860
Opened 2023-07-18 09:01 UTC by rodneyosodo

### What does this do?
Check for policy actions before adding policy. If the current users has `g_add` and `c_list` policies on a group, they can only add members to that group with either `g_add` or `c_list` actions. If they try to add a member with `c_update` it should fail unless they are the owner of that group.

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
When adding members to a group, add members with equal policy like yours or subset of your policies.

### Have you included tests for your changes?
Yes

### Did you document any new/modified functionality?
No

### Notes
How to reproduce this while testing is
1. Create 3 different users `a`, `b` and `c`.
2. Create a group with user `a`
3. Add user `b` to the group with only `g_add` actions while using the token of user `a`
4. Try to add user `c` to the group with `c_update` actions while using the token of user `b`

2023-07-18 14:16 UTC, dborovcanin requested changes

2023-07-18 14:16 UTC, dborovcanin commented on things/policies/service.go
> +		pol, err := svc.policies.Retrieve(ctx, page)
Is this fetch necessary and why don't we use the policy from `EvaluateGroupAccess`?

2023-07-18 15:09 UTC, rodneyosodo commented on things/policies/service.go
> +		pol, err := svc.policies.Retrieve(ctx, page)
Because it was returning only `subject`. I have changed it to return `SOA`

2023-07-20 07:21 UTC, SammyOina commented on things/policies/policies.go
> +func contains(actions []string, action string) bool {
you can use golang.org/x/exp/slices with the slices.Contains() method

2023-07-20 07:29 UTC, SammyOina requested changes

2023-07-20 07:29 UTC, SammyOina commented on users/policies/policies.go
> +func contains(actions []string, action string) bool {
same here

2023-07-27 12:36 UTC, SammyOina approved these changes

2023-08-02 13:03 UTC, drasko approved these changes
LGTM

2023-08-02 13:03 UTC, merged