NOISSUE - Add subject to broker subject mainflux message
absmach/magistrala pull request #1867
Opened 2023-07-21 10:40 UTC by SammyOina

Signed-off-by: SammyOina <sammyoina@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-07-24 15:16 UTC, drasko commented
I think it is safe to close this one, as `Subject` can be derived from broker's metadata in the subscription handler.

2023-07-24 19:39 UTC, drasko requested changes

2023-07-24 19:39 UTC, drasko commented on pkg/messaging/nats/pubsub.go
> +			msg.Subtopic = m.Subject // set for messages not published using adapters.
Why is this needed? This is confusing.

If there is no subtopic, it should stay an empty string.

2023-07-25 14:04 UTC, SammyOina commented
I am going to update the example in the docs instead which should have the same result

2023-07-25 14:04 UTC, closed without merging