NOISSUE-Update initialization of instanceID
absmach/magistrala pull request #1873
Opened 2023-08-01 14:02 UTC by ianmuchyri

### What does this do?
removes unnecessary `instanceID` initialization and instead uses `cfg.InstanceID` directly.
### Which issue(s) does this PR fix/relate to?

### List any changes that modify/break current functionality
none
### Have you included tests for your changes?
no
### Did you document any new/modified functionality?
no
### Notes

2023-08-01 14:08 UTC, rodneyosodo requested changes

2023-08-01 14:08 UTC, rodneyosodo commented on cmd/bootstrap/main.go
>  			logger.Error(fmt.Sprintf("Failed to generate instanceID: %s", err))
```suggestion
			logger.Error(fmt.Sprintf("failed to generate instanceID: %s", err))
```

Same as others

2023-08-01 14:32 UTC, rodneyosodo requested changes
Also rename this https://github.com/ianmuchyri/mainflux/blob/e92ca98508dae7eb65da4fa0a09da8b54e06933f/internal/clients/jaeger/provider.go#L41 as depicted by opentelemetry quidelines https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/host.md

2023-08-01 15:13 UTC, rodneyosodo approved these changes
LGTM

2023-08-02 09:31 UTC, drasko approved these changes
LGTM

2023-08-02 09:31 UTC, merged