NOISSUE - Fix Share Thing To Add External To Request
absmach/magistrala pull request #1886
Opened 2023-08-08 18:15 UTC by rodneyosodo

Signed-off-by: rodneyosodo <blackd0t@protonmail.com>

### What does this do?
Enables sharing things on SDK level

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
Add `external` field to policies. This will enables us to share things between users

2023-08-08 20:43 UTC, drasko requested changes

2023-08-08 20:43 UTC, drasko commented on pkg/sdk/go/policies.go
> +	External  bool      `json:"external,omitempty"`
There probably should be a comment explaining what this `External` means, as here it looks like it means something like "external policy"

2023-08-09 07:36 UTC, dborovcanin approved these changes

2023-08-09 12:41 UTC, drasko approved these changes
LGTM

2023-08-09 12:42 UTC, merged