NOISSUE - Change error description
absmach/magistrala pull request #1892
Opened 2023-08-21 06:47 UTC by WashingtonKK

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Doesn't return specific error in case of invalid password. In the event of an invalid password, it returns a general error message so that it does not show whether the user exists or not.

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-08-21 22:05 UTC, dborovcanin requested changes

2023-08-21 22:05 UTC, dborovcanin commented on pkg/errors/types.go
> +	ErrWrongSecret = New("invalid user id or secret")
Rename to `ErrLogin`.

2023-08-21 22:05 UTC, dborovcanin commented on users/hasher/hasher.go
> +	errComparePassword = errors.New("Failed to verify identity or secret")
Make these errors lowercase. Also, this error is specific to the actual secret so it does not make sense to mention identity here.

2023-08-22 13:25 UTC, SammyOina requested changes

2023-08-22 13:25 UTC, SammyOina commented on users/hasher/hasher.go
>  	errHashPassword    = errors.New("Generate hash from password failed")
```suggestion
	errHashPassword    = errors.New("generate hash from password failed")
```

2023-08-23 06:52 UTC, SammyOina approved these changes

2023-08-23 09:11 UTC, dborovcanin approved these changes

2023-08-23 12:48 UTC, merged