NOISSUE - Use Nats JetStream As Internal Message Bus
absmach/magistrala pull request #1893
Opened 2023-08-23 09:04 UTC by rodneyosodo

Signed-off-by: rodneyosodo <blackd0t@protonmail.com>

### What does this do?
Moves the internal message bus implementation to use Nats JetStream.

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
Update `NewPublisher` and `NewPubSub` function parameters.

### Have you included tests for your changes?
I have added integration tests to ensure the new Nats JetStream implementation works correctly.

### Did you document any new/modified functionality?
Not yet

### Notes
This change improves the performance and scalability of our internal message bus by switching to Nats JetStream. The new implementation maintains the same external interface, so there should be minimal disruption.

To be merged after https://github.com/mainflux/mainflux/pull/1885

2023-08-24 07:43 UTC, SammyOina commented on docker/.env
> +MF_POSTGRES_NAME=messages
is this change required?

2023-08-24 13:12 UTC, rodneyosodo commented on docker/.env
> +MF_POSTGRES_NAME=messages
Yes.

2023-08-28 13:04 UTC, drasko commented
@dborovcanin and @arvindh123 to review

2023-09-04 09:34 UTC, arvindh123 reviewed
LGTM

2023-09-14 16:07 UTC, SammyOina approved these changes

2023-10-17 14:05 UTC, dborovcanin requested changes

2023-10-17 14:05 UTC, dborovcanin commented on pkg/messaging/nats/pubsub.go
> +	if err := ps.stream.DeleteConsumer(ctx, id); err != nil {
Unlike plain NATS, JS client is able to hold consumer (subscription) data. Do we need to hold our own list of subscriptions in that case?

2023-10-18 10:02 UTC, rodneyosodo commented on pkg/messaging/nats/pubsub.go
> +	if err := ps.stream.DeleteConsumer(ctx, id); err != nil {
I have made the consumer durable meaning consumers can have subscriptions bound to the topic and resume until the consumer is explicitly deleted. We keep an internal list of subscriptions to track the `ConsumeContext` across consumers so that we can stop and delete the consumer upon unsubscribing

2023-10-18 11:55 UTC, dborovcanin requested changes

2023-10-18 11:55 UTC, dborovcanin commented on pkg/messaging/nats/pubsub.go
> +}
Simplify:
```go
func formatConsumerName(topic, id string) string {
	// A durable name cannot contain whitespace, ., *, >, path separators (forward or backwards slash), and non-printable characters.
	chars := []string{
		" ", "_",
		".", "_",
		"*", "_",
		">", "_",
		"/", "_",
		"\\", "_",
	}
	rplcr := strings.NewReplacer(chars...)
	topic = rplcr.Replace(topic)
	return fmt.Sprintf("%s-%s", topic, id)
}
```

2023-10-18 14:49 UTC, dborovcanin approved these changes

2023-10-18 15:00 UTC, drasko approved these changes
LGTM

2023-10-18 15:00 UTC, merged