Nats es
absmach/magistrala pull request #1907
Opened 2023-09-11 17:12 UTC by rodneyosodo

### What does this do?
This PR introduces Nats Jetstream as the default event sourcing (ES) mechanism.

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
This PR modifies mainflux default event sourcing mechanism to use Nats Jetstream instead of redis. This could potentially break existing code that relies on the previous ES implementation.

### Have you included tests for your changes?
Yes, this PR includes comprehensive tests to ensure that the Nats Jetstream implementation functions correctly and does not introduce regressions.

### Did you document any new/modified functionality?

### Notes
To be merged after #1897 , #1904 , #1893 , #1906 , #1896 
Jetstream documentation - https://docs.nats.io/nats-concepts/jetstream/

2023-09-14 17:01 UTC, SammyOina requested changes

2023-09-14 17:01 UTC, SammyOina commented on pkg/events/nats/publisher.go
> +	// since the events a publisher to a buffer.
```suggestion
	// since the events are published to a buffer.
```

2023-10-24 10:38 UTC, dborovcanin commented on pkg/messaging/pubsub.go
> +type Option func(vals interface{}) error
Please add a little more details to the description explaining why we have this type and how it's meant to be used. Overall, the idea is good and generic and I like it, but it can get a little tricky to understand it from the code and a comment with a better explanation will help. Consider adding an example comment, as well.

2023-10-24 13:17 UTC, SammyOina requested changes

2023-10-24 13:17 UTC, SammyOina commented on pkg/messaging/nats/options.go
> +func WithPrefix(prefix *string) messaging.Option {
With prefix for function names is typically used when extending some receiver value (usually a struct) consider renaming this

2023-10-24 13:42 UTC, dborovcanin requested changes

2023-10-24 13:42 UTC, dborovcanin commented on pkg/messaging/rabbitmq/pubsub.go
> +	chansPrefix  = "channels"
Use `const`.

2023-10-24 13:49 UTC, SammyOina requested changes

2023-10-24 13:49 UTC, SammyOina commented on pkg/messaging/pubsub.go
> +//	broker.NewPublisher(ctx, url, broker.WithPrefix(&eventsPrefix), broker.WithJSStream(js))
update comment

2023-10-24 14:07 UTC, dborovcanin approved these changes

2023-10-24 14:07 UTC, SammyOina approved these changes

2023-10-24 15:01 UTC, drasko approved these changes
LGTM

2023-10-24 15:22 UTC, merged