NOISSUE - description
absmach/magistrala pull request #1909
Opened 2023-09-15 10:43 UTC by 1998-felix

### What does this do?
Add DTLS support to CoAP messaging

### Which issue(s) does this PR fix/relate to?
None

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-09-20 06:33 UTC, SammyOina requested changes

2023-09-20 06:33 UTC, SammyOina commented on internal/server/coap/coap.go
> +var enableDTLS = true
use env var to pass this

2023-09-20 06:33 UTC, SammyOina commented on internal/server/coap/coap.go
> +var enableDTLS = true
use env var to pass this

2023-09-20 06:33 UTC, SammyOina commented on internal/server/coap/coap.go
>  		go func() {
this should be the default case in line 78

2023-10-18 10:44 UTC, SammyOina commented on internal/server/coap/coap.go
> +
```suggestion
```

2023-10-18 10:44 UTC, SammyOina commented on internal/server/coap/coap.go
> +			errCh <- gocoap.ListenAndServeDTLS("udp", s.Address, dtlsConfig, s.handler)
why is ListenTCP removed, we shoulld have all 3 options, no TLS, TLS and DTLS. Modify the config file and this

2023-10-19 15:55 UTC, drasko requested changes
I had two minor remarks. The rest is good. Please address those and remove draft, then we will merge.

2023-10-19 15:55 UTC, drasko commented on docker/nginx/nginx-key.conf
> +# COAP
CoAP

2023-10-19 15:55 UTC, drasko commented on docker/nginx/nginx-x509.conf
> +#COAP
CoAP, and add space after the `#`

2023-10-20 15:17 UTC, drasko requested changes

2023-10-20 15:17 UTC, drasko commented on docker/nginx/nginx-x509.conf
> +#CoAP
Put a space after the `#` comment, I have already demanded this.

2023-10-20 20:40 UTC, dborovcanin requested changes
Having two top-level `stream` directives is not allowed. Move CoAP `server` under the same `stream` as MQTT and always manually test PRs since this won't work due to multiple `stream` directives.

2023-10-20 20:40 UTC, dborovcanin commented on docker/nginx/snippets/coap-upstream.conf
> +}
Add an empty line to the end of the file.

2023-10-20 20:40 UTC, dborovcanin commented on docker/nginx/snippets/coap-upstream.conf
> +        server coap-adapter:${MF_COAP_ADAPTER_HTTP_PORT};
This is just CoAP port, not CoAP HTTP port (HTTP is used only for healthcheck).

2023-10-24 08:28 UTC, arvindh123 commented
LGTM 

In Future it will nice if coap server have CID support 
https://www.linkedin.com/pulse/what-dtls-connection-id-mieszko-mieru%C5%84ski/

Reference code for ID 
https://github.dev/plgd-dev/go-coap/blob/master/examples/dtls/cid/server/main.go

2025-12-01 10:49 UTC, dborovcanin commented
This has been added as a feature to mGate and will be a feature of mProxu, so it is not needed here.

2025-12-01 10:49 UTC, closed without merging