update http messaging to mproxy
absmach/magistrala pull request #1916
Opened 2023-10-05 12:09 UTC by SammyOina

Signed-off-by: SammyOina <sammyoina@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-10-16 11:46 UTC, rodneyosodo requested changes

2023-10-16 11:46 UTC, rodneyosodo commented on cmd/http/main.go
> +	default:
Fix port mapping and URI
- This is the error from HTTP adapter
	```bash
	{"level":"error","message":"failed to start proxy server with error: parse \":81\": missing protocol scheme","ts":"2023-10-16T11:41:52.786991106Z"}
	```

- This is the error when trying to publish
	```bash
	unable to send messages to channels: HTTP failed to send message from thing 77f1cc97-2104-4ab0-be6e-5c88706b4196 to channel 0736b9f8-9293-49ec-bc92-4ff9550e33c3: Status: : Post "http://localhost:8008/channels/0736b9f8-9293-49ec-bc92-4ff9550e33c3/messages": read tcp [::1]:51840->[::1]:8008: read: connection reset by peer
	```

2023-10-16 14:17 UTC, arvindh123 commented
@SammyOina 
I'm getting error in HTTP Adapter
```
2023-10-16 19:40:25 {"level":"info","message":"Successfully connected to things grpc server without TLS","ts":"2023-10-16T14:10:25.97790975Z"}
2023-10-16 19:40:25 {"level":"info","message":"http_adapter service http server listening at http-adapter:8008 without TLS","ts":"2023-10-16T14:10:25.994730439Z"}
2023-10-16 19:40:25 {"level":"info","message":"http_adapter service http server listening at http://localhost:81 without TLS","ts":"2023-10-16T14:10:25.9956256Z"}
2023-10-16 19:40:25 {"level":"info","message":"proxy HTTP shutdown at http://localhost:81","ts":"2023-10-16T14:10:25.995709404Z"}
2023-10-16 19:40:25 {"level":"error","message":"HTTP adapter service terminated: listen tcp: address http://localhost:81: too many colons in address","ts":"2023-10-16T14:10:25.996873955Z"}
2023-10-16 19:40:25 {"level":"error","message":"Error shutting down tracer provider: context canceled","ts":"2023-10-16T14:10:25.997285999Z"}
```

2023-10-16 14:31 UTC, arvindh123 commented
@SammyOina  @dborovcanin  @rodneyosodo 

I have some idea on this PR 

Please give your comments 

On looking the code, I understand, incoming messages are processed by proxy handler and there is no work for http service

So I have two proposal :

1.) Is possible to have tracing, logging, metering around the proxy handler and remove http service ? 

2.) In MQTT service,  mProxy does only authn, authz, or other kind of user defined work in incoming message and forward message to MQTT server. MQTT Server handles publishing, subscribing. 
Likewise can we do authn, authz and other checks in proxy handlers and let the service to do the publishing message in broker.

2023-10-16 14:50 UTC, SammyOina commented
> @SammyOina  @dborovcanin  @rodneyosodo 
> 
> I have some idea on this PR 
> 
> Please give your comments 
> 
> On looking the code, I understand, incoming messages are processed by proxy handler and there is no work for http service
> 
> So I have two proposal :
> 
> 1.) Is possible to have tracing, logging, metering around the proxy handler and remove http service ? 
> 
> 2.) In MQTT service,  mProxy does only authn, authz, or other kind of user defined work in incoming message and forward message to MQTT server. MQTT Server handles publishing, subscribing. 
> Likewise can we do authn, authz and other checks in proxy handlers and let the service to do the publishing message in broker. 
> 


I had moved tracing, logging and metrics to PKG/messaging/handler

2023-10-16 15:16 UTC, arvindh123 commented
> > @SammyOina  @dborovcanin  @rodneyosodo
> > I have some idea on this PR
> > Please give your comments
> > On looking the code, I understand, incoming messages are processed by proxy handler and there is no work for http service
> > So I have two proposal :
> > 1.) Is possible to have tracing, logging, metering around the proxy handler and remove http service ?
> > 2.) In MQTT service,  mProxy does only authn, authz, or other kind of user defined work in incoming message and forward message to MQTT server. MQTT Server handles publishing, subscribing.
> > Likewise can we do authn, authz and other checks in proxy handlers and let the service to do the publishing message in broker.
> 
> I had moved tracing, logging and metrics to PKG/messaging/handler

Yes I saw the code.
Is possible to remove http server , mProxy proxies request to http sever , but the http server doesn't do nothing. 
So instead of forwarding the to http server which doesn't do nothing,  the request can be terminate with response code by the handler itself.

2023-10-17 09:48 UTC, SammyOina commented
> > > @SammyOina  @dborovcanin  @rodneyosodo
> > > I have some idea on this PR
> > > Please give your comments
> > > On looking the code, I understand, incoming messages are processed by proxy handler and there is no work for http service
> > > So I have two proposal :
> > > 1.) Is possible to have tracing, logging, metering around the proxy handler and remove http service ?
> > > 2.) In MQTT service,  mProxy does only authn, authz, or other kind of user defined work in incoming message and forward message to MQTT server. MQTT Server handles publishing, subscribing.
> > > Likewise can we do authn, authz and other checks in proxy handlers and let the service to do the publishing message in broker.
> > 
> > 
> > I had moved tracing, logging and metrics to PKG/messaging/handler
> 
> Yes I saw the code. Is possible to remove http server , mProxy proxies request to http sever , but the http server doesn't do nothing. So instead of forwarding the to http server which doesn't do nothing, the request can be terminate with response code by the handler itself.

I think this is more of a question of what the mproxy library does, as it stands since it is a proxy it should allow to pass requests. Also, The current http server on mainflux doesn't do anything other than respond with HTTP status ok which is pretty much nothing. There is some remaining logic regarding content type because we can't put it on mproxy.

2023-10-17 11:52 UTC, dborovcanin commented
> @SammyOina @dborovcanin @rodneyosodo
> 
> I have some idea on this PR
> 
> Please give your comments
> 
> On looking the code, I understand, incoming messages are processed by proxy handler and there is no work for http service
> 
> So I have two proposal :
> 
> 1.) Is possible to have tracing, logging, metering around the proxy handler and remove http service ?
> 
> 2.) In MQTT service, mProxy does only authn, authz, or other kind of user defined work in incoming message and forward message to MQTT server. MQTT Server handles publishing, subscribing. Likewise can we do authn, authz and other checks in proxy handlers and let the service to do the publishing message in broker.

1) It is, that's what @SammyOina did.
2) It does make sense, but it is not in the nature of the "proxy" concept here. It is the simplest possible HTTP server, though, so I would keep it as is for the time being.

2023-10-22 21:41 UTC, dborovcanin requested changes

2023-10-22 21:41 UTC, dborovcanin commented on cmd/http/main.go
> +}
Use a single function with a param for TLS.

2023-10-23 07:43 UTC, dborovcanin approved these changes

2023-10-23 12:35 UTC, drasko approved these changes
LGTM

2023-10-23 12:35 UTC, merged