NOISSUE - Align Things API Documentation
absmach/magistrala pull request #1926
Opened 2023-10-16 10:05 UTC by rodneyosodo

### What does this do?
- aligns things API documentation with implementation

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
N/A

2023-10-16 11:43 UTC, drasko approved these changes, later dismissed
LGTM

2023-10-17 11:00 UTC, SammyOina approved these changes

2023-10-18 11:31 UTC, dborovcanin requested changes
There are commented tests in `/pkg/sdk/go/tokens_test.go`.

2023-10-18 14:29 UTC, dborovcanin approved these changes

2023-10-18 14:45 UTC, drasko approved these changes
LGTM

2023-10-18 14:45 UTC, merged