MG-2051 - Fix unable to reset user password
absmach/magistrala pull request #2052
Opened 2024-01-10 08:38 UTC by VeddySama

# What type of PR is this?
Fix Bug

## What does this do?
Fixed unable to reset user password

## Which issue(s) does this PR fix/relate to?

- Related Issue #2051
- Fixes #2051

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2024-01-10 09:24 UTC, dborovcanin reviewed
Thanks for the contribution, the changes look good. Can you add tests for this method?

2024-01-11 03:47 UTC, VeddySama commented
> Thanks for the contribution, the changes look good. Can you add tests for this method?

I have completed the tests, please take a look

2024-01-11 04:47 UTC, arvindh123 requested changes

2024-01-11 04:47 UTC, arvindh123 commented on users/service_test.go
> +			secret:     "newSecret",
Please convert secret string values `newSecret`, `secret` to const

2024-01-11 08:30 UTC, VeddySama commented on users/service_test.go
> +			secret:     "newSecret",
Is this correct now?

2024-01-11 11:10 UTC, arvindh123 commented on users/service_test.go
> +			secret:     "newSecret",
Yes

2024-04-03 14:12 UTC, dborovcanin commented
@ianmuchyri Please review. @VeddySama Can you, please, rebase?

2024-04-03 14:14 UTC, ianmuchyri commented
> @ianmuchyri Please review. @VeddySama Can you, please, rebase?

@VeddySama please check lint error and sign off your commits. This is in line with the contribution guidelines.

2024-04-03 15:31 UTC, VeddySama commented
> @ianmuchyri请查阅。@VeddySama你能重新建立基础吗？

Should I do it like I am doing now or should I re-establish a branch?

2024-04-03 15:40 UTC, VeddySama commented
I saw that the latest PR has been modified to submit this issue. You can adopt this PR.
https://github.com/absmach/magistrala/pull/2135

2024-04-03 15:42 UTC, closed without merging

2024-04-04 09:12 UTC, dborovcanin commented
@VeddySama Thanks for the contribution and sorry for the confusion; @ianmuchyri accidentally sent a PR without checking if there is a pending one.