NOISSUE - Update dependencies
absmach/magistrala pull request #2061
Opened 2024-01-21 16:36 UTC by dborovcanin

# What type of PR is this?

This pull request updates dependencies.
## What does this do?

It updates all dependencies except OPC-UA due to backward incompatibility.

## Which issue(s) does this PR fix/relate to?

There is no such issue.

## Have you included tests for your changes?

N/A
## Did you document any new/modified feature?

N/A
### Notes

N/A

2024-01-22 13:03 UTC, rodneyosodo requested changes

2024-01-22 13:03 UTC, rodneyosodo commented on readers/mongodb/setup_test.go
> +		Tag:        "6.0.13",
There is a newer version
```suggestion
		Tag:        "7.0.5",
```

2024-01-22 13:03 UTC, rodneyosodo commented on readers/cassandra/setup_test.go
> +		Tag:        "3.11.16",
Do we support version 5.0?

2024-01-22 13:03 UTC, rodneyosodo commented on docker/docker-compose.yml
> +    image: "postgres:16.1-alpine"
Also update jaeger, redis, nginx, users and invitations db

2024-01-22 14:27 UTC, dborovcanin commented on readers/cassandra/setup_test.go
> +		Tag:        "3.11.16",
At the moment, both 4.x.x and 5.0 are not supported.

2024-01-22 22:41 UTC, rodneyosodo requested changes
The following cases have not been updated
- `users/postgres/setup_test.go` 
- `things/postgres/setup_test.go`
- `invitations/postgres/setup_test.go`
- `internal/groups/postgres/setup_test.go`
- `pkg/clients/postgres/setup_test.go`
- `pkg/messaging/mqtt/setup_test.go`
- `pkg/messaging/nats/setup_test.go` and `pkg/events/nats/setup_test.go`
- `pkg/messaging/rabbitmq/setup_test.go` and `pkg/events/rabbitmq/setup_test.go`
- `pkg/events/redis/setup_test.go` and `bootstrap/events/producer/setup_test.go`
- `auth/postgres/setup_test.go`
- `bootstrap/postgres/setup_test.go`
- `certs/postgres/setup_test.go`
- `consumers/notifiers/postgres/setup_test.go`
- Redis on `docker/addons/lora-adapter/docker-compose.yml`, `docker/addons/opcua-adapter/docker-compose.yml` , `docker/addons/twins/docker-compose.yml` and `docker/docker-compose.yml`
- `docker/addons/prometheus/docker-compose.yml`
- `docker/addons/smpp-notifier/docker-compose.yml`
- `docker/addons/smtp-notifier/docker-compose.yml`
- `docker/addons/vault/docker-compose.yml`
- `docker/es` and `docker/brokers`

2024-01-23 10:34 UTC, rodneyosodo requested changes

2024-01-23 10:34 UTC, rodneyosodo commented on docker/addons/vault/docker-compose.yml
> +    image: vault:1.15.4
```suggestion
    image: hashicorp/vault:1.15.4
```

2024-01-23 11:34 UTC, rodneyosodo approved these changes

2024-01-23 12:09 UTC, merged