MF-174 - Add logger interface and go-kit logger implementation
absmach/magistrala pull request #212
Opened 2018-04-03 08:58 UTC by anovakovic01

Add wrapper logger interface and wrap go-kit logger in it. Add
tests for info, warn, error and log methods.

Signed-off-by: Aleksandar Novakovic <anovakovic01@gmail.com>

2018-04-03 10:02 UTC, drasko submitted a review, later dismissed
LGTM

2018-04-03 11:18 UTC, mijicd requested changes
Besides the explicitly requested changes, make sure that all logging usages are updated to use the new logger.

2018-04-03 11:18 UTC, mijicd commented on log/kitlog/logger.go
> +func (l *logger) SetLevel(lvl log.Level) {
Please remove this.

2018-04-03 11:18 UTC, mijicd commented on log/kitlog/logger.go
> +func (l logger) Info(obj interface{}) {
Logging methods should accept only the string parameter.

2018-04-03 11:18 UTC, mijicd commented on log/kitlog/logger.go
> +func (l logger) Log(lvl log.Level, obj interface{}) {
Please remove this.

2018-04-03 11:18 UTC, mijicd commented on log/level.go
> +	All Level = iota
This won't exist.

2018-04-03 11:18 UTC, mijicd commented on log/level.go
> +func AddLevel(lvl Level, name string) {
Please remove this.

2018-04-03 11:18 UTC, mijicd commented on log/logger.go
> +type Logger interface {
See my remarks given above. Also, rename the package to `logger`.

2018-04-03 18:23 UTC, mijicd requested changes
In case that I missed something, use `warn` for all erroneous cases that does not "break" the service, e.g. failed normalization can happen for non-SenML messages. Use `error` whenever there is a infrastructure/service failure, e.g. database or NATS connection failure.

2018-04-03 21:16 UTC, mijicd requested changes
Getting there.

2018-04-03 21:16 UTC, mijicd commented on logger/logger_test.go
> +		input string
The test is missing the expected output. I would recommend to restructure it in such a way that is easy to acquire the contents and verify it, i.e. provide an implementation of `io.Writer` for test purposes.

2018-04-04 08:14 UTC, mijicd approved these changes

2018-04-04 08:15 UTC, merged