MG-1993-Generate Mocks Per Service
absmach/magistrala pull request #2128
Opened 2024-03-27 13:02 UTC by nyagamunene

# What type of PR is this?
This is a feature because its add the following functionality: generates mocks per service.

## What does this do?
It generates the mocks for the individual services automatically rather than doing it manually.

## Which issue(s) does this PR fix/relate to?

- Resolves #1993 

## Have you included tests for your changes?

No, I have not included tests because its still in progress.

## Did you document any new/modified feature?

No, I have not updated the documentation.

### Notes

2024-03-28 08:13 UTC, WashingtonKK commented
Please sign off your commits, check DCO report [here](https://github.com/absmach/magistrala/pull/2128/checks?check_run_id=23168073503) and fix.

2024-03-28 08:16 UTC, WashingtonKK requested changes
We do not need mocks for the ws and coap services since they are not used. Only replace manually written mocks with generated mocks.
An example is bootstrap service, we have manually written mocks for the service but we need to have them generated instead.

2024-03-28 08:37 UTC, WashingtonKK commented
Also update the mockery version used to use [the latest version](https://github.com/vektra/mockery/releases/tag/v2.42.1)

2024-04-04 07:54 UTC, rodneyosodo requested changes

2024-04-04 07:54 UTC, rodneyosodo commented on bootstrap/configs.go
> +//go:generate mockery --name ConfigRepository --output=./mocks --filename configs.go --quiet --note "Copyright (c) Abstract Machines"
Run 
```bash
make mocks
```

to generate the mocks

2024-04-04 08:05 UTC, nyagamunene commented on bootstrap/configs.go
> +//go:generate mockery --name ConfigRepository --output=./mocks --filename configs.go --quiet --note "Copyright (c) Abstract Machines"
Okay

2024-04-09 09:48 UTC, closed without merging