MG-2069 - Remove relation requirement from entity unassignment
absmach/magistrala pull request #2130
Opened 2024-04-02 07:30 UTC by WashingtonKK

# What type of PR is this?

This is a refactor because it changes the following functionality: Unassign entity.

## What does this do?

Removes the relation requirement from unassigning an entity. When the relation is provided, only the user with that relation is removed, when not provided - all relations are removed.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2069
- Resolves #2069

## Have you included tests for your changes?

Yes, I have included tests for my changes.

## Did you document any new/modified feature?

No

### Notes

Signed-off-by: WashingtonKK <washingtonkigan@gmail.com>

2024-04-03 10:32 UTC, arvindh123 commented on things/api/http/requests.go
>  	}
Please remove Relation file from `unassignUsersReq`

2024-04-03 10:38 UTC, arvindh123 commented on auth/spicedb/policies.go
> +
@WashingtonKK 
`DeletePolicies` is different from `DeletePolicy`
`DeletePolicies` supports filteing of options, But DeletePolicy doesn't support filtering options

2024-04-03 10:50 UTC, arvindh123 commented on auth/service.go
We should not allow editor to remove administrator. 
This check will be bypassed if relation is empty. 
We need to think this approch in different way

2024-04-10 13:44 UTC, dborovcanin requested changes

2024-04-10 13:44 UTC, dborovcanin commented on auth/service.go
> +	} else {
Avoid using `if-else` to make it consistent with the rest of the codebase. Also, try to simplify with something like:
```go
pr := PolicyReq{
		Subject:     token,
		SubjectType: UserType,
		SubjectKind: TokenKind,
		Object:      id,
		ObjectType:  DomainType,
		Permission:  SharePermission,
	}
	if err := svc.Authorize(ctx, pr); err != nil {
		return err
	}

	if relation != "" {
		pr.Permission = SwitchToPermission(relation)
		if err := svc.Authorize(ctx, pr); err != nil {
			return err
		}

		if err := svc.removeDomainPolicies(ctx, id, relation, userIds...); err != nil {
			return errors.Wrap(errRemovePolicies, err)
		}
		return nil
	}
	pr.Permission = AdminPermission
	if err := svc.Authorize(ctx, pr); err != nil {
		// User is not admin.
		var ids []string
		for _, userID := range userIds {
			if err := svc.Authorize(ctx, PolicyReq{
				Subject:     userID,
				SubjectType: UserType,
				SubjectKind: UsersKind,
				Permission:  AdminPermission,
				Object:      id,
				ObjectType:  DomainType,
			}); err != nil {
				// Append all non-admins to ids.
				ids = append(ids, userID)
			}
		}

		// Remove only non-admins.
		if err := svc.removeDomainPolicies(ctx, id, MemberRelation, ids...); err != nil {
			return errors.Wrap(errRemovePolicies, err)
		}

		if err := svc.removeDomainPolicies(ctx, id, ViewerRelation, ids...); err != nil {
			return errors.Wrap(errRemovePolicies, err)
		}

		if err := svc.removeDomainPolicies(ctx, id, EditorRelation, ids...); err != nil {
			return errors.Wrap(errRemovePolicies, err)
		}
	}

	// If user is admin, remove all policies from all users.
	if err := svc.removeDomainPolicies(ctx, id, MemberRelation, userIds...); err != nil {
		return errors.Wrap(errRemovePolicies, err)
	}

	if err := svc.removeDomainPolicies(ctx, id, ViewerRelation, userIds...); err != nil {
		return errors.Wrap(errRemovePolicies, err)
	}

	if err := svc.removeDomainPolicies(ctx, id, EditorRelation, userIds...); err != nil {
		return errors.Wrap(errRemovePolicies, err)
	}

	if err := svc.removeDomainPolicies(ctx, id, AdministratorRelation, userIds...); err != nil {
		return errors.Wrap(errRemovePolicies, err)
	}

	return nil
```

2024-04-11 08:04 UTC, rodneyosodo requested changes

2024-04-11 08:04 UTC, rodneyosodo commented on auth/postgres/domains.go
> +		DELETE FROM
Add tests for this

2024-04-18 09:10 UTC, rodneyosodo requested changes

2024-04-18 09:10 UTC, rodneyosodo commented on auth/postgres/domains.go
> +		WHERE
Try and make this section DRY. You can use this as an example https://github.com/rodneyosodo/magistrala/blob/9f2fa81532db77ce790db3e5a938e7188065f73c/activitylog/postgres/events.go#L46C1-L50C130

2024-04-19 08:31 UTC, rodneyosodo approved these changes, later dismissed
LGTM

2024-04-19 10:43 UTC, dborovcanin requested changes
This starts to be a little cryptic and complex. We must simplify, but let's not do that in this PR.

2024-04-19 10:43 UTC, dborovcanin commented on auth/service.go
> +		}
You can simplify with something like:
```suggestion
for _, rel := range []string{MemberRelation, ViewerRelation, EditorRelation} {
			// Remove only non-admins.
			if err := svc.removeDomainPolicies(ctx, id, rel, ids...); err != nil {
				return errors.Wrap(errRemovePolicies, err)
			}
		}
```

2024-04-19 10:43 UTC, dborovcanin commented on auth/service.go
> +	}
Same here.

2024-04-23 07:38 UTC, rodneyosodo approved these changes, later dismissed

2024-04-23 08:23 UTC, dborovcanin requested changes

2024-04-23 08:23 UTC, dborovcanin commented on auth/service.go
> +		}
You can replace this whole section, since you have the loop in the block below:
```suggestion
	userIds = ids
```

2024-04-23 08:56 UTC, dborovcanin approved these changes

2024-04-23 08:58 UTC, merged

2024-04-23 09:09 UTC, arvindh123 commented on auth/postgres/domains.go
> +			q = fmt.Sprintf("%s AND relation = :relation", q)
@WashingtonKK  There will be only one relation in the Domain. 
So need to  consider relation here

2024-04-23 09:20 UTC, dborovcanin commented on auth/postgres/domains.go
> +			q = fmt.Sprintf("%s AND relation = :relation", q)
@WashingtonKK Please check this one and send a follow-up PR for it.