NOISSUE - Add group tests to users and things service
absmach/magistrala pull request #2133
Opened 2024-04-03 07:39 UTC by 1998-felix

# What type of PR is this?
This is a feature as it adds groups tests to users and things service using the groups service mocks.

## What does this do?
This adds groups tests to users and things services.

## Which issue(s) does this PR fix/relate to?
None.

## Have you included tests for your changes?
No since this is the test file.

## Did you document any new/modified feature?
Yes, documentation in in code comments.

### Notes

2024-04-04 08:06 UTC, rodneyosodo requested changes

2024-04-04 08:06 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +func TestAssignUserGroups(t *testing.T) {
```suggestion
func TestAssignGroupsToChannel(t *testing.T) {
```

2024-04-04 08:06 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +func TestUnassignUserGroups(t *testing.T) {
same

2024-04-04 08:06 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +func TestConnectChannelThing(t *testing.T) {
```suggestion
func TestConnectChannelToThing(t *testing.T) {
```

2024-04-04 08:06 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +func TestDisconnectChannelThing(t *testing.T) {
same

2024-04-04 08:06 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +			status:      http.StatusUnprocessableEntity,
This should be code 400 change validation to return missing id. Same as other cases

2024-04-04 12:21 UTC, rodneyosodo submitted a review, later dismissed
LGTM

2024-04-05 12:16 UTC, dborovcanin requested changes

2024-04-05 12:16 UTC, dborovcanin commented on things/api/http/endpoints_test.go
> +			desc:    "unassign users to group successfully",
unassign users from a group successfully

2024-04-05 12:16 UTC, dborovcanin commented on things/api/http/endpoints_test.go
> +			desc:    "unassign users to group successfully",
Fux other cases, as well.

2024-04-05 12:16 UTC, dborovcanin commented on users/api/endpoint_test.go
> +			desc:    "assign groups to group successfully",
assign group to a parent group successfully

2024-04-05 12:16 UTC, dborovcanin commented on users/api/endpoint_test.go
> +			desc:    "assign groups to group successfully",
Use `assign group to a parent group` instead of `assign group to a group`.

2024-04-05 12:40 UTC, dborovcanin approved these changes

2024-04-05 12:40 UTC, merged