MG-1981 - Fix bug on list groups wth subject returning subject group.
absmach/magistrala pull request #2148
Opened 2024-04-09 12:01 UTC by 1998-felix

# What type of PR is this?
This is a bug fix because it fixes the following issue: #1981 

## What does this do?
This pr fixes the bug  on list group parents and children returning the group that is the subject.

## Which issue(s) does this PR fix/relate to?

- Resolves #1981

## Have you included tests for your changes?
No, I have not included test because the part of the code is already covered by tests.

## Did you document any new/modified feature?
No

### Notes
N/A

2024-04-09 18:32 UTC, dborovcanin requested changes
Can you add some tests for this fix?

2024-04-11 07:46 UTC, rodneyosodo requested changes

2024-04-11 07:46 UTC, rodneyosodo commented on internal/groups/api/endpoints.go
> +func buildGroupsResponse(gp groups.Page, fbid bool) groupPageRes {
```suggestion
func buildGroupsResponse(gp groups.Page, filterByID bool) groupPageRes {
```

2024-04-16 11:51 UTC, dborovcanin approved these changes

2024-04-16 12:30 UTC, merged