MG-2143 - Generate mocks with mockery for Consumer service
absmach/magistrala pull request #2150
Opened 2024-04-09 16:55 UTC by nyagamunene

# What type of PR is this?
This is a feature because its add the following functionality: generates mocks for consumers.

## What does this do?
It generates the mocks for consumers service.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2147 
- Resolves #2147 

## Have you included tests for your changes?
Yes, I have included tests

## Did you document any new/modified feature?
No, I have not updated the documentation.

### Notes

2024-04-11 07:43 UTC, rodneyosodo requested changes

2024-04-11 07:43 UTC, rodneyosodo commented on consumers/notifiers/service_test.go
> +	repo := new(mocks.SubscriptionsRepository)
Fix CI

2024-04-11 11:25 UTC, dborovcanin requested changes

2024-04-11 11:25 UTC, dborovcanin commented on pkg/sdk/go/consumers_test.go
> +func GetSubscriptionsSlice(subs []sdk.Subscription, start, end int) []notifiers.Subscription {
Simplify and rename (and don't export):
```go
func subscriptionsSlice(subs []sdk.Subscription, start, end int) []notifiers.Subscription {
	var res []notifiers.Subscription
	for i := start; i < end; i++ {
		sub := subs[i]
		res = append(res, notifiers.Subscription{
			ID:      sub.ID,
			OwnerID: sub.OwnerID,
			Contact: sub.Contact,
			Topic:   sub.Topic,
		})
	}
	return res
}
```

2024-04-11 13:47 UTC, rodneyosodo requested changes

2024-04-11 13:47 UTC, rodneyosodo commented on consumers/notifiers/service_test.go
> +	repoCall1 := repo.On("Save", mock.Anything, mock.Anything).Return(validID, nil)
No need for `CreateSubscription` before running test cases since we are not persisting that data

2024-04-11 13:47 UTC, rodneyosodo commented on consumers/notifiers/service_test.go
> +		repoCall := repo.On("RetrieveAll", mock.Anything, mock.Anything).Return(notifiers.Page{}, tc.err)
Try and reduce the use of `mock.Anything`

2024-04-16 10:32 UTC, rodneyosodo requested changes

2024-04-16 10:32 UTC, rodneyosodo commented on consumers/notifiers/api/endpoint_test.go
> +	svcCall := svc.On("CreateSubscription", context.Background(), token, sub).Return(sub.ID, nil)
Remove this and replace `id` in with `sub.ID` downstream

2024-04-16 10:32 UTC, rodneyosodo commented on consumers/notifiers/api/endpoint_test.go
> +		svcCall := svc.On("CreateSubscription", context.Background(), token, sub).Return(sub.ID, nil)
same

2024-04-16 10:32 UTC, rodneyosodo commented on consumers/notifiers/service_test.go
>  		id, err := svc.CreateSubscription(context.Background(), token, tmp)
same

2024-04-16 10:32 UTC, rodneyosodo commented on consumers/notifiers/service_test.go
>  	id, err := svc.CreateSubscription(context.Background(), exampleUser1, sub)
same

2024-04-16 14:43 UTC, rodneyosodo requested changes

2024-04-16 14:43 UTC, rodneyosodo commented on pkg/sdk/go/consumers_test.go
>  		repoCall := auth.On("Identify", mock.Anything, &magistrala.IdentityReq{Token: tc.token}).Return(&magistrala.IdentityRes{Id: validID}, nil)
Add unhappy flows i.e Identify fails

2024-04-18 08:57 UTC, rodneyosodo requested changes

2024-04-18 08:57 UTC, rodneyosodo commented on consumers/notifiers/service_test.go
> +		repoCall := auth.On("Identify", context.Background(), &magistrala.IdentityReq{Token: tc.token}).Return(&magistrala.IdentityRes{Id: validID}, nil)
Add unhappy auth flows something like

```go
authCall := auth.On("Identify", context.Background(), &magistrala.IdentityReq{Token: tc.token}).Return(tc.idRes, tc.idErr)
```

Where `idRes` can contain empty id and also `idErr` can contain Authentication error

2024-04-18 08:57 UTC, rodneyosodo commented on consumers/notifiers/service_test.go
> +		repoCall := auth.On("Identify", context.Background(), &magistrala.IdentityReq{Token: tc.token}).Return(&magistrala.IdentityRes{Id: validID}, nil)
This applies to other cases

2024-04-18 08:57 UTC, rodneyosodo commented on pkg/sdk/go/consumers_test.go
> +		repoCall := auth.On("Identify", mock.Anything, &magistrala.IdentityReq{Token: tc.token}).Return(tc.identityRes, tc.err)
define two different errors for `Identity` and `Retrieve` calls

2024-04-19 14:45 UTC, rodneyosodo approved these changes, later dismissed

2024-04-22 08:06 UTC, dborovcanin requested changes

2024-04-22 08:06 UTC, dborovcanin commented on consumers/notifiers/service_test.go
> +			identityRes: &magistrala.IdentityRes{Id: validID},
User string instead of the full response; return response in the assert. Do the same for all the other test cases.

2024-04-22 08:52 UTC, dborovcanin approved these changes

2024-04-22 08:52 UTC, merged