MG2161 - Generate mocks with mockery for mqtt
absmach/magistrala pull request #2163
Opened 2024-04-10 12:18 UTC by JeffMboya

# What type of PR is this?

This is a feature because it adds mocks for mqtt using mockery.

## What does this do?

This PR introduces mock generation for the mqtt. This will allow us to write unit tests that are isolated from the implementation details of logger. 

## Which issue(s) does this PR fix/relate to?

- Related Issue #2161 
- Resolves #2161

## Have you included tests for your changes?

Yes

## Did you document any new/modified feature?

No

2024-04-12 07:15 UTC, rodneyosodo requested changes

2024-04-12 07:15 UTC, rodneyosodo commented on mqtt/events/streams.go
> +//go:generate mockery --name EventStore --output=../mocks --filename redis.go --quiet --note "Copyright (c) Abstract Machines"
Add it to CI

2024-04-12 07:15 UTC, rodneyosodo commented on mqtt/handler_test.go
> +		repoCall := eventStore.On("Connect", mock.Anything, mock.Anything).Return(nil)
Try and reduce the use of `mock.Anything` also this is not a `repocall`

2024-04-15 07:16 UTC, rodneyosodo requested changes

2024-04-15 07:16 UTC, rodneyosodo commented on .github/workflows/api-tests.yml
> +        run: make run down args="-v"
Add a new line

2024-04-15 07:16 UTC, rodneyosodo commented on mqtt/events/streams.go
> +//go:generate mockery --name EventStore --output=../mocks --filename redis.go --quiet --note "Copyright (c) Abstract Machines"
```suggestion
//go:generate mockery --name EventStore --output=../mocks --filename events.go --quiet --note "Copyright (c) Abstract Machines"
```

2024-04-15 07:16 UTC, rodneyosodo commented on .github/workflows/check-generated-files.yml
> +          check_mock_changes ./mqtt/mocks/redis.go "MQTT Redis ./mqtt/mocks/redis.go"
```suggestion
          check_mock_changes ./mqtt/mocks/redis.go "MQTT Events Store ./mqtt/mocks/redis.go"
```

2024-04-15 07:16 UTC, rodneyosodo commented on mqtt/handler_test.go
> +	svcCall *mock.Call
Remove this top-level variable definition

2024-04-15 07:16 UTC, rodneyosodo commented on mqtt/handler_test.go
> +	eventStore := mocks.NewEventStore(t)
```suggestion
	eventStore := new(mocks.EventStore)
```

2024-04-15 07:16 UTC, rodneyosodo commented on mqtt/handler_test.go
> +		} else {
If session is not in context it should return `ErrClientNotInitialized`

2024-04-15 08:52 UTC, rodneyosodo approved these changes
LGTM

2024-04-15 14:30 UTC, dborovcanin approved these changes

2024-04-15 14:30 UTC, merged