MG2164 - Generate mocks with mockery for users
absmach/magistrala pull request #2165
Opened 2024-04-10 14:42 UTC by JeffMboya

# What type of PR is this?

This is a feature because it adds mocks for Users service using mockery.

## What does this do?

This PR introduces mock generation for the Users service. This will allow us to write unit tests that are isolated from the implementation details of logger. 

## Which issue(s) does this PR fix/relate to?

- Related Issue #2164
- Resolves #2164

## Have you included tests for your changes?

Yes

## Did you document any new/modified feature?

No

2024-04-11 11:26 UTC, rodneyosodo requested changes

2024-04-11 11:26 UTC, rodneyosodo commented on users/emailer.go
> +//go:generate mockery --name Emailer --output=./mocks --filename email.go --quiet --note "Copyright (c) Abstract Machines"
```suggestion
//go:generate mockery --name Emailer --output=./mocks --filename emailer.go --quiet --note "Copyright (c) Abstract Machines"
```

2024-04-11 11:26 UTC, rodneyosodo commented on pkg/sdk/go/setup_test.go
> +	emailer   = umocks.NewEmailer(&testing.T{})
```suggestion
	emailer   = new(mocks.Emailer)
```

2024-04-11 13:01 UTC, rodneyosodo requested changes

2024-04-11 13:01 UTC, rodneyosodo commented on pkg/sdk/go/setup_test.go
> +	"github.com/absmach/magistrala/users/mocks"
Revert to using alias `umocks`

2024-04-11 13:42 UTC, rodneyosodo requested changes

2024-04-11 13:42 UTC, rodneyosodo commented on users/emailer.go
> +//go:generate mockery --name Emailer --output=./mocks --filename emailer.go --quiet --note "Copyright (c) Abstract Machines"
Add this to CI

2024-04-11 13:42 UTC, rodneyosodo commented on users/service_test.go
> +		repoCall2 := e.On("SendPasswordReset", mock.Anything, mock.Anything, mock.Anything, mock.Anything).Return(tc.err)
This is not a repocall. `repocall` is short form for repository call

2024-04-12 14:48 UTC, rodneyosodo requested changes

2024-04-12 14:48 UTC, rodneyosodo commented on users/service_test.go
> +		svcCall := e.On("SendPasswordReset", mock.Anything, mock.Anything, mock.Anything, mock.Anything).Return(tc.err)
Reduce usage of `mock.Anything` if parameters to the function are known.

2024-04-15 07:09 UTC, rodneyosodo approved these changes
LGTM

2024-04-15 07:24 UTC, dborovcanin approved these changes

2024-04-15 07:24 UTC, merged