MG-2170 - Generate mocks with mockery for HTTP service
absmach/magistrala pull request #2171
Opened 2024-04-11 11:27 UTC by nyagamunene

# What type of PR is this?
This is a feature because its add the following functionality: generates mocks for HTTP.

## What does this do?
It generates the mocks for HTTP service.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2170 
- Resolves #2170 

## Have you included tests for your changes?
Yes, I have included tests

## Did you document any new/modified feature?
No, I have not updated the documentation.

### Notes

2024-04-12 12:15 UTC, rodneyosodo requested changes

2024-04-12 12:15 UTC, rodneyosodo commented on pkg/sdk/go/message_test.go
> +		svcCall := pub.On("Publish", mock.Anything, mock.Anything, mock.Anything).Return(nil)
Reduce usage of `mock.Anything` also in some cases return non nil errors

2024-04-15 09:02 UTC, rodneyosodo requested changes

2024-04-15 09:02 UTC, rodneyosodo commented on http/api/endpoint_test.go
> +		svcCall := pub.On("Publish", mock.Anything, mock.Anything, mock.Anything).Return(nil)
Same

2024-04-15 12:50 UTC, rodneyosodo submitted a review, later dismissed
LGTM

2024-04-15 14:29 UTC, dborovcanin approved these changes

2024-04-15 14:29 UTC, merged