MG-2173 - Generate mocks with mockery for Twins service
absmach/magistrala pull request #2174
Opened 2024-04-14 16:07 UTC by nyagamunene

# What type of PR is this?
This is a feature because its add the following functionality: generates mocks for Twins.

## What does this do?
It generates the mocks for Twins service.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2173 
- Resolves #2173 

## Have you included tests for your changes?
Yes, I have included tests

## Did you document any new/modified feature?
No, I have not updated the documentation

### Notes

2024-04-15 09:01 UTC, rodneyosodo requested changes

2024-04-15 09:01 UTC, rodneyosodo commented on twins/api/http/endpoint_states_test.go
>  	tw, err := svc.AddTwin(context.Background(), token, twin, def)
We don't need to mock this

2024-04-15 09:01 UTC, rodneyosodo commented on twins/api/http/endpoint_states_test.go
>  	err = svc.SaveStates(context.Background(), message)
same

2024-04-16 15:10 UTC, dborovcanin approved these changes, later dismissed

2024-04-18 09:07 UTC, rodneyosodo requested changes

2024-04-18 09:07 UTC, rodneyosodo commented on twins/api/http/endpoint_states_test.go
> +	_, err := CreateMessage(attr, recs)
If we are not using the output from `CreateMessage` why are we using it?

2024-04-18 09:07 UTC, rodneyosodo commented on twins/api/http/endpoint_states_test.go
> +		repoCall1 := stateRepo.On("RetrieveAll", mock.Anything, mock.Anything, mock.Anything, mock.Anything).Return(tc.page, tc.err)
Avoid the use of `mock.Anything`

2024-04-18 09:07 UTC, rodneyosodo commented on twins/api/http/endpoint_states_test.go
>  		repoCall := auth.On("Identify", mock.Anything, mock.Anything).Return(&magistrala.IdentityRes{Id: testsutil.GenerateUUID(t)}, nil)
Add unhappy flows to simulate authentication failure

2024-04-18 09:07 UTC, rodneyosodo commented on twins/api/http/endpoint_twins_test.go
> +		repoCall1 := twinRepo.On("Save", mock.Anything, mock.Anything).Return(retained, tc.err)
Try and reduce the usage of `mock.Anything`. This applies to other PRs and also other cases in this PR

2024-04-18 09:07 UTC, rodneyosodo commented on twins/api/http/endpoint_twins_test.go
> +		repoCall1 := twinRepo.On("RetrieveByID", mock.Anything, tc.id).Return(twins.Twin{}, tc.err)
Simulate different failures have error variables for `retrieveByIDErr`, `updateErr` and `cacheErr`

2024-04-19 13:28 UTC, rodneyosodo requested changes

2024-04-19 13:28 UTC, rodneyosodo commented on twins/mongodb/twins_test.go
> +func CreateDefinition(channels, subtopics []string) twins.Definition {
We can define these 2 functions in mocks the reuse them in mocks service tests

2024-04-19 14:43 UTC, rodneyosodo submitted a review, later dismissed

2024-04-22 08:14 UTC, WashingtonKK commented
Can we upgrade to the latest version of mockery (v2.42.3)?

2024-04-22 09:51 UTC, rodneyosodo approved these changes, later dismissed

2024-04-23 08:56 UTC, rodneyosodo requested changes

2024-04-23 08:56 UTC, rodneyosodo commented on twins/api/http/endpoint_states_test.go
> +func convStat(data []stateRes) []twins.State {
```suggestion
func convState(data []stateRes) []twins.State {
```

2024-04-23 09:27 UTC, rodneyosodo approved these changes

2024-04-23 11:18 UTC, dborovcanin approved these changes

2024-04-23 11:18 UTC, merged