MG-2092 - Remove unused field in token object
absmach/magistrala pull request #2191
Opened 2024-04-19 09:08 UTC by JeffMboya

### What type of PR is this?
This is a bug fix because it fixes the issue where an unused field in the token object is causing a bug on the UI.

### What does this do?
This PR removes the unused domain field from the token object when a user is not logged in to a specific domain. This prevents the UI from incorrectly indicating that the token has a domain field when it does not.

### Which issue(s) does this PR fix/relate to?
Resolves #2092 

Have you included tests for your changes?
Yes, I have included tests to ensure that the domain field is not present in the token when a user is not logged in to a specific domain.

Did you document any new/modified feature?
No

2024-04-19 12:47 UTC, rodneyosodo requested changes
Remove commits not related to this PR

2024-04-19 12:58 UTC, rodneyosodo requested changes
Try and test this PR. I have loggedin without domain login and still there are unused fields

```bash
USER_TOKEN=$(magistrala-cli users token admin@example.com 12345678 | jq -r .access_token)
```

```bash
jwt decode $USER_TOKEN


Token header
------------
{
  "typ": "JWT",
  "alg": "HS512"
}

Token claims
------------
{
  "exp": 1713534942,
  "iat": 1713531342,
  "iss": "magistrala.auth",
  "sub": "",
  "type": 0,
  "user": "bcc7b52f-70f8-43b9-8a60-ef9549b76db1"
}
```

Subject is unused

2024-04-22 07:36 UTC, rodneyosodo requested changes

2024-04-22 07:36 UTC, rodneyosodo commented on auth/jwt/token_test.go
> +		},
Add the following case:
- issue token without domain
- issue token without subject

2024-04-22 07:36 UTC, rodneyosodo commented on auth/jwt/token_test.go
> +		{
Add the following cases
- parse token with an empty domain
- parse token with empty subject

2024-04-22 13:21 UTC, rodneyosodo requested changes

2024-04-22 13:21 UTC, rodneyosodo commented on auth/jwt/token_test.go
> +	createKeyAndToken := func(domain, subject string) (auth.Key, string) {
No need for this function refactor `newToken` to provide a token when the subject or domain is empty

2024-04-23 07:17 UTC, rodneyosodo requested changes

2024-04-23 07:17 UTC, rodneyosodo commented on auth/jwt/token_test.go
> +
Create 3 different keys:
- empty domain
- empty subject
- both empty

2024-04-23 08:59 UTC, rodneyosodo approved these changes
LGTM

2024-04-23 11:30 UTC, dborovcanin approved these changes

2024-04-23 11:30 UTC, merged