MG-2059-Set correct log level depending on error
absmach/magistrala pull request #2196
Opened 2024-04-23 09:08 UTC by nyagamunene

# What type of PR is this?
This is a refactor because it sets correct log level depending on error.

## What does this do?
It fixes the correct log level for the logs. Currently all log are warnings.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2059 
- Resolves #2059 

## Have you included tests for your changes?
No.

## Did you document any new/modified feature?
No.

### Notes

2024-04-30 13:14 UTC, arvindh123 requested changes
Please check the following files, I found some error are logged as Warn : 

auth/api/logging.go L30 to L128  https://github.com/nyagamunene/magistrala/blob/a596fd9abbf62be732b9185855def1f492f3baeb/auth/api/logging.go#L37-L129

bootstrap/api/logging.go

bootstrap/postgres/configs.go

certs/api/logging.go

cmd/opcua/main.go

coap/api/transport.go

consumers/notifiers/api/logging.go

consumers/writers/api/logging.go

internal/groups/api/logging.go

consumers/writers/api/logging.go

internal/groups/api/logging.go

lora/api/logging.go

invitations/middleware/logging.go

opcua/api/logging.go

pkg/events/redis/subscriber.go

things/api/logging.go

twins/api/logging.go

users/api/logging.go

ws/api/endpoints.go

2024-05-03 08:49 UTC, rodneyosodo requested changes
Some errors should be logged with `Warn` while others should be logged with `Error`. This is a simple explanation of how to do it https://stackoverflow.com/a/2031195 . Also, consider using `ErrorContext` and pass in the context rather than `Error`

2024-05-17 12:30 UTC, rodneyosodo requested changes

2024-05-17 12:30 UTC, rodneyosodo commented on auth/api/logging.go
> +			lm.logger.ErrorContext(ctx, "List objects failed to complete successfully", args...)
Revert all errors to `WarnContext`

2024-05-17 12:30 UTC, rodneyosodo commented on ws/api/endpoints.go
> +			logger.Error(fmt.Sprintf("Failed to upgrade connection to websocket: %s", err.Error()))
Use parent context

2024-05-17 12:30 UTC, rodneyosodo commented on ws/api/endpoints.go
> +		logger.Error("Empty channel id or malformed url")
Use request context

2026-03-02 10:40 UTC, dborovcanin commented
While this PR is relevant, it's been almost 2 years. It's obsolete, with low priority, and it doesn't make sense to continue with it. We will need a new PR to address this. Also, the title is misleading - it is related to a single log, not to logger as the may might imply.

2026-03-02 10:40 UTC, closed without merging