NOISSUE-doc-update - Update documentation with example requests and responses
absmach/magistrala pull request #220
Opened 2018-04-10 14:35 UTC by anovakovic01

Update documentation with example requests and responses in accordance
with new API changes. Add detailed flow explanation.

Signed-off-by: Aleksandar Novakovic <anovakovic01@gmail.com>

2018-04-10 14:40 UTC, drasko commented on docs/getting-started.md
> +```
I would also add `HTTPS` variant served by NginX (i.e. port `443` or `80`->`443` redirection)

2018-04-10 14:40 UTC, drasko commented on docs/getting-started.md
> +```
It does not have to be for every example, but at least one - to show people how to use HTTPS + cert

2018-04-10 21:07 UTC, drasko approved these changes
LGTM

2018-04-11 11:03 UTC, mijicd requested changes

2018-04-11 11:03 UTC, mijicd commented on docs/getting-started.md
> +Use the Mainflux manager HTTP/REST API to create user account:
`Use the Mainflux API to create user account:`. Drop REST/HTTP wherever not necessary.

2018-04-11 11:03 UTC, mijicd commented on docs/getting-started.md
> +Response will contain `Location` header which value represents path to newly
`... header whose value ...`

2018-04-11 11:03 UTC, mijicd commented on docs/getting-started.md
> +`"type":"app"` specified in JSON payload. Note that applications are also Mainflux
No need for `note that` section.

2018-04-11 11:03 UTC, mijicd commented on docs/getting-started.md
> +Response will contain `Location` header which value represents path to newly
`... header whose value ...`

2018-04-11 12:29 UTC, mijicd approved these changes

2018-04-11 12:30 UTC, merged