MG-1977 - Check whether user is domain member before sending invitation
absmach/magistrala pull request #2213
Opened 2024-04-30 13:22 UTC by 1998-felix

Signed-off-by: Felix Gateru [1998-felix](mailto:felix.gateru@gmail.com)
# What type of PR is this?
This is a bug fix because it fixes the following issue: #1977

## What does this do?
This pr introduces a check for whether a user to be invited is already part of the domain before an invitation to the domain is sent.

## Which issue(s) does this PR fix/relate to?

- Resolves #1977

## Have you included tests for your changes?
Yes, I have updated tests for my changes.

## Did you document any new/modified feature?
No,

### Notes
None

2024-04-30 14:22 UTC, dborovcanin commented
@1998-felix Is this ready?

2024-04-30 14:23 UTC, 1998-felix commented
> @1998-felix Is this ready?

Not yet

2024-05-02 08:24 UTC, WashingtonKK commented on invitations/service.go
> +		return svcerr.ErrConflict
Wrap this with an error that indicates that the user is already a member of the domain so that it is not mistaken for a situation where the invitation has already been sent to the user.

2024-05-03 09:15 UTC, rodneyosodo requested changes

2024-05-03 09:15 UTC, rodneyosodo commented on invitations/service.go
> +	if err := svc.authorize(ctx, domainUserId, auth.MembershipPermission, auth.DomainType, invitation.DomainID); err == nil {
Move this auth check after identify

2024-05-07 09:25 UTC, rodneyosodo submitted a review, later dismissed
LGTM

2024-05-07 09:33 UTC, WashingtonKK commented on invitations/service_test.go
> +			domainErr1:  nil,
Make this error and the corresponding request more descriptive. e.g. `domainMembershipReq`.

2024-05-07 10:03 UTC, WashingtonKK approved these changes
LGTM

2024-05-09 07:22 UTC, rodneyosodo approved these changes

2024-05-10 08:27 UTC, dborovcanin approved these changes

2024-05-10 08:27 UTC, merged