MG-1963 - Proxy CoAP using mproxy
absmach/magistrala pull request #2222
Opened 2024-05-07 09:11 UTC by 1998-felix

# What type of PR is this?
This is a feature because it updates the coap proxy to use mproxy.

## What does this do?
This pr updates the coap proxy to use mproxy

## Which issue(s) does this PR fix/relate to?

- Related Issue #1963 
- Resolves #1963

## Have you included tests for your changes?
No

## Did you document any new/modified feature?
No

### Notes
To be merged after #2183

2024-06-12 14:54 UTC, dborovcanin commented
@felixgateru Please resolve conflicts.

2025-09-23 12:51 UTC, rodneyosodo requested changes

2025-09-23 12:51 UTC, rodneyosodo commented on docker/.env
> +SMQ_COAP_ADAPTER_SERVER_CA_FILE=
- [x] DTLS certs are not mapped inside the container
- [x] DTLS certs are not correctly inputed

```
SMQ_COAP_ADAPTER_SERVER_CERT_FILE=""
```


- [x] On `docker/ssl/Makefile`, lets add this so that we can generate CoAP server certs

```
COAP_GRPC_SERVER_CONF_FILE_NAME=coap-server.conf
COAP_GRPC_SERVER_CN=coap
COAP_GRPC_SERVER_CRT_FILE_NAME=coap-server

coap_grpc_certs:
	$(call gen_grpc_cert,$(COAP_GRPC_SERVER_CRT_FILE_NAME),$(COAP_GRPC_SERVER_CN))

```

- [x] We should consider an env variable that enables `COAP_DTLS` same as `GRPC_MTLS`

2025-09-24 10:54 UTC, rodneyosodo requested changes
We should also consider updating the docs repo for this new feature

2025-09-24 10:54 UTC, rodneyosodo commented on docker/ssl/Makefile
> +COAP_DTLS_SERVER_CRT_FILE_NAME=coap-server
How do I generate client certs?

2025-09-24 11:22 UTC, rodneyosodo submitted a review, later dismissed
LGTM

2025-09-30 10:36 UTC, arvindh123 requested changes

2025-09-30 10:36 UTC, arvindh123 commented on coap/adapter.go
> -	authzRes, err := svc.channels.Authorize(ctx, &grpcChannelsV1.AuthzReq{
Is it possible to remove the channel authorization while unsubscribing ?
https://github.com/absmach/supermq/blob/69b849ccdeed2ba620d111e740df49e6b3ac5461/coap/adapter.go#L116-L128

2025-09-30 10:36 UTC, arvindh123 requested changes
Can we

2025-10-16 15:57 UTC, rodneyosodo submitted a review, later dismissed

2025-10-16 19:40 UTC, drasko commented
@dborovcanin, please review and let's merge

2025-10-24 14:58 UTC, dborovcanin requested changes

2025-10-24 14:58 UTC, dborovcanin commented on coap/handler.go
> +	LogInfoPublished    = "published with client_id %s to the topic %s"
Don't export unless necessary. Also, add `fmt` suffix to indicate this is format. Like `subscribedInfoFmt`, `connectedInfoFmt`...

2025-10-24 14:58 UTC, dborovcanin commented on docker/ssl/.gitignore
> +*coap-server*
Remove.

2025-10-24 15:55 UTC, merged