MG-2075-Add guest relation
absmach/magistrala pull request #2228
Opened 2024-05-13 13:56 UTC by nyagamunene

# What type of PR is this?
This is a feature because it adds a policy to a domain member to restrict the creation of new entities such as things, channels and groups in a domain

## What does this do?
It adds a guest relation policy to a domain member to restrict the creation of new entities such as things, channels and groups in a domain

## Which issue(s) does this PR fix/relate to?

- Related Issue #2075 
- Resolves #2075 

## Have you included tests for your changes?
No

## Did you document any new/modified feature?
No

### Notes

2024-05-20 13:20 UTC, arvindh123 requested changes

2024-05-20 13:20 UTC, arvindh123 commented on users/service.go
> +		fmt.Println(err.Error())
Remove this log line

2024-05-28 12:36 UTC, arvindh123 approved these changes, later dismissed

2024-05-28 13:35 UTC, rodneyosodo requested changes
Update SDK godocs

2024-05-28 13:35 UTC, rodneyosodo commented on users/service.go
> +		fmt.Println(err.Error())
Remove debug statements

2024-05-28 13:35 UTC, rodneyosodo commented on auth/service.go
> +	case GuestRelation:
Update this test too `TestSwitchToPermission`

2024-05-28 13:35 UTC, rodneyosodo commented on auth/service.go
> +	case GuestRelation:
also `TestCheckRelation`

2024-05-29 09:43 UTC, rodneyosodo submitted a review, later dismissed

2024-05-30 07:27 UTC, arvindh123 requested changes
@nyagamunene , Please update SDK godocs   
like how we have added for contributor relation  https://github.com/absmach/magistrala/pull/2237/files#diff-b5c7528ff157413346fba986ef7b76e891ac8088631bdebd3fcae8b30338ddb1

2024-06-05 11:02 UTC, rodneyosodo approved these changes, later dismissed

2024-06-10 07:04 UTC, arvindh123 submitted a review, later dismissed
LGTM

2024-06-10 07:56 UTC, rodneyosodo approved these changes, later dismissed

2024-06-12 14:18 UTC, dborovcanin approved these changes

2024-06-12 14:19 UTC, merged