MG-2025 - CLI : Flag to print only curl output
absmach/magistrala pull request #2242
Opened 2024-05-17 11:25 UTC by JeffMboya

## What type of PR is this?

This is a feature because it adds the ability to print only curl output in the CLI.

## What does this do?

This PR adds a new flag `--curl` to the CLI. When this flag is used, the CLI will print the actual request sent as a cURL command. This will be useful for debugging and for users to visualize the request sent by the CLI/SDK.

The implementation uses the `http2curl` library to convert http requests to cURL commands.

## Which issue(s) does this PR fix/relate to?

- Resolves #2025

## Have you included tests for your changes?

No.

## Did you document any new/modified feature?

No

2024-06-10 17:04 UTC, arvindh123 requested changes

2024-06-10 17:04 UTC, arvindh123 commented on Makefile
> +	done
Please revert this changes

2024-06-12 10:31 UTC, arvindh123 commented
If this PR is Approved and ready for merge, then we need to create Ticket in Magistrala docs to update CLI docs https://github.com/absmach/magistrala-docs/issues/new

2024-06-12 10:58 UTC, JeffMboya commented
> If this PR is Approved and ready for merge, then we need to create Ticket in Magistrala docs to update CLI docs https://github.com/absmach/magistrala-docs/issues/new

https://github.com/absmach/magistrala-docs/issues/192

2024-06-13 09:19 UTC, arvindh123 approved these changes

2024-06-18 09:23 UTC, dborovcanin approved these changes

2024-06-18 09:23 UTC, merged