MG-887 - Add Users CLI Tests.
absmach/magistrala pull request #2250
Opened 2024-05-21 03:30 UTC by WashingtonKK

# What type of PR is this?

This is an enhancement because it adds cli tests for users.

## What does this do?

This adds tests for cli, to check for invalid args input, and logging of output.

## Which issue(s) does this PR fix/relate to?

- Resolves #887

## Have you included tests for your changes?

Yes, I have included tests for my changes.

## Did you document any new/modified feature?

No, I have not updated the documentation because there are no new features, just an increase in scope of the existing tests to cover CLI.

### Notes

This is the first PR in this series, to be merged first.

2024-05-21 09:22 UTC, rodneyosodo requested changes

2024-05-21 09:22 UTC, rodneyosodo commented on cli/users_test.go
> +package cli
This should be `cli_test`

2024-05-21 09:22 UTC, rodneyosodo commented on cli/utils.go
> +func executeCommand(root *cobra.Command, v any, args ...string) (errorRes, out string, err error) {
This should not be in cli package but tests package

2024-05-21 09:22 UTC, rodneyosodo commented on cli/utils.go
> +	o := os.Stdout
Are we using these variables?

2024-05-21 09:22 UTC, rodneyosodo commented on cli/utils.go
> +	r, w, _ := os.Pipe()
Don't ignore errors assert they are nil or return

2024-05-21 09:22 UTC, rodneyosodo commented on cli/utils.go
> +	err = json.Unmarshal(res, v)
inline

2024-05-21 09:22 UTC, rodneyosodo commented on cli/users_test.go
> +		assert.True(t, !strings.Contains(out, rootCmd.Use), fmt.Sprintf("%s invalid usage: %s", tc.desc, out))
assert False

2024-05-21 09:22 UTC, rodneyosodo commented on cli/users_test.go
> +		sdkCall := sdkmocks.On("ListUserGroups", mock.Anything, mock.Anything, mock.Anything).Return(tc.page, tc.sdkerr)
Reduce use of `mock.Anything`

2024-05-21 11:10 UTC, WashingtonKK commented on cli/utils.go
> +	o := os.Stdout
Yes, `o` and `e` store the initial outputs and they are restored to the original value after use.

2024-05-22 11:29 UTC, rodneyosodo requested changes
Update `make test` to include this tests https://github.com/absmach/magistrala/blob/42be65a3d20df7ad999253e5b2b2a10490b1d64d/Makefile#L127 and also trigger it to run on PRs https://github.com/absmach/magistrala/blob/main/.github/workflows/tests.yml

2024-06-07 12:31 UTC, arvindh123 requested changes
At logs, we directly printing to `os.stdout` and `os.stderr`, 
Actually, cobra should take care to redirecting to out or error 

So We need to modify the log to like below 

```go
func logError( cmd *cobra.Command , err error) {
	boldRed := color.New(color.FgRed, color.Bold)
	boldRed.Fprintf(cmd.OutOrStderr(, "\nerror: ")

	fmt.Fprintf(cmd.OutOrStderr(), "%s\n\n", color.RedString(err.Error()))
}
```
Please modify the log functions like above and test

if it works , then create a `custom cobra.Command`, like below

```go
type cmd struct {
	*cobra.Command
}

func (c *cmd) logJSON(iList ...interface{}) {
	for _, i := range iList {
		m, err := json.Marshal(i)
		if err != nil {
			c.logError(err)
			return
		}

		pj, err := prettyjson.Format(m)
		if err != nil {
			c.logError(err)
			return
		}

		fmt.Fprintf(c.OutOrStdout(), "\n%s\n\n", string(pj))
	}
}

func (c *cmd) logUsage(u string) {
	fmt.Fprintf(c.OutOrStdout(), color.YellowString("\nusage: %s\n\n"), u)
}

func (c *cmd) logError(err error) {
	boldRed := color.New(color.FgRed, color.Bold)
	boldRed.Fprintf(c.OutOrStderr(), "\nerror: ")

	fmt.Fprintf(c.OutOrStderr(), "%s\n\n", color.RedString(err.Error()))
}
```

2024-06-10 08:40 UTC, WashingtonKK commented
> At logs, we directly printing to `os.stdout` and `os.stderr`, Actually, cobra should take care to redirecting to out or error
> 
> So We need to modify the log to like below
> 
> ```go
> func logError( cmd *cobra.Command , err error) {
> 	boldRed := color.New(color.FgRed, color.Bold)
> 	boldRed.Fprintf(cmd.OutOrStderr(, "\nerror: ")
> 
> 	fmt.Fprintf(cmd.OutOrStderr(), "%s\n\n", color.RedString(err.Error()))
> }
> ```
> 
> Please modify the log functions like above and test
> 
> if it works , then create a `custom cobra.Command`, like below
> 
> ```go
> type cmd struct {
> 	*cobra.Command
> }
> 
> func (c *cmd) logJSON(iList ...interface{}) {
> 	for _, i := range iList {
> 		m, err := json.Marshal(i)
> 		if err != nil {
> 			c.logError(err)
> 			return
> 		}
> 
> 		pj, err := prettyjson.Format(m)
> 		if err != nil {
> 			c.logError(err)
> 			return
> 		}
> 
> 		fmt.Fprintf(c.OutOrStdout(), "\n%s\n\n", string(pj))
> 	}
> }
> 
> func (c *cmd) logUsage(u string) {
> 	fmt.Fprintf(c.OutOrStdout(), color.YellowString("\nusage: %s\n\n"), u)
> }
> 
> func (c *cmd) logError(err error) {
> 	boldRed := color.New(color.FgRed, color.Bold)
> 	boldRed.Fprintf(c.OutOrStderr(), "\nerror: ")
> 
> 	fmt.Fprintf(c.OutOrStderr(), "%s\n\n", color.RedString(err.Error()))
> }
> ```

@arvindh123 , this implementation does not work, and coverage is still not generated.

2024-06-10 08:42 UTC, WashingtonKK commented
> > At logs, we directly printing to `os.stdout` and `os.stderr`, Actually, cobra should take care to redirecting to out or error
> > So We need to modify the log to like below
> > ```go
> > func logError( cmd *cobra.Command , err error) {
> > 	boldRed := color.New(color.FgRed, color.Bold)
> > 	boldRed.Fprintf(cmd.OutOrStderr(, "\nerror: ")
> > 
> > 	fmt.Fprintf(cmd.OutOrStderr(), "%s\n\n", color.RedString(err.Error()))
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please modify the log functions like above and test
> > if it works , then create a `custom cobra.Command`, like below
> > ```go
> > type cmd struct {
> > 	*cobra.Command
> > }
> > 
> > func (c *cmd) logJSON(iList ...interface{}) {
> > 	for _, i := range iList {
> > 		m, err := json.Marshal(i)
> > 		if err != nil {
> > 			c.logError(err)
> > 			return
> > 		}
> > 
> > 		pj, err := prettyjson.Format(m)
> > 		if err != nil {
> > 			c.logError(err)
> > 			return
> > 		}
> > 
> > 		fmt.Fprintf(c.OutOrStdout(), "\n%s\n\n", string(pj))
> > 	}
> > }
> > 
> > func (c *cmd) logUsage(u string) {
> > 	fmt.Fprintf(c.OutOrStdout(), color.YellowString("\nusage: %s\n\n"), u)
> > }
> > 
> > func (c *cmd) logError(err error) {
> > 	boldRed := color.New(color.FgRed, color.Bold)
> > 	boldRed.Fprintf(c.OutOrStderr(), "\nerror: ")
> > 
> > 	fmt.Fprintf(c.OutOrStderr(), "%s\n\n", color.RedString(err.Error()))
> > }
> > ```
> 
> @arvindh123 , this implementation does not work, and coverage is still not generated.

I suppose this is because the function `OutOrStdout` simply returns the writer that is set using `SetOut` and `SerErr` and uses it to write all output which still does not solve our issue.

2024-06-10 17:55 UTC, arvindh123 requested changes
This one works for me, We need to some how mock cobra execute or we need to create mock server service which cli is calling
```go
func logJSONCmd(cmd cobra.Command, iList ...interface{}) {
	for _, i := range iList {
		m, err := json.Marshal(i)
		if err != nil {
			logErrorCmd(cmd, err)
			return
		}

		pj, err := prettyjson.Format(m)
		if err != nil {
			logErrorCmd(cmd, err)
			return
		}

		fmt.Fprintf(cmd.OutOrStdout(), "\n%s\n\n", string(pj))
	}
}

func logUsageCmd(cmd cobra.Command, u string) {
	fmt.Fprintf(cmd.OutOrStdout(), color.YellowString("\nusage: %s\n\n"), u)
}

func logErrorCmd(cmd cobra.Command, err error) {
	boldRed := color.New(color.FgRed, color.Bold)
	boldRed.Fprintf(cmd.ErrOrStderr(), "\nerror: ")

	fmt.Fprintf(cmd.ErrOrStderr(), "%s\n\n", color.RedString(err.Error()))
}

func logOKCmd(cmd cobra.Command) {
	fmt.Fprintf(cmd.OutOrStdout(), "\n%s\n\n", color.BlueString("ok"))
}

func logCreatedCmd(cmd cobra.Command, e string) {
	if RawOutput {
		fmt.Fprintln(cmd.OutOrStdout(), e)
	} else {
		fmt.Fprintf(cmd.OutOrStdout(), color.BlueString("\ncreated: %s\n\n"), e)
	}
}

func logRevokedTimeCmd(cmd cobra.Command, t time.Time) {
	if RawOutput {
		fmt.Fprintln(cmd.OutOrStdout(), t)
	} else {
		fmt.Fprintf(cmd.OutOrStdout(), color.BlueString("\nrevoked: %v\n\n"), t)
	}
}


```

2024-06-10 17:55 UTC, arvindh123 commented on cli/setup_test.go
> +}
Some thing like this works ,But we need to mock the actual service server,
```suggestion
func executeCommand(t *testing.T, root *cobra.Command, args ...string) string {
	buffer := new(bytes.Buffer)
	root.SetOut(buffer)
	root.SetErr(buffer)
	root.SetArgs(args)

	err := root.Execute()
	assert.NoError(t, err, "Error executing command")

	return buffer.String()
}
```

2024-06-10 17:55 UTC, arvindh123 commented on cli/users_test.go
> +		},
Wrong args are passed.
```suggestion
			desc: "create user successfully with token",
			args: []string{
				createCommand,
				user.Name,
				user.Credentials.Identity,
				user.Credentials.Secret,
				token,
			},
			user:    user,
			logType: entityLog,
		},
```

2024-06-10 17:55 UTC, arvindh123 commented on cli/users_test.go
> +			},
Same here wrong args 
```suggestion
				createCommand,
				user.Name,
				user.Credentials.Identity,
				user.Credentials.Secret,
			},
```

2024-06-10 17:55 UTC, arvindh123 commented on cli/users_test.go
> +			},
```suggestion
				user.Name,
				user.Credentials.Identity,
				user.Credentials.Secret,
				token,
```

2024-06-10 17:55 UTC, arvindh123 commented on cli/users_test.go
> +			logType: usageLog,
```suggestion
			desc: "create user with invalid args",
			args: []string{
				createCommand,
				user.Name,
				user.Credentials.Identity,
			},
			logType: usageLog,
```

2024-06-10 17:55 UTC, arvindh123 commented on cli/users_test.go
> +
```suggestion
		out := executeCommand(t, rootCmd, tc.args...)

```

2024-07-10 12:41 UTC, dborovcanin commented
Closing as duplicate of https://github.com/absmach/magistrala/pull/2319.

2024-07-10 12:41 UTC, closed without merging