Mf-136 - Setup staging and test environments
absmach/magistrala pull request #226
Opened 2018-04-16 09:57 UTC by dusanb94

Setup Mainflux services to work in Kubernetes environment.

2018-04-16 10:11 UTC, drasko reviewed
LGTM

2018-04-26 08:45 UTC, mijicd requested changes
Flatten the directory structure by moving the `deployment/kubernetes` contents into `k8s` directory in project root.

2018-04-26 08:45 UTC, mijicd commented on deployment/kubernetes/ingress-controller/ingress.yaml
> +    # ingress.kubernetes.io/rewrite-target: /api
Same here.

2018-04-26 08:45 UTC, mijicd commented on deployment/kubernetes/nomralizer/deployment.yml
> +apiVersion: apps/v1beta1
Fix directory name typo.

2018-04-30 11:27 UTC, mijicd requested changes

2018-04-30 11:27 UTC, mijicd commented on k8s/nginx/README.md
> +# NGINX as Reverse Proxy for Mainflux services
As far as i can see, this is already a part of `k8s/README.md`. Hence, please remove it.

2018-04-30 11:32 UTC, mijicd approved these changes

2018-04-30 11:32 UTC, merged