MG-888 - Add bootstrap SDK tests
absmach/magistrala pull request #2261
Opened 2024-05-29 09:00 UTC by felixgateru

# What type of PR is this?
This is a feature as it adds tests for bootstrap related methods in the SDK.

## What does this do?
This pr adds tests for bootstrap service related methods in the sdk.

## Which issue(s) does this PR fix/relate to?

- Related Issue #888 

## Have you included tests for your changes?
Yes, tests are the changes.

## Did you document any new/modified feature?
No,

### Notes

2024-05-31 09:24 UTC, rodneyosodo requested changes
For valid cases check the service call had been called something similar to https://github.com/absmach/magistrala/blob/31d0e8c4529339a6626c9ff03a65972bf407dd89/pkg/sdk/go/users_test.go#L194

2024-05-31 09:24 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap_test.go
> +type readerChannelRes struct {
define this at the top

2024-05-31 09:24 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap_test.go
> +			assert.Equal(t, tc.page.Configs, res.Configs, fmt.Sprintf("%s: expected %v got %v\n", tc.desc, tc.page, res))
```suggestion
			assert.Equal(t, tc.page, res, fmt.Sprintf("%s: expected %v got %v\n", tc.desc, tc.page, res))
```

2024-05-31 09:24 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap_test.go
> +			assert.Equal(t, tc.page.Configs, res.Configs, fmt.Sprintf("%s: expected %v got %v\n", tc.desc, tc.page, res))
Then update total

2024-05-31 09:24 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap_test.go
> +		err := mgsdk.Whitelist(tc.cfg, tc.token)
You can change this function to take id and state rather than config since we are only using those 2

2024-05-31 09:24 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap_test.go
> +		svcCall := bsvc.On("ChangeState", mock.Anything, tc.token, tc.svcRequest, bootstrap.Active).Return(tc.svcErr)
what about inactive cases?

2024-05-31 09:24 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap_test.go
> +	}{
add empty update where config is empty except for thingID

2024-05-31 09:24 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap_test.go
> +	}{
same

2024-05-31 09:24 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap_test.go
> +		readerCall := reader.On("ReadConfig", mock.Anything, mock.Anything).Return(tc.readerResponse, tc.readerErr)
Can we get the actual values rather than using `mock.Anything` ?

2024-05-31 09:24 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap_test.go
> +		readerCall := reader.On("ReadConfig", mock.Anything, mock.Anything).Return(tc.readerResponse, tc.readerErr)
same

2024-05-31 09:24 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap_test.go
> +		{
add a case where the response is empty hence we fail to decrypt

2024-06-05 14:47 UTC, felixgateru commented on pkg/sdk/go/bootstrap_test.go
> +		{
The case for the empty response is included.

2024-06-11 05:47 UTC, JeffMboya approved these changes, later dismissed

2024-06-11 09:39 UTC, rodneyosodo requested changes

2024-06-11 09:39 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap.go
> +	if thingID == "" {
Move checks before any operation

2024-06-11 09:39 UTC, rodneyosodo commented on pkg/sdk/go/bootstrap.go
> +	if id == "" {
Also check for `Bootstrap` and `BootstrapSecure` that the `externalID` is not empty

2024-06-12 09:29 UTC, rodneyosodo submitted a review, later dismissed

2024-06-26 06:03 UTC, arvindh123 approved these changes

2024-06-26 11:57 UTC, rodneyosodo approved these changes

2024-06-26 12:44 UTC, dborovcanin approved these changes

2024-06-26 12:45 UTC, merged