MG-888 - Add certs API tests
absmach/magistrala pull request #2265
Opened 2024-05-30 14:34 UTC by felixgateru

# What type of PR is this?
This is a feature because it adds api tests for the certs service.

## What does this do?
This pr introduces `/certs/api/endpoint_test.go` file for api tests.

## Which issue(s) does this PR fix/relate to?

- Related Issue #888 

## Have you included tests for your changes?
Yes, the test file is the change.

## Did you document any new/modified feature?
No,

### Notes

2024-05-31 08:56 UTC, rodneyosodo requested changes

2024-05-31 08:56 UTC, rodneyosodo commented on certs/api/endpoint_test.go
> +		svcCall := svc.On("IssueCert", mock.Anything, tc.token, tc.thingID, tc.ttl).Return(cert, tc.svcErr)
```suggestion
		svcCall := svc.On("IssueCert", mock.Anything, tc.token, tc.thingID, tc.ttl).Return(tc.svcRes, tc.svcErr)
```

2024-05-31 08:56 UTC, rodneyosodo commented on certs/api/endpoint_test.go
> +			desc:     " view no existing cert",
```suggestion
			desc:     "view no existing cert",
```

2024-05-31 08:56 UTC, rodneyosodo commented on certs/api/endpoint_test.go
> +			desc:    "list with limit exceeding",
```suggestion
			desc:    "list with limit exceeding max limit",
```

2024-05-31 09:39 UTC, rodneyosodo requested changes

2024-05-31 09:39 UTC, rodneyosodo commented on certs/api/endpoint_test.go
> +	req.Header.Set("Referer", tr.referer)
We don't need this

2024-05-31 09:39 UTC, rodneyosodo commented on certs/api/endpoint_test.go
> +	validReqString := `{
make this inline

```go
validReqString := `{"thing_id": "%s","ttl": "%s"}`
invalidReqString := `{"thing_id": "%s","ttl": %s}`
```

2024-06-05 10:28 UTC, rodneyosodo approved these changes

2024-06-10 13:06 UTC, arvindh123 approved these changes

2024-06-11 12:10 UTC, JeffMboya approved these changes
LGTM

2024-06-12 07:37 UTC, dborovcanin approved these changes

2024-06-12 07:40 UTC, merged