MG-888 - Update certs sdk tests
absmach/magistrala pull request #2267
Opened 2024-05-31 09:19 UTC by felixgateru

# What type of PR is this?
This is a refactor as it refactors certs tests in the sdk.

## What does this do?

This pr:
- renames `valid` in issue cert to `validity`
- refactors certs tests

## Which issue(s) does this PR fix/relate to?

- Related Issue #888 

## Have you included tests for your changes?
Yes, the changes are to the tests.

## Did you document any new/modified feature?
Yes, I have updated the documentation for the sdk change.

### Notes

2024-05-31 09:34 UTC, rodneyosodo requested changes

2024-05-31 09:34 UTC, rodneyosodo commented on pkg/sdk/go/sdk.go
> +	//  cert, _ := sdk.IssueCert("thingID", "validity", "token")
add a valid validity example

2024-05-31 09:34 UTC, rodneyosodo commented on pkg/sdk/go/certs_test.go
>  		_, err := mgsdk.IssueCert(tc.thingID, tc.duration, tc.token)
Check returned cert is what is expected

2024-05-31 09:34 UTC, rodneyosodo commented on pkg/sdk/go/certs_test.go
> +			desc:   "view cert with invalid token",
```suggestion
			desc:   "view cert with missing token",
```

Add another case for invalid token

2024-05-31 09:34 UTC, rodneyosodo commented on pkg/sdk/go/certs_test.go
>  			desc:    "get cert with invalid token",
add another case for missing token

2024-06-05 10:36 UTC, rodneyosodo requested changes

2024-06-05 10:36 UTC, rodneyosodo commented on pkg/sdk/go/certs_test.go
> +		svcCall := svc.On("IssueCert", mock.Anything, tc.token, tc.thingID, tc.duration).Return(tc.svcRes, tc.svcErr)
Refactor this to something like for all SDK tests too

```go
t.Run(tc.desc, func(t *testing.T) {
	svcCall := svc.On("IssueCert", mock.Anything, tc.token, tc.thingID, tc.duration).Return(tc.svcRes, tc.svcErr)
	resp, err := mgsdk.IssueCert(tc.thingID, tc.duration, tc.token)
	assert.Equal(t, tc.err, err)
	if tc.err == nil {
		assert.Equal(t, sdkCert, resp)
		ok := svcCall.Parent.AssertCalled(t, "IssueCert", mock.Anything, tc.token, tc.thingID, tc.duration)
		assert.True(t, ok)
	}
	svcCall.Unset()
})
```

2024-06-10 13:05 UTC, arvindh123 approved these changes

2024-06-11 08:11 UTC, WashingtonKK approved these changes
LGTM

2024-06-11 08:11 UTC, WashingtonKK approved these changes

2024-06-11 09:31 UTC, rodneyosodo approved these changes
LGTM

2024-06-18 08:59 UTC, merged