MG-888 - Update consumers SDK tests
absmach/magistrala pull request #2271
Opened 2024-06-04 12:24 UTC by felixgateru

# What type of PR is this?
This is a refactor as it updates consumers SDK tests.

## What does this do?
This pr:

- Refactors comsumers sdk tests to use service mocks.
- Fixes bug in consumers not returning error with status.

## Which issue(s) does this PR fix/relate to?

- Related Issue #888 

## Have you included tests for your changes?
Yes, the changes are the tests.

## Did you document any new/modified feature?
No,

### Notes

2024-06-05 10:41 UTC, rodneyosodo requested changes

2024-06-05 10:41 UTC, rodneyosodo commented on pkg/sdk/go/consumers_test.go
> +		svcCall := nsvc.On("CreateSubscription", mock.Anything, tc.token, tc.svcReq).Return(tc.svcRes, tc.svcErr)
Do the same https://github.com/absmach/magistrala/pull/2267#discussion_r1627472265

2024-06-05 10:41 UTC, rodneyosodo commented on pkg/sdk/go/consumers_test.go
> +		err      errors.SDKError
Add invalid pageMetadata as a case

2024-06-10 13:03 UTC, arvindh123 submitted a review, later dismissed

2024-06-11 09:33 UTC, rodneyosodo submitted a review, later dismissed
LGTM

2024-06-26 09:47 UTC, dborovcanin approved these changes

2024-06-26 11:40 UTC, merged