NOISSUE - Fix CI to fetch tags
absmach/magistrala pull request #2282
Opened 2024-06-10 15:44 UTC by dborovcanin

# What type of PR is this?

This is a quick fix of CI scirpt.

## What does this do?

Since our code build includes the latest Git tag for the Health endpoint, we need to have at least the latest tag available during building binaries in the CI.

## Which issue(s) does this PR fix/relate to?

There is no such issue.

## Have you included tests for your changes?

N/A

## Did you document any new/modified feature?

N/A

### Notes

N/A

2024-06-10 17:00 UTC, arvindh123 approved these changes, later dismissed

2024-06-10 19:13 UTC, dborovcanin commented
Unfortunately, fetching tags on this action is still broken: https://github.com/actions/checkout/issues/1471. I had to add a manual step for that.

2024-06-11 07:14 UTC, rodneyosodo requested changes

2024-06-11 07:14 UTC, rodneyosodo commented on .github/workflows/build.yml
> +        with:
Since this doesn't work do we still need it?

2024-06-11 07:14 UTC, rodneyosodo commented on .github/workflows/tests.yml
> +      - name: Fetch tags for the build
Shouldn't this only be needed on the build workflow?

2024-06-11 09:58 UTC, rodneyosodo requested changes

2024-06-11 09:58 UTC, rodneyosodo commented on Makefile
> +VERSION ?= $(shell git describe --abbrev=0 --tags || echo 'unknown')
```suggestion
VERSION ?= $(shell git describe --abbrev=0 --tags 2>/dev/null || echo 'unknown')
```

2024-06-11 10:06 UTC, rodneyosodo approved these changes
LGTM

2024-06-11 10:12 UTC, merged