NOISSUE - Fix list domain users
absmach/magistrala pull request #2369
Opened 2024-08-01 12:13 UTC by nyagamunene

# What type of PR is this?
This is a bug fix because it fixes list domain user.

## What does this do?
It fixes how `listMembers` is implemented.

## Which issue(s) does this PR fix/relate to?

No issue.

## Have you included tests for your changes?
Yes

## Did you document any new/modified feature?

N/A

### Notes

2024-08-01 12:41 UTC, dborovcanin requested changes

2024-08-01 12:41 UTC, dborovcanin commented on users/service.go
> +	}
This type of filter will result in the incorrect total count.

2024-08-02 06:34 UTC, ianmuchyri approved these changes

2025-07-28 11:24 UTC, nyagamunene commented
Listing domain users was moved to roles and is handles in a different manner: https://github.com/absmach/supermq/blob/8e70e1113e0d8a98a63c82e4e368aa504b017d11/pkg/roles/provisionmanage.go#L538

2025-07-28 11:24 UTC, closed without merging