MG-2301 - Verify connections during creation of bootstrap
absmach/magistrala pull request #2371
Opened 2024-08-01 16:13 UTC by nyagamunene

# What type of PR is this?
This is a bug fix because it fixes the following issue: #2301 

## What does this do?
It adds verify connections  in the `aad` method in bootstrap.

## Which issue(s) does this PR fix/relate to?
- Related Issue #2301 
- Resolves #2301 

## Have you included tests for your changes?
Yes

## Did you document any new/modified feature?
N/A

### Notes

2024-08-08 10:57 UTC, arvindh123 requested changes

2024-08-08 10:57 UTC, arvindh123 commented on things/things.go
> +	VerifyConnections(ctx context.Context, token string, thingID, groupID []string) (clients.ConnectionsPage, error)
instead of `thingID` `groupID` we can have like `thingIDs` and `groupIDs`, since they are slice

2024-08-08 10:57 UTC, arvindh123 commented on bootstrap/events/producer/streams_test.go
> +		desc           string
changes related to bootstrap are needed in this PR ?

2024-08-08 10:57 UTC, arvindh123 commented on auth/service.go
> +}
We can have this logic in Things service, 
Like things service will verify connection via auth gRPC connection.

2024-08-08 10:57 UTC, arvindh123 commented on auth/service.go
> +}
This may be inefficent if we move this logic to things service, but in future we can have direct grpc connection to spiceDB from things service.

2025-01-11 13:23 UTC, dborovcanin commented
The Boostrap service has been moved to the Magistrala repository.  @nyagamunene Please send this PR to Magistrala.

2025-01-11 13:23 UTC, closed without merging