reject an invitation
absmach/magistrala pull request #2379
Opened 2024-08-09 14:33 UTC by SammyOina

# What type of PR is this?

## What does this do?

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2024-08-12 11:30 UTC, felixgateru requested changes

2024-08-12 11:30 UTC, felixgateru commented on invitations/service_test.go
> +		platformcall := authsvc.On("Authorize", context.Background(), &platformReq).Return(&magistrala.AuthorizeRes{Authorized: tc.authorised}, tc.adminErr)
I dont think this code is required.

2024-08-12 11:30 UTC, felixgateru commented on invitations/service_test.go
> +func TestRejectInvitation(t *testing.T) {
Add a test case for a failed `UpdateRejection` from the repo layer

2024-08-13 09:16 UTC, felixgateru reviewed
Should a user be able to accept a rejected invitation?

2024-08-13 10:04 UTC, SammyOina commented
> Should a user be able to accept a rejected invitation?

No it should not be possible, check latest commit

2024-08-13 12:02 UTC, felixgateru requested changes

2024-08-13 12:02 UTC, felixgateru commented on invitations/service_test.go
> +		repocall2 := repo.On("Delete", context.Background(), mock.Anything, mock.Anything).Return(tc.repoErr)
I dont think this is needed

2024-08-13 12:02 UTC, felixgateru commented on invitations/service_test.go
> +		adminErr    error
I dont these are used

2024-08-13 12:02 UTC, felixgateru commented on invitations/service_test.go
> +		repocall3 := repo.On("UpdateRejection", context.Background(), mock.Anything).Return(tc.repoErr)
You can make a specific error variable to be thrown when this fails

2024-08-13 14:02 UTC, felixgateru requested changes

2024-08-13 14:02 UTC, felixgateru commented on invitations/service.go
> +	fmt.Println(inv.UserID)
Remove debug log

2024-08-13 14:10 UTC, felixgateru commented on invitations/service.go
> +	return svcerr.ErrAuthorization
Should we return the same error for accepting a rejected invitation as well as one that has already been confirmed?

2024-08-14 12:23 UTC, felixgateru approved these changes, later dismissed

2024-08-20 21:19 UTC, dborovcanin requested changes

2024-08-20 21:19 UTC, dborovcanin commented on invitations/service.go
> +	inv.UpdatedAt = time.Now()
Set `inv.UpdatedAt = inv.RejectedAt` instead of double calling `time.Now()`.

2024-08-20 21:19 UTC, dborovcanin commented on api/openapi/invitations.yml
> +        "204":
Please double-check. Accept seems to return 200 (https://github.com/SammyOina/mainflux/blob/556ffc1aa00a9bd40c477ae7086693717994f6ef/invitations/api/responses.go#L73). Either revert this or update the response to 204. While 200 is more common, 204 is the correct code here and I don't mind using it.

2024-08-20 21:19 UTC, dborovcanin commented on invitations/api/endpoint_test.go
> +			desc:        "with service error",
Either use `with` everywhere or remove it from here. While it is redundant, I prefer having it, but I leave it up to you, just stay consistent.

2024-08-20 21:19 UTC, dborovcanin commented on invitations/postgres/invitations.go
> +	dbinv := toDBInvitation(invitation)
`dbInv`

2024-09-02 11:47 UTC, dborovcanin commented
@JeffMboya Please test this one.

2024-09-02 12:41 UTC, JeffMboya commented
> @JeffMboya Please test this one.

@dborovcanin I have tested it and it works seamlessly

2024-09-02 12:41 UTC, JeffMboya submitted a review, later dismissed

2024-09-04 06:37 UTC, rodneyosodo approved these changes, later dismissed

2024-09-12 09:05 UTC, dborovcanin requested changes
We should also provide option to filter only for rejected invitations. You can do that in the next PR, but at least add a condition when listing all to exclude rejected ones by default.

2024-09-12 09:05 UTC, dborovcanin commented on invitations/api/endpoint_test.go
> +			desc:        "service error",
Use `unauthorized error` instead of service error. Also, validToken, validID, validCT - everything seems valid, but we expect AuthZ error. Tests are also documentation, take care that they are obvious and as straightforward as possible.

2024-09-12 09:05 UTC, dborovcanin commented on invitations/service_test.go
> +			desc:        "list invitations successful that have been confirmed with sdk err",
confirmed -> accepted

2024-09-12 09:05 UTC, dborovcanin commented on invitations/service_test.go
> +			desc:        "list invitations successful that have been confirmed with sdk err",
What does this even mean? Is it a successful operation or not? Can we have another scenario with just a successful list?

2024-09-12 09:28 UTC, SammyOina commented on invitations/service_test.go
> +			desc:        "list invitations successful that have been confirmed with sdk err",
there is a successful case of line 611

2024-09-12 10:24 UTC, dborovcanin commented on invitations/service_test.go
> +			desc:        "list invitations successful that have been confirmed with failed update confirmation",
Please remove SDK tests from the service tests and move them where they belong.

2024-09-12 12:45 UTC, dborovcanin approved these changes

2024-09-12 12:45 UTC, merged

2024-09-17 05:16 UTC, WashingtonKK commented on pkg/sdk/go/invitations.go
> +	_, _, sdkerr := sdk.processRequest(http.MethodDelete, url, token, data, nil, http.StatusNoContent)
This will not work since it does not match what we have on service transport layer: /post.
Please make this match what we have on transport layer.

2024-09-17 05:16 UTC, WashingtonKK commented on pkg/sdk/go/invitations.go
> +	_, _, sdkerr := sdk.processRequest(http.MethodDelete, url, token, data, nil, http.StatusNoContent)
Also update `sdk.Invitation` to contain `RejectedAt`

2024-09-17 05:16 UTC, WashingtonKK commented on pkg/sdk/go/invitations.go
> +	_, _, sdkerr := sdk.processRequest(http.MethodDelete, url, token, data, nil, http.StatusNoContent)
Please send a fix for these