MG-2441 - Add domain ID to API
absmach/magistrala pull request #2442
Opened 2024-09-24 20:47 UTC by nyagamunene

# What type of PR is this?
This is a feature because it adds the following functionality: it add domain id when passing requests in the API layer.

## What does this do?
It add domain id when passing requests in the API layer for users and things.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2441 
- Resolves #2441 

## Have you included tests for your changes?
Yes.

## Did you document any new/modified feature?
Yes

### Notes

2024-10-08 07:48 UTC, dborovcanin commented
@nyagamunene Please make sure this is ready for review today. Also, please sign off your commits.

2024-10-08 07:49 UTC, nyagamunene commented
> @nyagamunene Please make sure this is ready for review today. Also, please sign off your commits.

No problem

2024-10-18 10:16 UTC, dborovcanin requested changes
@nyagamunene Please rebase. This is to be merged before #2409.

2024-10-18 15:50 UTC, dborovcanin requested changes
Overall, looks good. Fix CI and comments and it's ready for another review. I'll also check if there is a better way to handle things in Bootstrap.

2024-10-18 15:50 UTC, dborovcanin commented on users/api/clients.go
> +			), "search_clients").ServeHTTP)
Remove duplicate handlers.

2024-10-22 08:47 UTC, arvindh123 requested changes
For Things, groups ,channels  
DomainID should be automatically decoded from URL , 
We can do that in Middleware and add to authn.Session

2024-10-22 09:03 UTC, nyagamunene commented
> For Things, groups ,channels DomainID should be automatically decoded from URL , We can do that in Middleware and add to authn.Session

Since in this PR we are just adding the domainID to URL should I make this change in the other PR?

2024-10-22 09:09 UTC, arvindh123 requested changes

2024-10-22 09:09 UTC, arvindh123 commented on users/api/requests.go
> +	if req.domainID == "" {
@nyagamunene  We have changes in  request in this PR , It is not relevant to this PR, please remove it

2024-10-22 09:11 UTC, dborovcanin commented
> > For Things, groups ,channels DomainID should be automatically decoded from URL , We can do that in Middleware and add to authn.Session
> 
> Since in this PR we are just adding the domainID to URL should I make this change in the other PR?

Since we are already breaking API, you can do it here. In the next one, you can remove the domain from the token, just like planned.

2024-10-22 11:32 UTC, arvindh123 requested changes

2024-10-22 11:32 UTC, arvindh123 commented on cmd/things/main.go
>  	})
Please undo this empty changes

2024-10-22 11:32 UTC, arvindh123 commented on consumers/notifiers/api/requests.go
> +
Please remove this empty changes , Is this due to linter?

2024-10-22 11:32 UTC, arvindh123 commented on pkg/authn/authn.go
> +func (s *Session) UpdateSession(DomainID string) {
No need of this changes function, 

Instead check and invalidate authn session to empty object , if authn session domain id is not equal to domainID 

We could not have these logic for all endpoints, it is needed only required for domains, things, groups and channels 

For users this logic is no needed logic.

2024-10-22 11:32 UTC, arvindh123 commented on certs/api/requests.go
> +	if req.domainID == "" {
Certs service doesn't have authn middleware ? Do we need token here?

2024-10-22 11:32 UTC, arvindh123 commented on bootstrap/api/requests.go
> +	if req.domainID == "" {
Bootstrap service doesn't have authn middleware ? Do we need token here?

2024-10-22 11:57 UTC, nyagamunene commented on certs/api/requests.go
> +	if req.domainID == "" {
> Certs service doesn't have authn middleware ? Do we need token here?

DomainID is needed for issuing and revoking cert

2024-10-23 15:53 UTC, arvindh123 reviewed
LGTM

2024-10-23 15:53 UTC, arvindh123 commented on internal/groups/api/requests.go
> +
remove this line

2024-10-23 17:01 UTC, dborovcanin requested changes

2024-10-23 17:01 UTC, dborovcanin commented on users/api/clients.go
> +		r.Get("/domains/{domainID}/groups/{groupID}/users", otelhttp.NewHandler(kithttp.NewServer(
There is no need for `/domains` prefix here, use `/{domainID}/groups/...`. I.e. unlike other entities, let's not prefix domain ID.

2024-10-23 17:01 UTC, dborovcanin commented on users/api/clients.go
> +		r.Get("/domains/{domainID}/groups/{groupID}/users", otelhttp.NewHandler(kithttp.NewServer(
Same for other endpoints.

2024-10-23 19:39 UTC, dborovcanin approved these changes

2024-10-23 19:40 UTC, merged