NOISSUE - Remove domain from token
absmach/magistrala pull request #2468
Opened 2024-10-14 19:37 UTC by nyagamunene

# What type of PR is this?
This is a refactor because it changes the following functionality: it removes domain from token since it is passed with the URL.

## What does this do?
It removes domain from token.

## Which issue(s) does this PR fix/relate to?

- Related Issue: N/A
- Resolves: N/A

## Have you included tests for your changes?
Yes.

## Did you document any new/modified feature?
No

### Notes

2024-10-24 13:09 UTC, arvindh123 submitted a review, later dismissed

2024-10-25 08:30 UTC, felixgateru requested changes

2024-10-25 08:30 UTC, felixgateru commented on api/openapi/invitations.yml
> +          description: Unauthorized access the domain ID.
Could you improve the grammar on this

2024-10-25 09:36 UTC, felixgateru requested changes

2024-10-25 09:36 UTC, felixgateru commented on invitations/api/transport.go
> +		token:  apiutil.ExtractBearerToken(r),
Please remove the token from this section, I dont think it is used anymore

2024-10-25 10:19 UTC, felixgateru approved these changes, later dismissed
LGTM

2024-10-25 11:05 UTC, arvindh123 approved these changes, later dismissed
CLI suggestion: (This can be done in separate PR)

We can context management to the CLI, allowing users to manage multiple sessions with `domain_id` and `token`.

 Users can:
Add a context with `mg-cli add-context <DomainID> <token> <contextName>`
List all contexts using `mg-cli list-context`
Switch contexts with `mg-cli use-context <contextName>`

This setup helps manage multiple sessions seamlessly.


LGTM

2024-10-25 11:41 UTC, dborovcanin commented
> CLI suggestion: (This can be done in separate PR)
> 
> We can add context management to the CLI, allowing users to manage multiple sessions with `domain_id` and `token`.
> 
> Users can: Add a context with `mg-cli add-context <DomainID> <token> <contextName>` List all contexts using `mg-cli list-context` Switch contexts with `mg-cli use-context <contextName>`
> 
> This setup helps manage multiple sessions seamlessly.
> 
> LGTM

I agree. I have created a reference issue. I was thinking of something similar recently, like `nats` CLI command, or even `kubectl`.

2024-10-25 12:03 UTC, dborovcanin requested changes

2024-10-25 12:03 UTC, dborovcanin commented on cli/provision.go
> +			// Create token
Remove this comment, it's obvious.

2024-10-25 12:03 UTC, dborovcanin commented on cli/users.go
> +		Use:   "token <username> <password>]",
Fix format (an extra `]`).

2024-10-25 12:03 UTC, dborovcanin commented on cli/users.go
> +		Use:   "refreshtoken <token>]",
Same.

2024-10-25 12:32 UTC, dborovcanin approved these changes

2024-10-25 12:41 UTC, merged