NOISSUE - Group service middleware into single folder
absmach/magistrala pull request #2472
Opened 2024-10-16 09:13 UTC by felixgateru

# What type of PR is this?
This is a refactor as it groups current service middleware.

## What does this do?
This pr creates the following folder structure for magistrala services:
`service`
-- `middleware`
---- `authorization.go` 
---- `logging.go`
---- `metrics.go`
---- `tracing.go`
---- `doc.go`

## Which issue(s) does this PR fix/relate to?
Noissue

## Have you included tests for your changes?
No

## Did you document any new/modified feature?
Yes changes include godoc documentation

### Notes
To be merged after #2444

2024-10-22 11:10 UTC, rodneyosodo requested changes

2024-10-22 11:10 UTC, rodneyosodo commented on cmd/postgres-reader/main.go
> +	svc = middleware.LoggingMiddleware(svc, logger)
To reduce stuttering 

```suggestion
	svc = middleware.Logging(svc, logger)
```

2025-08-07 18:36 UTC, dborovcanin commented
@felixgateru Please resolve conflicts.

2025-09-25 18:32 UTC, dborovcanin requested changes
Let's also rename factory functions to `NewLogging`,  `NewMetrics`... so we have `middleware.New<middleware type>`.

2025-09-25 18:32 UTC, dborovcanin commented on clients/middleware/doc.go
> +// to the documentation at https://docs.magistrala.abstractmachines.fr/tracing/.
This is SuperMQ, not Magistrala.

2025-09-25 18:32 UTC, dborovcanin commented on consumers/notifiers/middleware/doc.go
> +// to the documentation at https://docs.magistrala.abstractmachines.fr/tracing/.
Same, SMQ, not MG.

2025-09-25 18:32 UTC, dborovcanin commented on provision/middleware/doc.go
> +// Provision service.
Same. Check other MG references as well.

2025-09-26 09:28 UTC, dborovcanin requested changes

2025-09-26 09:28 UTC, dborovcanin commented on pkg/roles/rolemanager/middleware/logging.go
> +// NewRoleManagerLoggingMiddleware adds logging facilities to the core service.
Use the same approach: `NewLogging` (and `NewAuth` snd `NewMetric`) here, so we have something like `middlewarealias.NewLogging...`.

2025-09-26 10:04 UTC, dborovcanin requested changes

2025-09-26 10:04 UTC, dborovcanin commented on channels/middleware/authorization.go
> +	ram, err := rmMW.NewAuthorization(policies.ChannelType, svc, authz, rolesOpPerm, callout)
Avoid using mixedCaps in package aliases. Use `rolemw` here.

2025-09-26 11:54 UTC, dborovcanin approved these changes

2025-09-26 11:55 UTC, merged