MF-164 - Extract users service
absmach/magistrala pull request #248
Opened 2018-04-30 13:18 UTC by anovakovic01

**Summary:**
- Add users service
- Add HTTP API for users service
- Add gRPC API for users service
- Add logging
- Add metrics
- Add README and swagger files
- Add tests for service implementation
- Add tests for API layer

2018-04-30 20:03 UTC, mijicd reviewed
For now it looks good, I will take some more time to look it more thoroughly.

One remark though, you should (re)move manager service code that's related to the users service.

2018-04-30 21:38 UTC, drasko reviewed
Looks good, no remarks from my side.

I note however that Identity is moved to `gRPC`-only, no HTTP counterpart. This will break all other services (adapters), so they must be changed simultaneously with this PR.

2018-05-01 23:12 UTC, mijicd commented on users/README.md
> +## Usage
Eventually, we should deprecate these "single service API docs", and replace them with one, unified HTTP API doc.

2018-05-03 21:29 UTC, mijicd requested changes
Looks good. Fix these minor remarks and we can merge it. Side note: let's drop the "usage" section from individual services, and let's unify all of the individual API docs into the top-level API specification. There's not much sense into fiddling with individual service.

2018-05-03 21:29 UTC, mijicd commented on cmd/users/main.go
> +		service := grpcapi.NewService(svc)
Don't name it, it has only one usage. It is a bit confusing to have `server`, `service` and `svc`.

2018-05-03 21:29 UTC, mijicd commented on cmd/users/main.go
> +	go func() {
Since this is quite big now, i propose that you extract these snippets to non-exported functions and use `main()` just to invoke them.

2018-05-04 14:24 UTC, mijicd requested changes

2018-05-04 14:56 UTC, anovakovic01 commented on manager/postgres/channels_test.go
> +		"create new channel": {c1, false},
Currently, there are no relationships between users and channels in database. That is why this test case lost it's purpose.

2018-05-04 20:48 UTC, mijicd requested changes

2018-05-04 20:48 UTC, mijicd commented on api.go
> +type APIRes interface {
Godoc missing on methods. Rename to `Response`.

2018-05-07 07:44 UTC, mijicd approved these changes

2018-05-07 07:45 UTC, merged