MG-2048 - Authorize things with PATs
absmach/magistrala pull request #2499
Opened 2024-10-31 09:45 UTC by nyagamunene

# What type of PR is this?
This is a feature because it adds the following functionality: It adds authorization to things and users using PATs.

## What does this do?
 It adds PATs authorization to things and users middleware

## Which issue(s) does this PR fix/relate to?

- Related Issue #2048 
- Resolves #

## Have you included tests for your changes?
Yes

## Did you document any new/modified feature?
No

### Notes

2024-11-12 09:41 UTC, arvindh123 requested changes

2024-11-12 09:41 UTC, arvindh123 commented on clients/middleware/authorization.go
>  			Domain:      session.DomainID,
```suggestion
		if err := am.extAuthorize(ctx, clients.GroupOpSetChildClient, authz.PolicyReq{
```

2024-11-12 09:41 UTC, arvindh123 commented on clients/middleware/authorization.go
>  		Domain:      session.DomainID,
```suggestion
	if err := am.extAuthorize(ctx, clients.GroupOpSetChildClient, authz.PolicyReq{
		Domain:      session.DomainID,
```

2024-11-12 09:41 UTC, arvindh123 commented on internal/api/auth.go
> +			}
This can be done in auth service, During authentication process.  
Is there any reason behind this ?

2024-11-12 09:41 UTC, arvindh123 commented on internal/proto/auth/v1/auth.proto
>    rpc Authenticate(AuthNReq) returns (AuthNRes) {}
Lets have seperate RPC for PAT Authentication like PAT,

2024-11-12 09:41 UTC, arvindh123 commented on auth/api/http/pats/transport.go
> +		).ServeHTTP)
Please remove this endpoint, For now we can provide authoirzePAT via gRPC only.

2024-11-12 09:41 UTC, arvindh123 commented on auth/service.go
> +	}
Move this logic to `Authenticate` function in file `pkg/authn/authsvc/authn.go`

Lets have seperate RPC for IdentifyPAT. 

The `Authenticate` function in file `pkg/authn/authsvc/authn.go` will call IdentifyPAT base on token prefix

2024-11-12 09:41 UTC, arvindh123 commented on pkg/authn/authsvc/authn.go
>  }
Lets have seperate RPC call IdentifyPAT, move the logic to here

Something like below code 
```suggestion
	switch {
	case strings.HasPrefix(token, patPrefix+patSecretSeparator):
		res, err := a.authSvcClient.AuthenticatePAT(ctx, token)
		if err != nil {
			return authn.Session{}, errors.Wrap(errors.ErrAuthentication, err)
		}
		return authn.Session{ID: res.GetId(), UserID: res.GetUserId(), DomainID: res.GetDomainId()}, nil
	default:
		res, err := a.authSvcClient.Authenticate(ctx, &grpcAuthV1.AuthNReq{Token: token})
		if err != nil {
			return authn.Session{}, errors.Wrap(errors.ErrAuthentication, err)
		}
		return authn.Session{ID: res.GetId(), UserID: res.GetUserId(), DomainID: res.GetDomainId()}, nil
	}

```

2024-11-12 12:19 UTC, arvindh123 requested changes

2024-11-12 12:19 UTC, arvindh123 commented on users/middleware/authorization.go
Do PAT Authorization before checkAdmin or UserAuthz

2024-12-20 13:55 UTC, arvindh123 submitted a review, later dismissed

2024-12-20 16:20 UTC, dborovcanin submitted a review, later dismissed

2024-12-23 09:17 UTC, arvindh123 approved these changes, later dismissed

2024-12-30 16:40 UTC, dborovcanin approved these changes

2024-12-30 16:41 UTC, merged