MG-2358 - Add Domain to Events
absmach/magistrala pull request #2510
Opened 2024-11-06 13:34 UTC by nyagamunene

# What type of PR is this?
This is a feature because it adds the following functionality: ...

## What does this do?

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2024-12-04 11:07 UTC, dborovcanin commented
@nyagamunene Please rebase.

2025-01-11 13:21 UTC, dborovcanin requested changes
@nyagamunene Please rebase and remove Bootstrap references and send them as a new PR on the Magistrala repo.

2025-01-16 11:01 UTC, dborovcanin requested changes

2025-01-16 11:01 UTC, dborovcanin commented on apidocs/openapi/journal.yml
> +      description: Unique identifier for an entity, e.g. group, channel or client.  Used together with entity_type.
Fix type with duplicate whitespace after full stop.

2025-01-16 11:01 UTC, dborovcanin commented on channels/events/events.go
> +		"super_admin":       cce.SuperAdmin,
Do we need super admin info?

2025-01-16 11:04 UTC, felixgateru commented on channels/events/events.go
> +		"super_admin":       cce.SuperAdmin,
Arvindh had mentioned I add it. I am not yet sure where we it would be used

2025-01-16 12:13 UTC, dborovcanin approved these changes
If we find some fields unnecessary, we should remove them to reduce stress on producer, consumer, broker, and networking.

2025-01-16 12:13 UTC, merged