NOISSUE - Update CoAP docs
absmach/magistrala pull request #257
Opened 2018-05-08 16:28 UTC by dusanb94

Fix typos in cmd/coap/main.go

Signed-off-by: Dušan Borovčanin <borovcanindusan1@gmail.com>

2018-05-08 18:25 UTC, mijicd requested changes

2018-05-08 18:25 UTC, mijicd commented on docs/getting-started.md
> +Useful tools for sending CoAP messages can be found [here](https://github.com/mcollina/coap-cli) and [here](https://github.com/mkovatsc/Copper).
Put this at the beginning and name the links according to the tool names, instead of as "here".

2018-05-09 08:31 UTC, anovakovic01 requested changes

2018-05-09 08:31 UTC, anovakovic01 commented on cmd/coap/main.go
> +	logger.Info(fmt.Sprintf("CoAP adapter terminated: %s", c.Error()))
Use `Error` instead of `Info`.

2018-05-09 10:54 UTC, anovakovic01 approved these changes

2018-05-09 10:56 UTC, mijicd approved these changes

2018-05-09 10:56 UTC, merged