NOISSUE: Add roles and actions to domain listing
absmach/magistrala pull request #2571
Opened 2024-12-05 16:03 UTC by arvindh123

# What type of PR is this?
This is a feature PR , because it adds the 
-  Add roles and actions to domain listing

## What does this do?
 Add roles and actions to domain listing
 
Added new query params role_id, role_name and actions 
where actions support mutiple actions values seperated by comma
Example: ```http://localhost/domains?actions=read,write```

## Example : 
**Request :** 
```bash
curl --location 'http://localhost/domains?role_name=admin' \
--header 'Authorization: Bearer <TOKEN>'
```
**Response:**
```json
{
    "total": 2,
    "offset": 0,
    "limit": 10,
    "domains": [
        {
            "id": "6cf182f7-4b9b-46f2-bd9a-db21f04cf7d3",
            "name": "Domain 1",
            "alias": "domain_1",
            "status": "enabled",
            "role_id": "domain_BdX1tZUT8Wd2anlh7ZCVPI4f",
            "role_name": "admin",
            "actions": [
                "view_role_users",
                "add_role_users",
                "channel_add_role_users",
                "channel_connect_to_client",
                "channel_create",
                "channel_delete",
                "channel_manage_role",
                "channel_publish",
                "channel_read",
                "channel_remove_role_users",
                "channel_set_parent_group",
                "channel_subscribe",
                "channel_update",
                "channel_view_role_users",
                "client_add_role_users",
                "client_connect_to_channel",
                "client_create",
                "client_delete",
                "client_manage_role",
                "client_read",
                "client_remove_role_users",
                "client_set_parent_group",
                "client_update",
                "client_view_role_users",
                "delete",
                "disable",
                "enable",
                "group_add_role_users",
                "group_create",
                "group_delete",
                "group_manage_role",
                "group_membership",
                "group_read",
                "group_remove_role_users",
                "group_set_child",
                "group_set_parent",
                "group_update",
                "group_view_role_users",
                "manage_role",
                "membership",
                "read",
                "remove_role_users",
                "update"
            ],
            "created_by": "25bd6559-1830-4234-8784-32b3110077d8",
            "created_at": "2024-12-05T08:14:55.010844Z",
            "updated_by": "ebff0d2c-a02c-400c-a44c-42803cfad38a",
            "updated_at": "2024-12-05T08:50:19.22145Z"
        },
        {
            "id": "38083857-58fa-4cb2-b8c5-66d9b3eadae5",
            "name": "Domain 11",
            "alias": "domain_11",
            "status": "enabled",
            "role_id": "domain_cLN9re3Y3tetX7IlRfPBmqVr",
            "role_name": "admin",
            "actions": [
                "add_role_users",
                "channel_add_role_users",
                "channel_connect_to_client",
                "channel_create",
                "channel_delete",
                "channel_manage_role",
                "channel_publish",
                "channel_read",
                "channel_remove_role_users",
                "channel_set_parent_group",
                "channel_subscribe",
                "channel_update",
                "channel_view_role_users",
                "client_add_role_users",
                "client_connect_to_channel",
                "client_create",
                "client_delete",
                "client_manage_role",
                "client_read",
                "client_remove_role_users",
                "client_set_parent_group",
                "client_update",
                "client_view_role_users",
                "delete",
                "disable",
                "enable",
                "group_add_role_users",
                "group_create",
                "group_delete",
                "group_manage_role",
                "group_membership",
                "group_read",
                "group_remove_role_users",
                "group_set_child",
                "group_set_parent",
                "group_update",
                "group_view_role_users",
                "manage_role",
                "membership",
                "read",
                "remove_role_users",
                "update",
                "view_role_users"
            ],
            "created_by": "ebff0d2c-a02c-400c-a44c-42803cfad38a",
            "created_at": "2024-12-05T09:00:42.352388Z",
            "updated_at": "0001-01-01T00:00:00Z"
        }
    ]
}
````

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2024-12-06 09:06 UTC, dborovcanin approved these changes, later dismissed

2024-12-06 09:06 UTC, dborovcanin commented on cmd/domains/main.go
> +func availableActionsAndBuiltInRoles(spicedbSchemaFile string) ([]roles.Action, map[roles.BuiltInRoleName][]roles.Action, error) {
Rename to `listRoles` since that's what we are doing here. Actions are part of role.

2024-12-06 09:06 UTC, dborovcanin commented on domains/service_test.go
> +	ds, _ := domains.New(drepo, policy, idProvider, sidProvider, availableActions, builtInRoles)
Please fix the linter's compile error remark.

2024-12-06 09:57 UTC, felixgateru requested changes

2024-12-06 09:57 UTC, felixgateru commented on domains/api/http/decode.go
> +		dir:      dir,
I dont think `oder` and `dir` are used

2024-12-06 09:57 UTC, felixgateru commented on domains/postgres/domains.go
> +	fmt.Printf("%+v\n", dbPage)
Remove debug log

2024-12-06 11:44 UTC, arvindh123 commented on domains/api/http/decode.go
> +		dir:      dir,
Added order and direction to repo

2024-12-06 12:48 UTC, felixgateru approved these changes
LGTM

2024-12-06 13:02 UTC, ianmuchyri approved these changes

2024-12-10 18:25 UTC, dborovcanin approved these changes

2024-12-10 18:25 UTC, merged