NOISSUE: Change Role Name to Role ID
absmach/magistrala pull request #2612
Opened 2024-12-20 18:42 UTC by arvindh123

# What type of PR is this?
This is a feature because it adds the following functionality: 
Change from Role Name to Role ID

## What does this do?

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2024-12-23 08:18 UTC, felixgateru requested changes

2024-12-23 08:18 UTC, felixgateru commented on api/http/util/errors.go
> +	// ErrMissingRoleID indicates that role name are empty.
```suggestion
	// ErrMissingRoleID indicates that role id is empty.
```

2024-12-23 11:37 UTC, felixgateru reviewed
We will need to update the api docs for this change

2024-12-23 13:31 UTC, arvindh123 commented
This PR is depend on  https://github.com/absmach/supermq/pull/2585

2024-12-25 13:24 UTC, dborovcanin approved these changes

2024-12-25 13:25 UTC, merged