NOISSUE - Update Docker compose
absmach/magistrala pull request #274
Opened 2018-05-12 00:05 UTC by dusanb94

2018-05-12 08:15 UTC, mijicd requested changes

2018-05-12 08:15 UTC, mijicd commented on http/swagger.yaml
> +        401:
This is wrong and misleading. 401 should be thrown exclusively on missing credentials (token). Permissions issues should be taken care via 403. Please review the other API docs as well.

2018-05-12 08:15 UTC, mijicd commented on docker/docker-compose.yml
> +      on-failure
Nitpick: remove linebreak: `restart: on-failure`.

2018-05-12 08:15 UTC, mijicd commented on docker/docker-compose.yml
> +    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
Please drop this and spawn 2 DB containers.

2018-05-13 10:57 UTC, nmarcetic submitted a review, later dismissed

2018-05-13 10:57 UTC, nmarcetic commented on docker/nginx.conf
> +        proxy_pass http://http-adapter:8185/;
Remove this `/` at the end.

2018-05-13 10:57 UTC, nmarcetic commented on docker/docker-compose.yml
> +    depends_on:
No deps to `clients-db`  ?

2018-05-13 10:57 UTC, nmarcetic commented on docker/docker-compose.yml
> +
No deps to `users-db` ?

2018-05-14 11:10 UTC, mijicd approved these changes

2018-05-14 11:11 UTC, merged