MF-282 - Rename clients to things in Dashflux
absmach/magistrala pull request #289
Opened 2018-05-17 14:55 UTC by dusanb94

This pull request resolves #282.

2018-05-21 15:51 UTC, nmarcetic requested changes

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/app.module.ts
>  import { MockClientsService } from './core/services/mock-clients.service';
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/components/channels/add-channel-dialog/add-channel-dialog.component.html
> +            <mat-option *ngFor="let client of clientsStore.things" [value]="client">{{client.name}}</mat-option>
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/components/channels/add-channel-dialog/add-channel-dialog.component.spec.ts
> +import { ThingsService } from '../../../core/services/clients/clients.service';
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/components/channels/add-channel-dialog/add-channel-dialog.component.ts
> +    public clientsStore: ThingsStore,
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/components/channels/channels.component.spec.ts
> +import { ThingsService } from '../../core/services/clients/clients.service';
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/components/channels/channels.component.ts
> +    public clientsStore: ThingsStore,
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/components/channels/channels.component.ts
> +    this.clientsStore.getThings();
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/components/things/add-thing-dialog/add-thing-dialog.component.spec.ts
> +import { ThingsService } from '../../../core/services/clients/clients.service';
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/components/things/things.component.spec.ts
> +import { ThingsService } from '../../core/services/clients/clients.service';
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/components/things/things.component.ts
> +  clients: Observable<Thing[]>;
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/core/services/channels/channels.service.ts
>    getClientsToDelete(channelFormData: Channel, channel: Channel) {
Rename this and all above.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/core/services/mock-clients.service.ts
> +const MOCK_CLIENTS = [
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/core/services/mock-clients.service.ts
>        return Observable.of(MOCK_CLIENTS).delay(1000);
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/core/services/mock-clients.service.ts
> +    MOCK_CLIENTS.push(thing);
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/core/store/auth.store.spec.ts
> +import { ThingsService } from '../services/clients/clients.service';
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/core/store/things.store.spec.ts
> +import { ThingsService } from '../services/clients/clients.service';
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/core/store/things.store.ts
> +import { ThingsService } from '../services/clients/clients.service';
Rename.

2018-05-21 15:51 UTC, nmarcetic commented on dashflux/src/app/core/store/ui.store.spec.ts
> +import { ThingsService } from '../services/clients/clients.service';
Rename.

2018-05-24 10:17 UTC, closed without merging

2018-05-24 10:35 UTC, dusanb94 commented
This PR is moved to #305.