MF-269 - Replace UUID with BIGSERIAL as primary key
absmach/magistrala pull request #291
Opened 2018-05-20 18:59 UTC by mijicd

This pull request resolves #269.

**Summary:**
- dropped CoAP (incompatible API, poor library support, no tests)
- replaced UUID with `BIGSERIAL` (`uint64`) as things and channels primary key
- propagated these changes through protobuf schemas

2018-05-20 22:40 UTC, drasko submitted a review, later dismissed

2018-05-20 22:40 UTC, drasko commented on things/api/http/requests_test.go
> +		"invalid thing ID":           {thing, 0, key, things.ErrNotFound},
Why `wrong` constant is not used here, and it is in many other places in tests? It would increase code self-documentation.

2018-05-21 08:40 UTC, dusanb94 commented on docs/getting-started.md
> -
Should MQTT docs be removed?

2018-05-21 08:48 UTC, dborovcanin submitted a review, later dismissed
LGTM!

2018-05-21 09:45 UTC, anovakovic01 requested changes

2018-05-21 09:45 UTC, anovakovic01 commented on http/api/endpoint_test.go
> +		"publish message with invalid authorization token": {id, msg, contentType, invalidToken, http.StatusForbidden},
Maybe add test case `publish message to non-existent channel`?

2018-05-21 10:49 UTC, anovakovic01 approved these changes
LGTM!

2018-05-21 10:51 UTC, merged