MF-296 - Create docker-compose with InfluxDB and Grafana
absmach/magistrala pull request #306
Opened 2018-05-25 10:59 UTC by dusanb94

This pull request resolves #296.

Signed-off-by: Dušan Borovčanin <dusan.borovcanin@mainflux.com>

2018-05-28 10:26 UTC, nmarcetic commented
@dusanb94  Do you think its better to keep this composition on service/docker level instead of root docker level ? Just curious if it can be confusing to peoples. @drasko @anovakovic01 ?

2018-05-28 10:48 UTC, anovakovic01 requested changes
@nmarcetic I don't see any problem with docker-compose path, as it can be treated as addon.

2018-05-28 10:48 UTC, anovakovic01 commented on writers/influxdb/README.md
> +Docker compose file is available in ./docker/docker-compose.yml. Besides database
Could you please change this path to be relative to project root?

2018-05-28 10:48 UTC, anovakovic01 commented on writers/influxdb/docker/docker-compose.yml
> +      MF_INFLUXDB_WRITER_PORT: 8900
Don't forget to remove DB from env variable name.

2018-05-28 10:48 UTC, anovakovic01 commented on writers/influxdb/docker/docker-compose.yml
> +    image: grafana/grafana:master
Could you specify Grafana version?

2018-05-28 10:54 UTC, dusanb94 commented
@nmarcetic This compose file is really about InfluxDB and its integration with Grafana, so it made sense for me to put it in service docker level.

2018-05-28 10:57 UTC, drasko commented
@nmarcetic we have one generic Dockerfile that builds docker images for all services depending on parameters passed by Makefile: https://github.com/mainflux/mainflux/blob/master/docker/Dockerfile

I think this one should be in a separated, more generic, dir, as it is now.

`docker-compose` also uses external configs (`nginx.conf`) and certs, so this one also better live in separate dir, not with every service.

2018-05-28 10:58 UTC, drasko commented
@dusanb94 nope, please move it to `docker` dir and call it `docker-compose-influxdb-grafana.yaml`

2018-05-28 11:12 UTC, anovakovic01 commented
@drasko Let him at least place it in `docker/influxdb-grafana/docker-compose.yml`. We don't need complex docker-compose file name. Also, Makefile doesn't use only one generic Dockerfile. It uses Dockerfiles from `mqtt` and `dashflux`.

2018-05-28 11:17 UTC, nmarcetic commented on writers/influxdb/docker/docker-compose.yml
> +    image: grafana/grafana:master
Agree @dusanb94 Please use latest.

2018-05-28 11:17 UTC, nmarcetic commented
@anovakovic01 @dusanb94 I understand now and YES I agree it makes sense more to keep it on service level.

2018-05-28 12:53 UTC, anovakovic01 submitted a review, later dismissed

2018-05-30 10:29 UTC, nmarcetic submitted a review, later dismissed
LGTM!

2018-05-30 16:52 UTC, drasko submitted a review, later dismissed
LGTM

2018-05-30 16:52 UTC, drasko commented
@dusanb94 please update branch so we can merge it.

2018-05-31 10:44 UTC, anovakovic01 requested changes

2018-05-31 10:44 UTC, anovakovic01 commented on docker/addons/influxdb/docker-compose.yml
> +      MF_INFLUXDB_POINT: messages
Update this env var name.

2018-06-01 09:17 UTC, anovakovic01 approved these changes
LGTM!

2018-06-01 09:20 UTC, nmarcetic approved these changes

2018-06-01 09:20 UTC, merged