NOISSUE - Rename path veriables in InfluxDB wirter
absmach/magistrala pull request #315
Opened 2018-05-28 10:43 UTC by dusanb94

Signed-off-by: Dušan Borovčanin <dusan.borovcanin@mainflux.com>

2018-05-28 10:54 UTC, anovakovic01 requested changes

2018-05-28 10:54 UTC, anovakovic01 commented on cmd/influxdb/main.go
> +	"github.com/nats-io/go-nats"
Please return `nats` alias. I think that improves readability (You don't need to open files from `github.com/nats-io/go-nats` to see package name).

2018-05-28 10:54 UTC, anovakovic01 commented on writers/influxdb/README.md
Add run command, same as in other `README` files.

2018-05-28 19:22 UTC, drasko requested changes

2018-05-30 12:42 UTC, anovakovic01 approved these changes
LGTM!

2018-05-30 13:27 UTC, nmarcetic approved these changes

2018-05-30 13:37 UTC, drasko approved these changes
LGTM

2018-05-31 10:28 UTC, merged