NOISSUE - Update Copyright Notice
absmach/magistrala pull request #39
Opened 2023-11-12 20:31 UTC by rodneyosodo

### What does this do?
Add CI check for non-go files to check that the files contain a license

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
N/A

2023-11-14 08:06 UTC, SammyOina approved these changes

2023-11-14 09:24 UTC, dborovcanin reviewed
Can [Goheader linter](https://golangci-lint.run/usage/linters/#goheader) be used for this?

2023-11-14 09:31 UTC, rodneyosodo commented
Goheader only does it for go files.

2023-11-14 10:54 UTC, dborovcanin requested changes

2023-11-14 10:54 UTC, dborovcanin commented on .github/workflows/check-license.yaml
> +          fi
Can we simplify a bit and log the failed file, something like:
```bash
ff=$(grep -rcL --exclude-dir=.git --exclude-dir=build \
            --exclude='*.{crt,key,pem,zed,hcl,md,json,csv,mod,sum,tmpl,args}' \
            --exclude={CODEOWNERS,LICENSE,MAINTAINERS} \
            --regexp "Copyright (c) Abstract Machines" . | head -n 1)

if [ "$ff" ]; then
    echo "License header check failed on file: $ff"
    exit 1
fi
```

2023-11-14 12:10 UTC, dborovcanin approved these changes

2023-11-16 15:16 UTC, ianmuchyri approved these changes

2023-11-17 11:08 UTC, dborovcanin requested changes
Update headers for Domains in SDK and CLI.

2023-11-17 11:37 UTC, dborovcanin approved these changes

2023-11-17 11:37 UTC, merged