NOISSUE - Influxdb batch add
absmach/magistrala pull request #394
Opened 2018-09-14 14:24 UTC by dusanb94

**Summary:**
Add batch write to InfluxDB writer. Since the official Go InfluxDB client currently supports only batch point add, batch size is increased in order to improve performance. Batch size, as well as the time interval for flushing the batch, can be configured using corresponding env variables.

2018-09-17 19:33 UTC, drasko submitted a review, later dismissed
LGTM

2018-09-18 16:54 UTC, ghost submitted a review, later dismissed
LGTM

2018-09-18 17:29 UTC, nmarcetic commented
@dusanb94 Please sync branch

2018-09-19 07:26 UTC, drasko submitted a review, later dismissed
LGTM

2018-09-19 08:47 UTC, anovakovic01 requested changes

2018-09-19 08:47 UTC, anovakovic01 commented on writers/influxdb/README.md
> +docker-compose -f docker/addons/influxdb/docker-compose.yml up -d
Shouldn't it be `docker-compose -f docker/addons/influxdb-writer/docker-compose.yml up -d`?

2018-09-19 08:47 UTC, anovakovic01 commented on writers/influxdb/README.md
> +_Please note that you need to start core services before additional ones. Since all services need to be in the same network and writer services are dependent of core, you need to start core services
`dependent on core`

2018-09-19 08:47 UTC, anovakovic01 commented on writers/influxdb/messages.go
> +	bp, _ := influxdata.NewBatchPoints(repo.cfg)
Handle error.

2018-09-19 10:14 UTC, anovakovic01 commented on writers/influxdb/messages_test.go
> +	time.Sleep(saveTimeout)
@dusanb94 Can we avoid this somehow?

2018-09-21 17:09 UTC, drasko requested changes

2018-09-21 17:09 UTC, drasko commented on writers/influxdb/messages.go
> +	return nil
Should not this one reset the timeout timer also? I.e. if we had more writes than a batchsize we should write immediately, and then rest the timeout to start collecting a batch for a next second.

2018-09-22 23:52 UTC, drasko approved these changes
LGTM

2018-09-22 23:53 UTC, merged