MF-389 - Add documentation for Writers and Readers
absmach/magistrala pull request #398
Opened 2018-09-18 22:52 UTC by blokovi

2018-09-19 20:59 UTC, drasko requested changes
Very good doc here @blokovi. Just a few minor remarks from my side.

2018-09-19 20:59 UTC, drasko commented on docs/getting-started.md
> +## ADDONS
Why is this allcap? Not consistent with other headlines.

2018-09-19 20:59 UTC, drasko commented on writers/influxdb/README.md
> +Docker compose file is available in <project_root>/docker/addons/influxdb-writer/docker-compose.yml. Besides database
Use backticks to verbatim-format the code.

2018-09-19 21:51 UTC, drasko submitted a review, later dismissed
LGTM

2018-09-20 13:19 UTC, drasko approved these changes
LGTM

2018-09-20 13:32 UTC, nmarcetic approved these changes

2018-09-20 13:32 UTC, merged