MF-374 - Bring back CoAP adapter
absmach/magistrala pull request #413
Opened 2018-10-02 15:06 UTC by dusanb94

This pull request resolves #374.

2018-10-07 19:26 UTC, drasko submitted a review, later dismissed
Please add copyright headers. Otherwise looks good.

2018-10-08 08:04 UTC, anovakovic01 requested changes
@dusanb94 Good job! I left some small remarks for you to resolve, but generally, this looks great.

2018-10-08 08:04 UTC, anovakovic01 commented on coap/api/transport.go
> +	http.ListenAndServe(port, b)
You should make two handlers: `HTTP` and `CoAP`, and handle this `ListenAndServe` part in `main`.

2018-10-08 08:04 UTC, anovakovic01 commented on coap/nats/broker.go
> +const prefix = "channel"
First declare constants, then vars.

2018-10-08 08:04 UTC, anovakovic01 commented on coap/api/transport.go
> +func NotFoundHandler(l *net.UDPConn, a *net.UDPAddr, m *gocoap.Message) *gocoap.Message {
As far as I can tell, there is no need for this to be public.

2018-10-17 15:01 UTC, manuio requested changes

2018-10-26 16:45 UTC, manuio requested changes

2018-10-27 00:52 UTC, drasko submitted a review, later dismissed
LGTM

2018-10-27 00:53 UTC, drasko commented
@dusanb94 this looks good. Please resolve remarks from @anovakovic01 and @manuIO and let's merge this one.

2018-10-27 07:11 UTC, anovakovic01 commented on coap/api/transport.go
> +	timestamp = int64(time.Millisecond) * 31
@manuIO This rule is applicable only to public constants, because of easier docs search (this one is private, so it won't be in go docs).

2018-10-27 07:14 UTC, anovakovic01 commented on coap/api/logging.go
> +	}(time.Now())
I see that API has changed so this one is resolved.

2018-10-27 16:49 UTC, manuIO commented on coap/api/transport.go
> +	timestamp = int64(time.Millisecond) * 31
But why not change this?

2018-10-28 02:59 UTC, drasko submitted a review, later dismissed
LGTM

2018-10-29 11:03 UTC, anovakovic01 requested changes

2018-10-29 11:03 UTC, anovakovic01 commented on coap/api/util.go
> +)
`import "strings"`

2018-10-29 11:03 UTC, anovakovic01 commented on coap/api/util.go
> +const keyHeader = "key"
Maybe this should be called `authorization` like in other protocol adapter.

2018-10-29 14:22 UTC, manuio submitted a review, later dismissed
LGTM

2018-10-31 17:35 UTC, manuio approved these changes

2018-10-31 17:53 UTC, anovakovic01 approved these changes

2018-10-31 17:53 UTC, merged