NOISSUES: Domains SDK
absmach/magistrala pull request #45
Opened 2023-11-14 12:17 UTC by arvindh123

Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
- Provides SDK for Domains

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-11-16 15:11 UTC, ianmuchyri requested changes

2023-11-16 15:11 UTC, ianmuchyri commented on cmd/test/main.go
> +package main
remove test file from cmd

2023-11-16 15:11 UTC, ianmuchyri commented on cli/domains.go
> +	},
we need a cli function for list user's domains

2023-11-16 15:59 UTC, arvindh123 commented on cli/domains.go
> +	},
Added in users

2023-11-16 15:59 UTC, arvindh123 commented on cmd/test/main.go
> +package main
removed

2023-11-16 16:30 UTC, ianmuchyri commented on pkg/sdk/go/sdk.go
> +	// AddUserToDomain add user to a domain.
```suggestion
	// AddUserToDomain adds a user to a domain.
```

2023-11-16 16:30 UTC, ianmuchyri commented on pkg/sdk/go/sdk.go
> +	// RemoveUserFromDomain remove user from a domain.
```suggestion
	// RemoveUserFromDomain removes a user from a domain.
```

2023-11-16 16:30 UTC, ianmuchyri commented on pkg/sdk/go/sdk.go
> +	// DisableDomain changes the status of the domain to disable.
```suggestion
	// DisableDomain changes the status of the domain to disabled.
```

2023-11-16 16:32 UTC, dborovcanin requested changes

2023-11-16 16:32 UTC, dborovcanin commented on cli/domains.go
> +		Long:  `Domains management: create, update, retrieve domains , assign / unassign users to domains and list users of domain"`,
`assign/unassign`

2023-11-16 16:32 UTC, dborovcanin commented on pkg/sdk/go/domains.go
> +	do := Domain{}
```GO
var d Domain
```

2023-11-16 16:32 UTC, dborovcanin commented on pkg/sdk/go/domains.go
> +	up := UsersPage{}
The same, `var up UserPage`, same for other variable declarations.

2023-11-16 17:18 UTC, ianmuchyri approved these changes

2023-11-17 10:42 UTC, dborovcanin approved these changes

2023-11-17 10:42 UTC, merged