MF-454 - Use message Time field as a time for InfluxDB points
absmach/magistrala pull request #455
Opened 2018-11-09 17:52 UTC by dusanb94

Signed-off-by: Dusan Borovcanin <dusan.borovcanin@mainflux.com>

### What does this do?
Use time from received message to set time value in InfluxDB.  

### Which issue(s) does this PR fix/relate to?
This pull request closes #454.

### Notes
This pull request slightly modifies the way messages are saved in InfluxDB. Field "Time" is removed and replaced by default "time" column of InfluxDB. Previously, "time" kept information about timestamp when the message is saved in the database, so that info is no longer persistent in InfluxDB. However, this information can be found in service logs if needed. This also means that the size of tag set of the single point is slightly reduced.

2018-11-09 20:32 UTC, drasko requested changes
As discussed in the issue - tagset is wrong.

This tagset will form huge number of different series. Only `channelID` and eventually `content-type` should be in a tagset.

2018-11-13 17:51 UTC, drasko submitted a review, later dismissed
LGTM

2018-11-16 09:25 UTC, nmarcetic submitted a review, later dismissed

2018-11-16 10:25 UTC, nmarcetic submitted a review, later dismissed

2018-11-18 15:42 UTC, drasko approved these changes
LGTM

2018-11-18 15:42 UTC, merged