MF-467 - Make CoAP ping period configurable
absmach/magistrala pull request #469
Opened 2018-11-26 16:15 UTC by dusanb94

Signed-off-by: Dusan Borovcanin <dusan.borovcanin@mainflux.com>

### What does this do?
This PR makes CoAP adapter ping period configurable.

### Which issue(s) does this PR fix/relate to?
Closes #467.

### Have you included tests for your changes?
No. Test will be included as a part of the Adapter tests.

### Did you document any new/modified functionality?
Yes.

2018-11-26 16:19 UTC, drasko submitted a review, later dismissed
LGTM

2018-11-26 20:21 UTC, anovakovic01 requested changes

2018-11-26 20:21 UTC, anovakovic01 commented on cmd/coap/main.go
> +		log.Fatalf("Invalid value passed for %s\n", envPingPeriod)
Why not using mainflux logger?

2018-11-26 20:21 UTC, anovakovic01 commented on cmd/coap/main.go
> +		log.Fatalf("Value of %s must be between 1 and 24", envPingPeriod)
Same here.

2018-11-27 12:53 UTC, anovakovic01 approved these changes

2018-11-27 13:02 UTC, drasko approved these changes
LGTM

2018-11-27 13:02 UTC, merged