NOISSUE - Move CLI documentation from getting started guide to separate page
absmach/magistrala pull request #470
Opened 2018-11-26 16:32 UTC by blokovi

Signed-off-by: Ivan Milošević <iva@blokovi.com>

### What does this do?

Move CLI documentation from getting started guide to separate page

### Which issue(s) does this PR fix/relate to?
No issue

2018-11-26 16:33 UTC, drasko submitted a review, later dismissed
LGTM

2018-11-26 20:15 UTC, anovakovic01 requested changes

2018-11-26 20:15 UTC, anovakovic01 commented on docs/cli.md
> +./mainflux-cli things get <thing_id> --offset=1 --limit=5 <user_auth_token>
`offset` and `limit` don't make sense when thing ID is passed.

2018-11-26 20:15 UTC, anovakovic01 commented on docs/cli.md
> +./mainflux-cli channels get <channel_id> --offset=1 --limit=5 <user_auth_token>
`offset` and `limit` don't make sense when channel ID is passed.

2018-11-26 20:35 UTC, drasko approved these changes
LGTM

2018-11-27 07:26 UTC, anovakovic01 approved these changes

2018-11-27 07:40 UTC, merged