Limit user to have single relation with things, groups, channels and domains
absmach/magistrala pull request #48
Opened 2023-11-15 12:21 UTC by arvindh123

Signed-off-by: Arvindh <arvindh91@gmail.com>

Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
- Limit user to have single relation with things, groups, channels and domains

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-11-22 15:46 UTC, rodneyosodo requested changes

2023-11-22 15:46 UTC, rodneyosodo commented on auth/spicedb/policies.go
> +	// user should not any relation with group
grammar. Should user have or have not?

2023-11-23 13:39 UTC, ianmuchyri commented on auth/spicedb/policies.go
> +	// user should not any relation with thing
same here, `user should not have any relation with thing`

2023-11-23 13:44 UTC, arvindh123 commented on auth/spicedb/policies.go
> +	// user should not any relation with group
done

2023-11-23 13:44 UTC, arvindh123 commented on auth/spicedb/policies.go
> +	// user should not any relation with thing
done

2023-11-24 12:56 UTC, ianmuchyri approved these changes

2023-11-24 13:17 UTC, rodneyosodo approved these changes
LGTM

2023-11-27 09:56 UTC, dborovcanin approved these changes

2023-11-27 09:57 UTC, merged