MF-513 - Add Bootstrapping service
absmach/magistrala pull request #524
Opened 2018-12-24 00:56 UTC by dusanb94

### What does this do?
This pull request introduces Bootstrapping service.
### Which issue(s) does this PR fix/relate to?
This pull request resolves #513.

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
Yes.

2018-12-26 15:29 UTC, drasko submitted a review, later dismissed
LGTM

2018-12-27 11:36 UTC, anovakovic01 requested changes

2018-12-27 11:36 UTC, anovakovic01 commented on bootstrap/api/requests.go
> +	Channels    []string `json:"mainflux_channels"`
Remove `mainflux` prefix, I think that you don't need it (correct me if I'm wrong).

2018-12-27 11:36 UTC, anovakovic01 commented on bootstrap/configs.go
> +)
First define `const`, then `type` and then `func`, it's easier to follow, and also, reader of this code will be more interested in predefined values, than in implementation details.

2018-12-27 11:36 UTC, anovakovic01 commented on bootstrap/postgres/configs.go
> +		if err = rows.Scan(&c.MFThing, &c.MFKey, pq.Array(&c.MFChannels), &c.ExternalID, &c.ExternalKey, &content, &c.State); err != nil {
Please break this in two lines, I think that this `scan` part is too long.

2018-12-27 11:36 UTC, anovakovic01 commented on bootstrap/postgres/configs.go
> +	if err := cr.db.QueryRow(q, thing.MFThing, thing.Owner, thing.MFKey, pq.Array(thing.MFChannels), thing.ExternalID, thing.ExternalKey,
Please break this into two lines, this `queryrow` part is too long.

2018-12-27 11:36 UTC, anovakovic01 commented on bootstrap/postgres/configs.go
> +	if err := cr.db.QueryRow(q, externalKey, externalID).Scan(&config.MFThing, &config.Owner, &config.MFKey, pq.Array(&config.MFChannels), &content, &config.State); err != nil {
Same here, please break.

2018-12-27 11:36 UTC, anovakovic01 commented on bootstrap/postgres/init.go
> +                        content  		  TEXT,
Can you fix alignment in this file?

2018-12-27 11:36 UTC, anovakovic01 commented on bootstrap/service.go
> +func (bs bootstrapService) Update(key string, thing Config) error {
This function is really long, can you break it into multiple private functions (if there are more than one logical step)?

2018-12-27 11:36 UTC, anovakovic01 commented on cmd/bootstrap/main.go
> +	} else {
You can use `return` and remove `else`.

2018-12-30 13:54 UTC, chombium reviewed
All the endpoints which are exposed by the bootstrap service are general by their naming but are also things exclusive. Do we want to leave the `/bootstrap`, `/configs` and '/unknown' endpoints to be exclusively for things operations of we want to make the enpoints  `/things/bootstrap`, `/things/configs` and '/things/unknown' or `/bootstrap/things`, `/configs/things` and '/unknown/things', so that we leave a bit of space for eventual api upgrades and service extension to cover configuration of other Mainflux entities as well?

The other thing that bothers me is the "unknown" table name and the endpoint... /unknown... unknown what?I think that we must be more specific..

2018-12-30 13:54 UTC, chombium commented on bootstrap/postgres/init.go
> +					"DROP TABLE things",
Drop table unknown is missing here

2019-01-09 14:18 UTC, drasko submitted a review, later dismissed
LGTM

2019-01-09 14:32 UTC, drasko approved these changes
LGTM

2019-01-09 14:42 UTC, anovakovic01 approved these changes
LGTM!

2019-01-09 14:42 UTC, merged