NOISSUE - Fix event sourcing client on LoRa adapter
absmach/magistrala pull request #527
Opened 2018-12-27 23:58 UTC by anovakovic01

Fixes event sourcing client on LoRa adapter. Client was missing events because it couldn't create user group. This was a known issue and it's fixed with new SDK method for creating consumer group. Now we use method that creates empty stream if stream doesn't already exist.

2018-12-28 00:08 UTC, drasko requested changes

2018-12-28 00:08 UTC, drasko commented on lora/redis/streams.go
> +			if err != nil && err != errMetadataType {
What happens if `err != nil` and it is not `errMetadataType` (but some other kind of error)? We do not log this at all?

2018-12-28 08:12 UTC, anovakovic01 commented on lora/redis/streams.go
> +			if err != nil && err != errMetadataType {
Yes, we log only that case (case that you just asked about, where error is not `errMetadataType`), and we don't need to log `errMetadataType`, because this means that event is of no interest for our service.

2018-12-28 08:15 UTC, manuio submitted a review, later dismissed
LGTM

2018-12-28 08:38 UTC, drasko submitted a review, later dismissed
LGTM

2018-12-28 09:09 UTC, manuio submitted a review, later dismissed

2019-01-03 15:05 UTC, manuio approved these changes

2019-01-08 01:54 UTC, drasko approved these changes
LGTM

2019-01-08 01:54 UTC, merged