Add lora doc to getting-started.md
absmach/magistrala pull request #529
Opened 2018-12-28 17:45 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

2018-12-29 21:16 UTC, anovakovic01 requested changes

2018-12-29 21:16 UTC, anovakovic01 commented on docs/getting-started.md
> + - **Create a Device:** Then you can create a Device. To must configure the `network session key` and `application session key` of your Device. You can generate and copy them on your device configura
`...and set them using UI.`

2018-12-29 21:16 UTC, anovakovic01 commented on docs/getting-started.md
> + This service uses RedisDB to create a route map between both systems. As in Mainflux we use Channels to connect Things, LoRa Serser uses Applications to connect Devices. Route map create a mapping o
Fix `LoRa Server`, also `Route map creates a mapping of...`. Fix fourth sentence `Lora-adapter uses metadata from provisioning events emitted by...`

2018-12-29 21:16 UTC, anovakovic01 commented on docs/getting-started.md
> + To receive Lora messages the lora-adapter subscribes to the topic `applications/+/devices/+` of the LoRa Server. The [LoRa-Gateways-Bridge](https://www.loraserver.io/lora-gateway-bridge/overview) us
`LoRa-Gateway-Bridge`. `The lora-adapter verifies the applicationID and...`.

2018-12-30 14:00 UTC, drasko submitted a review, later dismissed
LGTM

2018-12-30 23:43 UTC, anovakovic01 approved these changes
LGTM!

2018-12-31 15:00 UTC, anovakovic01 submitted a review, later dismissed
LGTM!

2019-01-08 01:57 UTC, drasko approved these changes
LGTM

2019-01-08 11:25 UTC, anovakovic01 approved these changes
LGTM!

2019-01-08 11:25 UTC, merged