-
absmach/magistrala pull request #534
Opened 2019-01-04 15:24 UTC by juanmagal

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2019-01-04 17:07 UTC, dborovcanin requested changes
@juanmagal Thanks for your contribution. Can you, please, read the aforementioned [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file and follow the instructions for sending pull requests? You need to add an appropriate PR title (check contribution guide and PR template for naming recommendations), a short explanation of what is the purpose of this PR, and sign off all the commits.

2019-01-05 13:19 UTC, chombium requested changes
Hi @juanmagal,

At first thanks and congratulations on sending the first PR to Mainflux as a new contributor. I really like that you've found a possible enhancement and you've start working on it. I also must agree with @dusanb94 and we'll have to help you to clean up the PR before the changes get merged.

I would generally suggest that you:
1. Clean up your commits and get rid of the merge request commits (check the [contribution guide](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md), you should use `git pull --rebase upstream master`

2. You have to sign off  your commits. `git commit -s...`
3. You've copied most of the config files from the docker and k8s folders in the helm folder. This way there is a huge overhead of keeping the files in sync and as the configuration grows, this will turn out in to a maintenance nightmare. The right way to go is to keep the configuration files where they are, so that each of them is a single source of truth and to adjust the helm template (yes I know that it will more complex) :)

@mainflux/contributors this PR refers to #388 

HTH,
Jovan
P.S. keep up the good work

2019-01-05 13:19 UTC, chombium commented on k8s/mainflux/users.yml
> +  minReplicas: 1
always cleanup the files after testing ;)

2019-01-05 17:06 UTC, juanmagal commented
Hi,

 I am sorry, I pushed the button and didn't want to, so please disregard my
request. I will provide the correct changes once they are ready and they
follow the contribution instructions.

 My apologies for the inconveniences.

Best regards,

Juanma


El vie., 4 ene. 2019 18:07, Dušan Borovčanin <notifications@github.com>
escribió:

> *@dusanb94* requested changes on this pull request.
>
> @juanmagal <https://github.com/juanmagal> Thanks for your contribution.
> Can you, please, read the aforementioned CONTRIBUTING.md
> <https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md> file
> and follow the instructions for sending pull requests? You need to add an
> appropriate PR title (check contribution guide and PR template for naming
> recommendations), a short explanation of what is the purpose of this PR,
> and sign off all the commits.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mainflux/mainflux/pull/534#pullrequestreview-189449420>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AM-qCTIcQvlMIUeU9kIbfytLC7eyCT14ks5u_4pcgaJpZM4Zp1Ho>
> .
>

2019-01-05 18:34 UTC, chombium commented
@juanmagal no worries, take all the time you need, to finish the PR.
We don't need to renect the PR, I've added the "work in progress" label to it, so that we know that it's not finished.

Happy hacking

2019-01-07 12:16 UTC, manuio commented
@juanmagal Please, edit the name of the PR. Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.

2019-01-08 01:53 UTC, drasko commented
@juanmagal as @manuio pointed out - can you please edit title and description of this PR?

2019-01-08 14:53 UTC, closed without merging

2019-01-08 14:54 UTC, juanmagal commented
This pull request was open by mistake, once it is ready I will open a new one. I'm sorry for the inconveniences.