NOISSUE - Add name field for Bootstrap Config
absmach/magistrala pull request #564
Opened 2019-01-30 18:19 UTC by dusanb94

### What does this do?
This PR adds a `name` field to the Bootstrap service Config data model. This field represents the human-readable name of Configuration and is not required. Bootstrap service supports case-insensitive, partial-match searching over this field.

### List any changes that modify/break current functionality
There should be no such changes.

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
Yes, API docs are updated.

2019-02-01 14:59 UTC, manuio requested changes

2019-02-01 14:59 UTC, manuio commented on bootstrap/api/endpoint.go
> +				res.Configs = append(res.Configs, unknownRes{ExternalID: cfg.ExternalID, ExternalKey: cfg.ExternalKey})
fix the tabulation

2019-02-01 14:59 UTC, manuio commented on bootstrap/api/endpoint_test.go
> +			url:    fmt.Sprintf("%s/configs?offset=%d&limit=%d&name=%s", bs.URL, 0, 100, "95"),
can you create const for this values?

2019-02-01 14:59 UTC, manuio commented on bootstrap/mocks/configs.go
> +			if (state == -1 || v.State == state) && (name == "" || strings.Index(strings.ToLower(v.Name), name) != -1) && v.Owner == key {
Maybe you can split this checks

2019-02-01 14:59 UTC, manuio commented on bootstrap/service_test.go
> +			config: saved[95:96],
Maybe use const here also

2019-02-01 14:59 UTC, manuio commented on bootstrap/service_test.go
> +			limit:  100,
and here

2019-02-02 23:24 UTC, drasko requested changes

2019-02-03 08:11 UTC, manuio commented on bootstrap/service_test.go
> +			config: saved[95:96],
@drasko that's why the "maybe"

2019-02-04 08:56 UTC, dusanb94 commented on bootstrap/api/endpoint.go
> +				res.Configs = append(res.Configs, unknownRes{ExternalID: cfg.ExternalID, ExternalKey: cfg.ExternalKey})
Tabulation is fine here.

2019-02-04 09:03 UTC, dusanb94 commented
@manuio All literals that are not extracted to `const` are test specific or test-case specific, so it's OK to keep it this way.

2019-02-04 11:41 UTC, manuio requested changes

2019-02-04 11:41 UTC, manuio commented on bootstrap/api/endpoint.go
> +				res.Configs = append(res.Configs, unknownRes{ExternalID: cfg.ExternalID, ExternalKey: cfg.ExternalKey})
No, in the same file you did it right:
```
channels = append(channels, channelRes{
	ID:       ch.ID,
	Name:     ch.Name,
	Metadata: ch.Metadata,
})
```

2019-02-04 11:41 UTC, manuio commented on bootstrap/api/transport.go
> +	ret := bootstrap.Filter{FullMatch: make(map[string]string), PartialMatch: make(map[string]string)}
same here

2019-02-04 11:41 UTC, manuio commented on bootstrap/postgres/configs.go
> +		c := dbChannel{ID: ch.ID, Name: ch.Name, Metadata: ch.Metadata}
and here

2019-02-04 15:55 UTC, manuio submitted a review, later dismissed
LGTM

2019-02-06 09:18 UTC, drasko approved these changes
LGTM

2019-02-06 09:28 UTC, anovakovic01 approved these changes
LGTM!

2019-02-06 09:28 UTC, merged