NOISSUE: add subtopic support on http adapter
absmach/magistrala pull request #592
Opened 2019-02-12 13:56 UTC by beres

### What does this do?
The patch add subtopic support for http-adapter

### Which issue(s) does this PR fix/relate to?

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2019-02-12 14:13 UTC, beres commented
The same approach can be used for ws/coap adapters, so the regexp could be exported in a more generic place, topics.go? What do you think?

2019-02-12 19:30 UTC, drasko requested changes

2019-02-12 19:30 UTC, drasko commented on http/api/transport.go
> +	channelPartRegExp = regexp.MustCompile(`^/channels/(?P<channelId>[\w\-]+)/messages(?P<subTopics>/.+[^/])*$`)
Use `chanID` instead of `channelId` to stay Go-idiomatic.

2019-02-12 19:30 UTC, drasko commented on http/api/transport.go
> +func authorize(r *http.Request, channelId string) (string, error) {
`chanID`

2019-02-12 19:30 UTC, drasko commented on http/api/transport.go
> +	id, err := auth.CanAccess(ctx, &mainflux.AccessReq{Token: apiKey, ChanID: channelId})
`chanID`

2019-02-14 12:31 UTC, drasko commented
Related to https://github.com/mainflux/mainflux/issues/596 - @beres can you take this one? It's not trivial :)

2019-03-12 12:34 UTC, nmarcetic commented
Duplicate #642

2019-03-12 12:34 UTC, closed without merging