MF-597 - Removed legacy code as not needed anymore
absmach/magistrala pull request #598
Opened 2019-02-14 12:55 UTC by mteodor

Signed-off-by: mteodor <mirko.teodorovic@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Removed legacy code as not needed anymore

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2019-02-14 13:00 UTC, drasko requested changes

2019-02-14 13:00 UTC, drasko commented on docker/Dockerfile
> -    && apk add make protobuf git \
Will `make` exist in the container if you do not install it?

2019-02-14 13:13 UTC, drasko requested changes

2019-02-14 13:13 UTC, drasko commented on docker/Dockerfile
> +    && apk add make  git \
Is `git` needed? There is an extra space betreen `make` and `git`

2019-02-14 14:10 UTC, drasko approved these changes
LGTM

2019-02-15 17:35 UTC, nmarcetic approved these changes

2019-02-15 17:35 UTC, merged