MF-552 - Use event sourcing to keep Bootstrap service in sync with Things service
absmach/magistrala pull request #603
Opened 2019-02-18 16:32 UTC by dusanb94

### What does this do?
This PR adds the use of event sourcing from Things service to keep corresponding Bootstrap service entities in sync.

### Which issue(s) does this PR fix/relate to?
This PR resolves #552.

### List any changes that modify/break current functionality
There are 2 major API changes:
    - List of Configs does not return Channels
    - Update Config is split to Config fields change and Config connections

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
Yes, docs are up to date.

2019-02-18 16:39 UTC, drasko submitted a review, later dismissed
LGTM

2019-02-22 09:02 UTC, manuio submitted a review, later dismissed

2019-02-25 21:54 UTC, drasko submitted a review, later dismissed
LGTM

2019-02-25 22:19 UTC, manuio submitted a review, later dismissed

2019-02-28 16:42 UTC, anovakovic01 requested changes

2019-02-28 16:42 UTC, anovakovic01 commented on bootstrap/api/endpoint_test.go
> +		if err != io.EOF {
Inline.

2019-02-28 16:42 UTC, anovakovic01 commented on bootstrap/api/logging.go
> +		message := fmt.Sprintf("Method removeConfig for config %s took %s to complete", id, time.Since(begin))
Same here.

2019-02-28 16:42 UTC, anovakovic01 commented on bootstrap/api/logging.go
> +		message := fmt.Sprintf("Method updateChannel for channel %s took %s to complete", channel.ID, time.Since(begin))
Same here.

2019-02-28 16:42 UTC, anovakovic01 commented on bootstrap/postgres/configs.go
> +		if err = rows.Scan(&c.ID, &c.Name, &c.Metadata); err != nil {
Use `:=`.

2019-02-28 16:42 UTC, anovakovic01 commented on bootstrap/postgres/configs.go
> +		if err = rows.Scan(&c.ID, &c.Name, &c.Metadata); err != nil {
Use `:=`.

2019-02-28 16:42 UTC, anovakovic01 commented on bootstrap/postgres/configs.go
> +	if err = insertChannels(key, channels, tx); err != nil {
Use `:=`.

2019-02-28 16:42 UTC, anovakovic01 commented on bootstrap/postgres/configs.go
> +	if err = updateConnections(key, id, connections, tx); err != nil {
Use `:=`.

2019-02-28 16:42 UTC, anovakovic01 commented on bootstrap/postgres/configs.go
> +		if err = rows.Scan(&ch.ID, &ch.Name, &ch.Metadata); err != nil {
Use `:=`.

2019-03-03 03:01 UTC, drasko requested changes

2019-03-04 16:11 UTC, anovakovic01 approved these changes
LGTM!

2019-03-04 16:40 UTC, drasko approved these changes
LGTM

2019-03-04 16:41 UTC, merged