Remove logout button and add logout header
absmach/magistrala pull request #604
Opened 2019-02-18 18:12 UTC by darkodraskovic

This code contains also minor code optimizations.

2019-02-18 20:14 UTC, drasko requested changes

2019-02-18 20:14 UTC, drasko commented on ui/src/User.elm
> +        -- div [ id "loggedIn" ]
Remove dead code.

2019-02-19 17:52 UTC, blokovi approved these changes
LGTM

2019-02-19 18:03 UTC, drasko approved these changes
LGTM

2019-02-19 18:10 UTC, merged