MG-35 - Improve CI speed by using self-hosted agent
absmach/magistrala pull request #61
Opened 2023-11-17 08:49 UTC by Musilah

### What does this do?
Improve CI speed by setting up a Github Actions Runner
### Which issue(s) does this PR fix/relate to?
Resolves #35 

### List any changes that modify/break current functionality
None
### Have you included tests for your changes?
None
### Did you document any new/modified functionality?
No
### Notes

2023-11-20 12:18 UTC, WashingtonKK commented on .github/workflows/ci.yml
> +          path: ./bin/golangci-lint
``
```suggestion
          path: ./bin
```

2023-11-21 13:47 UTC, rodneyosodo requested changes

2023-11-21 13:47 UTC, rodneyosodo commented on auth.pb.go
> +// 	protoc        v4.24.3
Revert

2023-11-21 13:47 UTC, rodneyosodo commented on .github/workflows/golangci-lint.yml
> +
This doesn't need to be in a separate file. You can just combine them

2023-11-21 13:47 UTC, rodneyosodo commented on .github/workflows/ci.yml
> +      - MG-35-self-hostrunner
no need for this at the moment. It should be on push to main or on pull request to main

2023-11-21 13:47 UTC, rodneyosodo commented on .github/workflows/ci.yml
> +      - name: Setup Codecov
Why not use official action by `codecov` https://github.com/codecov/codecov-action ?

2023-11-21 13:47 UTC, rodneyosodo commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-20.04
This ubuntu version is pretty old use `ubuntu-latest`

2023-11-21 16:37 UTC, dborovcanin requested changes
Since all the services are very similar, can we use a matrix with the service list instead of having repeated sections per service?

2023-11-23 09:31 UTC, dborovcanin requested changes
We also need to trigger actions if GH Actions files change (such as proto update or other changes in the Actions file).

2023-11-23 11:24 UTC, arvindh123 commented on .github/workflows/ci.yml
> +          done
This looks good, May be this command `find . -name "*.pb.go"` will help you get all `*.pb.go` in repo in single step

2023-11-27 09:00 UTC, dborovcanin requested changes

2023-11-27 09:00 UTC, dborovcanin commented on .github/workflows/ci.yml
> +          DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB }}
Also, can the whole Docker push be a part added to the matrix, so we don't have to repeat it for all the services?

2023-11-28 08:24 UTC, rodneyosodo requested changes

2023-11-28 08:24 UTC, rodneyosodo commented on .github/workflows/build.yml
> +name: Build and Publish Docker Image
What is the difference between this and `cd` ?

2023-11-28 09:09 UTC, Musilah commented on .github/workflows/build.yml
> +name: Build and Publish Docker Image
ah im supposed to delete it. apologies

2023-11-28 14:21 UTC, merged