MF-539 - Improve Bootstrap Service documentation
absmach/magistrala pull request #646
Opened 2019-03-13 16:19 UTC by dusanb94

### What does this do?
This pull request updates Bootstrap service documentation.

### Which issue(s) does this PR fix/relate to?
This PR resolves #539.

### List any changes that modify/break current functionality
There are documented minor API changes. Enabling/disabling uses `PUT` and `DELETE` HTTP requests, respectively.

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
Yes, this pull request is all about documenting.

2019-03-14 15:50 UTC, drasko requested changes

2019-03-14 15:50 UTC, drasko commented on docs/bootstrap.md
> +
Add architecture diagram and show where Bootstrap Service sits in the system.

2019-03-14 15:50 UTC, drasko commented on docs/bootstrap.md
> +
Something similar to this: https://medium.com/@vrmvrm/device-key-distribution-with-lightweight-m2m-36cdc12e5711

2019-03-14 15:50 UTC, drasko commented on docs/bootstrap.md
> +
Also - exmplain difference between Bootstrap and ordinary provisioning.

2019-03-15 17:32 UTC, drasko submitted a review, later dismissed
LGTM

2019-03-15 17:34 UTC, nmarcetic submitted a review, later dismissed

2019-03-15 18:10 UTC, nmarcetic approved these changes

2019-03-15 18:11 UTC, drasko approved these changes
LGTM

2019-03-15 18:11 UTC, merged