NOISSUES: List user permissions on entities
absmach/magistrala pull request #66
Opened 2023-11-20 13:30 UTC by arvindh123

Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
- In list entities request, adds permissions in response
- grpc endpoint to list permission between subject and object

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-11-20 13:37 UTC, arvindh123 commented on auth/api/grpc/client.go
> +	// 	SubjectRelation: lp.SubjectRelation,
@dborovcanin , @rodneyosodo 
Commented code is used in other functions , but instead of this type cast directly we can cast to grpc type
Why we are casting to local struct instead of grpc type

2023-11-21 08:47 UTC, rodneyosodo requested changes
Come to think of it we are kind of reinventing the wheel. This is why graphql was born. We are adding 2 states to a single REST endpoint i.e clients and permissions and this shouldn't be the case

2023-11-21 08:47 UTC, rodneyosodo commented on auth.proto
> +}
Add new line

2023-11-21 08:47 UTC, rodneyosodo commented on auth/api/grpc/endpoint.go
> +		_ = req
No need for this

2023-11-21 08:47 UTC, rodneyosodo commented on auth/spicedb/policies.go
> +
remove empty space

2023-11-21 08:47 UTC, rodneyosodo commented on things/service.go
> +		resultChan := make(chan error, len(tp.Clients))
You can use https://pkg.go.dev/golang.org/x/sync/errgroup instead

2023-11-22 08:49 UTC, arvindh123 commented on things/service.go
> +		resultChan := make(chan error, len(tp.Clients))
Done

2023-11-22 08:50 UTC, arvindh123 commented on auth/api/grpc/endpoint.go
> +		_ = req
removed

2023-11-22 08:50 UTC, arvindh123 commented on auth.proto
> +}
Added

2023-11-22 13:41 UTC, rodneyosodo requested changes

2023-11-23 11:45 UTC, arvindh123 commented on internal/api/common.go
> +	ListPerms        = "list_perms"
Already we are using query param 'permissions' for filtering permissions.

2023-11-24 13:21 UTC, ianmuchyri commented
@arvindh123  We will need to provision for `getPermissions `in the sdk, so as to use it in the UI

2023-11-28 14:50 UTC, arvindh123 commented
> @arvindh123 We will need to provision for `getPermissions `in the sdk, so as to use it in the UI

SDK added PR in #76

2023-11-29 11:36 UTC, dborovcanin approved these changes

2023-11-29 11:40 UTC, merged