MF-687 - Add event sourcing to Bootstrap service
absmach/magistrala pull request #695
Opened 2019-04-05 14:11 UTC by dusanb94

### What does this do?
This pull request adds events for CRUD and bootstrap action to the Bootstrap service.

### Which issue(s) does this PR fix/relate to?
This pull request resolves #687.

### List any changes that modify/break current functionality
There are no such changes.

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
No.

2019-04-06 11:18 UTC, nmarcetic submitted a review, later dismissed

2019-04-06 13:00 UTC, anovakovic01 requested changes

2019-04-08 12:01 UTC, drasko approved these changes
LGTM

2019-04-08 14:55 UTC, ghost approved these changes

2019-04-08 15:45 UTC, anovakovic01 approved these changes
LGTM!

2019-04-08 15:46 UTC, merged