NOISSUE - Replace repeating code by card gen func
absmach/magistrala pull request #697
Opened 2019-04-08 12:22 UTC by darkodraskovic

Signed-off-by: Darko Draskovic <darko.draskovic@gmail.com>

### What does this do?

Replaces repeating code in Connection and Message module by a helper func.

2019-04-08 15:50 UTC, drasko requested changes

2019-04-08 15:50 UTC, drasko commented on ui/README.md
> +you can install `elm-live` (https://github.com/wking-io/elm-live) and execute
Use Markdown links

2019-04-08 17:13 UTC, blokovi submitted a review, later dismissed
LGTM

2019-04-09 13:16 UTC, drasko submitted a review, later dismissed
LGTM

2019-04-09 14:06 UTC, blokovi approved these changes
LGTM

2019-04-09 14:21 UTC, drasko approved these changes
LGTM

2019-04-09 14:21 UTC, merged