MF-488 - Remove Thing type (app or device)
absmach/magistrala pull request #718
Opened 2019-04-17 19:19 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

2019-04-18 16:32 UTC, anovakovic01 requested changes

2019-04-18 16:32 UTC, anovakovic01 commented on docs/getting-started.md
> +This proves that messages have been well send through the system, via protocol adapter (`mainflux-http`) and `normalizer` service which corectly parsed messages.
`correctly`

2019-04-18 16:32 UTC, anovakovic01 commented on things/api/http/endpoint_test.go
> +	thing   = things.Thing{ Name: "test_app", Metadata: map[string]interface{}{"test": "data"}}
Remove extra space in front of `Name:`.

2019-04-18 16:59 UTC, anovakovic01 reviewed
@manuio You'll have to remove `type` from UI too. :)

2019-04-18 18:42 UTC, manuio commented
@anovakovic01 sure :) I'm starting right now

2019-04-18 18:43 UTC, manuio commented on docs/getting-started.md
> +This proves that messages have been well send through the system, via protocol adapter (`mainflux-http`) and `normalizer` service which corectly parsed messages.
thanks

2019-04-18 18:43 UTC, manuio commented on things/api/http/endpoint_test.go
> +	thing   = things.Thing{ Name: "test_app", Metadata: map[string]interface{}{"test": "data"}}
thanks

2019-04-19 15:06 UTC, drasko submitted a review, later dismissed
LGTM

2019-04-19 16:26 UTC, dborovcanin reviewed
Please check these files as well:
https://github.com/mainflux/mainflux/blob/master/things/README.md#things (remove `(i.e. devices & applications)` part)
https://github.com/mainflux/mainflux/blob/master/docs/dev-guide.md#thing-create-event and https://github.com/mainflux/mainflux/blob/master/docs/dev-guide.md#thing-create-event (remove `type` field from event examples)

Great job, @manuio.

2019-04-19 16:26 UTC, dusanb94 commented on sdk/go/things_test.go
> +			desc:     "create new epmty thing",
Typo: `epmty`.

2019-04-19 20:31 UTC, drasko approved these changes
LGTM

2019-04-19 21:22 UTC, dborovcanin approved these changes

2019-04-20 10:17 UTC, anovakovic01 approved these changes
LGTM!

2019-04-20 12:09 UTC, merged