Add basic websocket support
absmach/magistrala pull request #721
Opened 2019-04-18 17:05 UTC by darkodraskovic

Signed-off-by: Darko Draskovic <darko.draskovic@gmail.com>

Adds websocket support for sending messages.

2019-04-20 23:42 UTC, drasko requested changes

2019-04-20 23:42 UTC, drasko commented on ui/src/Env.elm
> +      url = "http://localhost:80/"
Shouldn't the URL be emptyy for this to work in docker?

2019-04-21 00:12 UTC, drasko approved these changes
LGTM

2019-04-21 00:15 UTC, blokovi approved these changes
LGTM

2019-04-21 00:40 UTC, merged