MF-525 - Add pagination response to the readers
absmach/magistrala pull request #729
Opened 2019-04-23 15:01 UTC by anovakovic01

### What does this do?
Adds pagination response for every reader.

### Which issue(s) does this PR fix/relate to?
Resolves #525.

### List any changes that modify/break current functionality
Readers response has now pagination metadata.

### Have you included tests for your changes?
Yes, I've updated existing tests.

### Did you document any new/modified functionality?
I've updated swagger docs.

2019-04-23 15:34 UTC, manuio requested changes

2019-04-23 15:34 UTC, manuio commented on readers/influxdb/messages.go
> +	fmt.Println(resp.Results[0].Series[0].Columns)
remove this please

2019-04-23 15:41 UTC, nmarcetic submitted a review, later dismissed

2019-04-23 15:41 UTC, anovakovic01 commented on readers/influxdb/messages.go
> +	fmt.Println(resp.Results[0].Series[0].Columns)
@manuio good catch, thanks

2019-04-23 15:47 UTC, nmarcetic approved these changes

2019-04-23 15:56 UTC, manuio approved these changes

2019-04-24 22:18 UTC, drasko approved these changes
LGTM

2019-04-24 22:18 UTC, merged