NOISSUE - Fix domains bug and feature to disable user self register
absmach/magistrala pull request #74
Opened 2023-11-22 15:41 UTC by arvindh123

Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
- Fix: Update Nginx entrypoint.sh file shebang
- Fix: Include membership users by default in listing domain users , added permission=membership as default query params for domain users listing (#60)
- Fix: Resolve conflict when creating identical thing names, thing keys, and group names in different domains (#55)
- Add: Implement a feature to disable user self-registration; users can only be added by a super admin

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)
Resolves #60, Resolves #55

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-11-22 15:50 UTC, rodneyosodo requested changes

2023-11-22 15:50 UTC, rodneyosodo commented on users/service.go
> +		return "", errors.Wrap(errors.ErrAuthentication, err)
This creates a duplicate since Identify returns `errors.ErrAuthentication`

2023-11-23 06:30 UTC, arvindh123 commented on users/service.go
> +		return "", errors.Wrap(errors.ErrAuthentication, err)
`svc.auth.Identify` returns rpc errors , so `api.EncodeError` could not able to encode error and returns `500` error
Regrading rpc errors raised issue here #50

2023-11-23 08:43 UTC, rodneyosodo approved these changes
LGTM

2023-11-23 13:35 UTC, ianmuchyri approved these changes

2023-11-24 12:43 UTC, ianmuchyri commented
@arvindh123 when I try listing entities who's list is empty it returns an error instead of an empty list

`2023-11-24 15:42:26 {"level":"warn","message":"Method list_things using token eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJkb21haW4iOiI1Y2Q3NDhkNy1iZjFmLTRjYTktYjEwYy00ZmZlM2Y0Mzc5YmEiLCJleHAiOjE3MDA4MzMxNTIsImlhdCI6MTcwMDgyOTU1MiwiaXNzIjoibWFnaXN0cmFsYS5hdXRoIiwic3ViIjoiYzIxN2NlYWYtOTJkYy00YmI1LWFlNDgtM2RjZjI3NTU5MzhkIiwidHlwZSI6MCwidXNlciI6ImMyMTdjZWFmLTkyZGMtNGJiNS1hZTQ4LTNkY2YyNzU1OTM4ZCJ9.M-swDOOUblSrryn3gAZmyYLW5p5EvXKgxWDYHCR4JQKKT7VBfA9nk7W8nxLw0SEHVTw90kIrq2AzuRz3gDqCdQ took 6.221668ms to complete with error: entity not found : entity not found : rpc error: code = Internal desc = entity not found.","ts":"2023-11-24T12:42:26.601743534Z"}`

2023-11-27 15:09 UTC, dborovcanin commented on auth/postgres/domains.go
> +	if pm.SubjectID == "" {
Please add a comment explaining this approach.

2023-11-27 17:33 UTC, dborovcanin approved these changes

2023-11-27 17:33 UTC, merged