NOISSUE - Add certificate fields to the Bootstrap service
absmach/magistrala pull request #752
Opened 2019-05-20 17:19 UTC by dusanb94

### What does this do?
This pull request adds cert-related fields to Bootstrap service.

### List any changes that modify/break current functionality
None of the existing features is modified.

### Have you included tests for your changes?
Not at the moment. I'll update pull request description as I update the code and tests.

### Did you document any new/modified functionality?
No, I'll update it as I remove `draft` status.

2019-05-21 17:59 UTC, drasko submitted a review, later dismissed
LGTM

2019-05-22 15:18 UTC, nmarcetic submitted a review, later dismissed

2019-05-22 16:42 UTC, manuio requested changes

2019-05-22 16:42 UTC, manuio commented on bootstrap/postgres/configs_test.go
> +			certKey: "crtKey",
`certKey`

2019-05-22 16:42 UTC, manuio commented on bootstrap/postgres/configs_test.go
> +			certKey: "crtKey",
certKey

2019-05-22 17:07 UTC, drasko submitted a review, later dismissed
LGTM

2019-05-22 17:11 UTC, manuio submitted a review, later dismissed

2019-05-22 17:51 UTC, nmarcetic submitted a review, later dismissed

2019-05-22 21:14 UTC, nmarcetic approved these changes

2019-05-22 21:21 UTC, manuio approved these changes

2019-05-22 21:22 UTC, merged