NOISSUE - Add searchable Channels name
absmach/magistrala pull request #754
Opened 2019-05-30 14:38 UTC by manuio

2019-06-10 15:12 UTC, anovakovic01 requested changes

2019-06-10 15:12 UTC, anovakovic01 commented on things/api/http/responses.go
> +	Name   string `json:"name"`
Why do you return the name in the response?

2019-06-10 15:12 UTC, anovakovic01 commented on things/postgres/channels_test.go
> +			desc: "create thing with invalid name",
`channel`, not `thing`

2019-06-10 15:12 UTC, anovakovic01 commented on things/service_test.go
> +		"list with existent name": {
existing

2019-06-10 21:21 UTC, anovakovic01 approved these changes
LGTM!

2019-06-11 00:12 UTC, drasko approved these changes
LGTM

2019-06-11 08:37 UTC, merged