NOISSUE - Fix Update user roles, Listing and retrieve users with role
absmach/magistrala pull request #76
Opened 2023-11-23 16:33 UTC by arvindh123

Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
- Fix : Update user role and  Listing and retrieve users with role 

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-11-24 12:26 UTC, ianmuchyri requested changes

2023-11-24 12:26 UTC, ianmuchyri commented on api/openapi/users.yml
>        description: JSON-formated document describing the owner of user to be update
```suggestion
      description: JSON-formated document describing the role of the user to be update
```

2023-11-27 14:30 UTC, ianmuchyri requested changes
In sdk.go change `UpdateUserOwner` to `UpdateUserRole`

2023-11-27 14:41 UTC, ianmuchyri commented
> In sdk.go change `UpdateUserOwner` to `UpdateUserRole`

also update in `users_tests.go`

2023-11-29 10:37 UTC, arvindh123 commented
> UpdateUserOwner

Fixed in https://github.com/absmach/magistrala/pull/49

2023-11-29 12:28 UTC, dborovcanin commented on api/openapi/users.yml
> +      description: JSON-formated document describing the role of the user to be update
@arvindh123 Please address this one.

2023-11-29 12:54 UTC, dborovcanin approved these changes

2023-11-29 12:54 UTC, merged