MF-757 - Add support for explicit content type
absmach/magistrala pull request #771
Opened 2019-06-27 09:38 UTC by anovakovic01

### What does this do?
Adds support for custom content type and format.
### Which issue(s) does this PR fix/relate to?
Resolves #757.

### Have you included tests for your changes?
No.

### Did you document any new/modified functionality?
Yes, I've updated the Messaging section.

2019-06-27 13:41 UTC, drasko requested changes
Looks good. Just misses some comments in my opinion.

2019-06-27 13:41 UTC, drasko commented on mqtt/mqtt.js
> +            contentType = elements[elements.length - 2].replace('_', '/').replace('-', '+');
Please put some comments in this whole block. I can see what you are doing, but it might not be so easy for the newcomers.

2019-06-27 13:41 UTC, drasko commented on version.go
> +	// Service contains service name.
Nice!

2019-07-10 06:17 UTC, dborovcanin submitted a review, later dismissed

2019-07-19 10:28 UTC, anovakovic01 commented on mqtt/mqtt.js
> +    formats = {
Good catch! Fixed!

2019-07-19 10:32 UTC, dborovcanin submitted a review, later dismissed

2019-07-19 10:34 UTC, dborovcanin submitted a review, later dismissed

2019-07-22 15:10 UTC, drasko submitted a review, later dismissed
LGTM

2019-07-24 16:18 UTC, nmarcetic submitted a review, later dismissed

2019-07-24 17:05 UTC, nmarcetic approved these changes

2019-07-24 17:32 UTC, drasko approved these changes
LGTM

2019-07-25 00:22 UTC, merged