MF-792 - Users service not working in offline mode
absmach/magistrala pull request #795
Opened 2019-07-18 15:30 UTC by anovakovic01

### What does this do?
Enables `users` service to work in an offline mode.

### Which issue(s) does this PR fix/relate to?
Resolves #792.

### List any changes that modify/break current functionality
There are no such changes.

### Have you included tests for your changes?
There are already tests written for this validation.

### Did you document any new/modified functionality?
There is no new functionality.

### Notes

2019-07-18 17:01 UTC, nmarcetic approved these changes

2019-07-19 10:27 UTC, dborovcanin approved these changes

2019-07-19 10:28 UTC, merged

2019-07-19 11:08 UTC, chombium requested changes
We should definitely change the validation, as others are also having [problems](https://github.com/asaskevich/govalidator/issues/337). But the validation function should be adjusted.

2019-07-19 11:08 UTC, chombium commented on users/users.go
> +	userRegexp    = regexp.MustCompile("^[a-zA-Z0-9!#$%&'*+/=?^_`{|}~.-]+$")
The email user (the local part) and the host (the domain part) can also have non ASCII UTF-8 characters. These  regex expressions will make them invalid.

Do we want to enable email addresses which have UTF-8 characters as well?

2019-07-19 11:37 UTC, anovakovic01 commented on users/users.go
> +	if len(email) < 6 || len(email) > 254 {
@chombium these are all valid points, but I think that this should be handled in a separate PR.  I recommend that you write an issue for these validation improvements. This code was just a quick bug fix, so this code is from `govalidator` lib.

2019-07-19 11:40 UTC, chombium commented on users/users.go
> +	if len(email) < 6 || len(email) > 254 {
@anovakovic01 I've opened a new issue already #798 ;)