NOISSUE - Add rungw command to Makefile
absmach/magistrala pull request #805
Opened 2019-07-24 10:34 UTC by blokovi

Add `make rungw` command to run mainflux without jaeger
Add name to jaeger container

Signed-off-by: Ivan Milošević <iva@blokovi.com>

### What does this do?

Add new `make rungw` command that will start docker composition of all core Mainflux services expect open tracing (mainflux-jeager). It's supposed to help running Mainflux on edge

### Which issue(s) does this PR fix/relate to?
No issue

2019-07-24 10:39 UTC, nmarcetic submitted a review, later dismissed

2019-07-24 10:44 UTC, manuio submitted a review, later dismissed

2019-07-24 13:38 UTC, nmarcetic submitted a review, later dismissed

2019-07-24 13:40 UTC, nmarcetic submitted a review, later dismissed

2019-07-24 16:22 UTC, mteodor submitted a review, later dismissed

2019-07-25 00:23 UTC, drasko approved these changes
LGTM

2019-07-25 00:24 UTC, drasko requested changes

2019-07-25 00:24 UTC, drasko commented on Makefile
> +rungw:
Can you please just add a comment what we are doing here and why.

2019-07-25 10:24 UTC, nmarcetic approved these changes

2019-07-25 10:30 UTC, mteodor approved these changes

2019-07-25 11:08 UTC, manuio approved these changes

2019-07-25 15:24 UTC, drasko approved these changes
LGTM

2019-07-25 15:24 UTC, merged