NOISSUE - Fix building UI docker image for arm
absmach/magistrala pull request #806
Opened 2019-07-24 10:36 UTC by blokovi

Add entrypoint in arm Dockerfile
Switch from ash to dash in entrypoint script

Signed-off-by: Ivan Milošević <iva@blokovi.com>

### What does this do?
Fix building of UI docker image for arm architecture

### Which issue(s) does this PR fix/relate to?
No issue

2019-07-24 10:38 UTC, nmarcetic submitted a review, later dismissed

2019-07-24 10:44 UTC, manuio submitted a review, later dismissed

2019-07-24 13:37 UTC, nmarcetic submitted a review, later dismissed

2019-07-24 16:19 UTC, mteodor submitted a review, later dismissed

2019-07-25 00:25 UTC, drasko submitted a review, later dismissed
I will approve, but this should be simplified. I let @nmarcetic do the research and correct this implementation.

2019-07-25 10:23 UTC, nmarcetic submitted a review, later dismissed

2019-07-25 11:08 UTC, manuio requested changes

2019-07-25 11:08 UTC, manuio commented on ui/docker/Dockerfile.arm
> +ENTRYPOINT ["/entrypoint.sh"]
maybe a new line here?

2019-07-25 11:33 UTC, blokovi commented on ui/docker/Dockerfile.arm
> +ENTRYPOINT ["/entrypoint.sh"]
added

2019-07-25 12:05 UTC, manuio approved these changes
LGTM

2019-07-25 15:14 UTC, nmarcetic approved these changes

2019-07-25 15:15 UTC, merged