Updated Readme
absmach/magistrala pull request #808
Opened 2019-07-24 13:22 UTC by nmarcetic

Signed-off-by: nmarcetic <n.marcetic86@gmail.com>

### What does this do?
Updates README file.

2019-07-24 16:25 UTC, blokovi submitted a review, later dismissed

2019-07-24 17:34 UTC, drasko requested changes

2019-07-24 17:34 UTC, drasko commented on README.md
> +- Platform logging and instrumentation support (Grafana, Prometheus, Opentracing)
Should be `OpenTracing`

2019-07-25 10:27 UTC, blokovi submitted a review, later dismissed

2019-07-25 10:27 UTC, anovakovic01 submitted a review, later dismissed
LGTM!

2019-07-25 11:10 UTC, manuio requested changes

2019-07-25 11:10 UTC, manuio commented on README.md
> +- Message persistence (Cassandra, InfluxDB MongoDB and PostgresSQL)
There is a `,` missing between InfluxDB and MongoDB

2019-07-25 11:10 UTC, manuio commented on README.md
> +- Platform logging and instrumentation support (Grafana, Prometheus, OpenTracing)
Maybe better `Prometheus and OpenTracing)`

2019-07-25 15:21 UTC, anovakovic01 approved these changes
LGTM!

2019-07-25 15:23 UTC, drasko commented on README.md
> +- Platform logging and instrumentation support (Grafana, Prometheus and OpenTracing)
Maybe add Fluentd and ElasticSearch?

2019-07-25 15:23 UTC, drasko commented on README.md
> +- Platform logging and instrumentation support (Grafana, Prometheus and OpenTracing)
Maybe add CockroachDB and ScyllaDB?

2019-07-25 16:08 UTC, manuio approved these changes

2019-07-25 17:20 UTC, drasko approved these changes
LGTM

2019-07-25 17:20 UTC, merged