NOISSUE - Add VerneMQ support
absmach/magistrala pull request #809
Opened 2019-07-27 22:02 UTC by drasko

Signed-off-by: drasko <drasko.draskovic@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Adds support for [VerneMQ](https://github.com/vernemq/vernemq), to be used as an alternative MQTT adapter, instead of [Aedes](https://github.com/mcollina/aedes)

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes

2019-07-30 18:49 UTC, anovakovic01 requested changes

2019-07-30 18:49 UTC, anovakovic01 commented on mqtt/verne/src/mfx_auth.erl
> +    [{cnanel_id, ChannelId}, {content_type, ContentType}, {nats_subject, NatsSubject}] = parseTopic(Topic),
Fix typo `cnanel_id`. In other places too.

2019-07-31 10:10 UTC, dborovcanin requested changes
Do we really need `rebar3` (mqtt/verne/rebar3) binary?

2019-07-31 21:35 UTC, drasko commented on mqtt/verne/README.md
> +        DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
@dusanb94 this does not come from us, this is VerneMQ specific - a way to tweak params in the `vernemq.config` withing the container. This is their converntion.

2019-08-01 10:29 UTC, drasko commented
> Do we really need `rebar3` (mqtt/verne/rebar3) binary?

@dusanb94 we do not, but it is a script, and VerneMQ keep it in thier demo plugin that I started with: https://github.com/vernemq/vernemq_demo_plugin - so I decided that we keep it.

2019-08-01 10:33 UTC, dborovcanin approved these changes

2019-08-01 10:40 UTC, merged