NOISSUE - add measuring time from pub to sub
absmach/magistrala pull request #839
Opened 2019-09-05 07:06 UTC by mteodor

### What does this do?
add measuring of time from publishing up to receiving a message in subscriber
synchronize publishers and subscribers on start end end of publishing
add a test message that can be normalized

2019-09-05 09:29 UTC, anovakovic01 requested changes

2019-09-05 09:29 UTC, anovakovic01 commented on tools/mqtt-bench/client.go
> +			//log.Printf("Failed to decode message %s\n", err.Error())
Remove the code that is commented out.

2019-09-05 09:29 UTC, anovakovic01 commented on tools/mqtt-bench/templates/config.toml
> +>>>>>>> improve sync between pub and sub
You've committed conflict marks. Please resolve them.

2019-09-05 09:29 UTC, anovakovic01 commented on tools/mqtt-bench/bench.go
> +	//checkConnection(cfg.MQTT.Broker.URL, 1)
Remove the code that is commented out.

2019-09-05 11:12 UTC, dborovcanin submitted a review, later dismissed

2019-09-05 14:55 UTC, drasko requested changes

2019-09-05 14:55 UTC, drasko commented on tools/mqtt-bench/bench.go
> +	// how many records to make message long sz bytes
Comments start with capital letters

2019-09-05 14:55 UTC, drasko commented on tools/mqtt-bench/bench.go
> +		// is this needed
Remove dead code

2019-09-06 11:33 UTC, drasko approved these changes
LGTM

2019-09-06 12:07 UTC, dborovcanin approved these changes

2019-09-06 12:59 UTC, anovakovic01 approved these changes
LGTM!

2019-09-06 12:59 UTC, merged