NOISSUE - Repository Retrieve User By Name
absmach/magistrala pull request #84
Opened 2023-11-28 12:35 UTC by rodneyosodo

### What does this do?
Retrieve users by name from the database. This is a new feature. It enables the user to retrieve users by name. This is needed for search purposes

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
Yes

### Did you document any new/modified functionality?
No

### Notes
N/A

2023-11-29 16:26 UTC, arvindh123 commented on pkg/clients/postgres/clients.go
> +func ToDBClientsPage(pm clients.Page) (dbClientsPage, error) {
@rodneyosodo, Please base with master, Most of the helper functions are exported in this PR https://github.com/absmach/magistrala/pull/76/files

2023-11-29 16:31 UTC, arvindh123 commented on users/postgres/clients_test.go
>  )
Could not find usage of this variable

2023-11-29 16:34 UTC, arvindh123 commented on users/postgres/clients.go
> +		if pm.Dir != "" && (pm.Dir == "asc" || pm.Dir == "desc") {
`absmach/magistrala/internal/api/common.go` package have const string with values `asc` `desc`, May be it can be reused here

2023-12-01 10:54 UTC, arvindh123 reviewed
LGTM

2023-12-01 10:55 UTC, arvindh123 approved these changes

2023-12-04 08:38 UTC, arvindh123 approved these changes

2023-12-04 08:39 UTC, arvindh123 approved these changes

2023-12-04 09:12 UTC, rodneyosodo commented on users/postgres/clients.go
> +	}
From this testing it is safe

![image](https://github.com/absmach/magistrala/assets/28790446/729f5e93-163f-4ccf-afdd-9189793c4de1)

Condition 5 doesn't happen since we wrap our search param with `%:search%`

2023-12-04 13:25 UTC, dborovcanin requested changes
Tests are failing, please fix them.

2023-12-04 14:05 UTC, dborovcanin approved these changes

2023-12-04 14:05 UTC, merged