Password change b
absmach/magistrala pull request #880
Opened 2019-10-09 12:03 UTC by mteodor

### What does this do?
Adds an endpoint for changing password of currently authenticated user

### Which issue(s) does this PR fix/relate to?`
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2019-10-09 12:43 UTC, manuio requested changes

2019-10-09 12:43 UTC, manuio commented on docker/docker-compose.yml
> +      MF_MAIL_FROM_NAME: ${MF_MAIL_FROM_NAME}
EMAIL

2019-10-09 12:43 UTC, manuio commented on users/README.md
> +| MF_MAIL_FROM_NAME         | Mail "from" name                                                        |                |
EMAIL

2019-10-09 12:43 UTC, manuio commented on users/README.md
> +      MF_MAIL_FROM_NAME: [MF_MAIL_FROM_NAME]
EMAIL

2019-10-11 21:55 UTC, drasko requested changes

2019-10-11 21:55 UTC, drasko commented on users/api/http/endpoint.go
> +		res := resetPassRes{}
Replace `Pass` with `Passwd`. It was uncler to me reading the code is the `pass` referencing to passing something...

2019-10-11 21:55 UTC, drasko commented on users/api/http/responses.go
> +type resetPassRes struct {
Replace `Pass` with `Passwd`

2019-10-11 21:55 UTC, drasko commented on users/mocks/users.go
> +// UpdatePassword(
Please fix comment

2019-10-11 21:55 UTC, drasko commented on users/service.go
> +
No need for white line here

2019-10-11 21:55 UTC, drasko commented on users/token/token.go
> +//Package token provides password recovery token generation with TTL
Put space after `//`

2019-10-11 21:55 UTC, drasko commented on users/token/token.go
> +	tokenDuration    int    //token in duration in min
Space after `//`

2019-10-11 21:55 UTC, drasko commented on users/token/token.go
> +
No need fro blank line

2019-10-13 13:31 UTC, closed without merging