Docs
absmach/magistrala pull request #904
Opened 2019-10-23 12:06 UTC by manuio

Closes #890

2019-10-23 13:54 UTC, drasko requested changes

2019-10-23 13:54 UTC, drasko commented on docs/opcua.md
> +The OPC-UA Server is used for connectivity layer. It allows various methods to read informations from the OPC-UA server and his nodes. The current version of the opcua-adapter still experimental and
`his` is used for persons. For things you should use `its`.

2019-10-23 13:54 UTC, drasko commented on docs/opcua.md
> +
Please mention public test-servers here.

2019-10-23 14:04 UTC, chombium commented on docs/opcua.md
> +The opcua-adapter uses the matadata of provision events emitted by Mainflux system to update his route map. For that, you must provision Mainflux `Channels` and `Things` with an extra metadata key in
use its instead of his as above

2019-10-23 16:09 UTC, drasko approved these changes
LGTM

2019-10-24 07:49 UTC, nmarcetic approved these changes

2019-10-24 07:49 UTC, merged