MF-922 - Add User Update endpoint
absmach/magistrala pull request #923
Opened 2019-10-30 08:31 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

2019-10-30 08:37 UTC, drasko requested changes

2019-10-30 08:37 UTC, drasko commented on users/api/http/transport.go
> +	mux.Put("/users", kithttp.NewServer(
Can we move this near to GET on `/users` (or vice-versa) - to increase readability.

2019-10-30 08:37 UTC, drasko commented on users/tracing/users.go
> +	return urm.repo.Update(ctx, user)
Does this update whole user structure or just Metadata?

If it updates whole user structure, it means that User can change his own "constructive" information - which is contrary to the ide that users are created and managed by the admins - and can lead to security breaches.

@nmarcetic please review this one and advise.

2019-10-30 09:09 UTC, anovakovic01 requested changes

2019-10-30 09:09 UTC, anovakovic01 commented on users/postgres/users.go
> +}
Why do we need this struct?

2019-10-30 09:09 UTC, anovakovic01 commented on users/service.go
> +func (svc usersService) UserUpdate(ctx context.Context, token string, u User) error {
I recommend that you pass only metadata instead of the whole user.

2019-10-30 09:09 UTC, anovakovic01 commented on users/api/http/requests.go
> +	user  users.User
Please don't use user here (use metadata instead).

2019-10-30 10:05 UTC, manuio commented on users/postgres/users.go
> +}
I forgot to remove it, good catch!

2019-10-30 18:58 UTC, drasko commented on users/api/http/transport.go
> +	mux.Put("/users", kithttp.NewServer(
Indeed, sorry for this remark :)

2019-10-30 18:59 UTC, drasko commented on users/tracing/users.go
> +	return urm.repo.Update(ctx, user)
@nmarcetic please review and advise here so we can move further.

2019-10-31 10:27 UTC, anovakovic01 requested changes

2019-10-31 10:27 UTC, anovakovic01 commented on users/api/logging.go
> +		message := fmt.Sprintf("Method user_update for user %s took %s to complete", email, time.Since(begin))
Change `user_update` to `update_metadata`.

2019-10-31 10:27 UTC, anovakovic01 commented on users/api/metrics.go
> +		ms.counter.With("method", "user_update").Add(1)
Same here.

2019-10-31 13:56 UTC, anovakovic01 requested changes

2019-10-31 13:56 UTC, anovakovic01 commented on users/api/http/endpoint.go
> +func userUpdateMetaEndpoint(svc users.Service) endpoint.Endpoint {
Please rename this method name.

2019-10-31 13:56 UTC, anovakovic01 commented on users/api/http/requests.go
> +	User  users.User
First, I want to ask why is `Token` public? Second, I still think that here you should have fields that you're updating (for now just `metadata`). If you leave it this way, I can pass email and pass, and the request will be accepted.

2019-10-31 13:56 UTC, anovakovic01 commented on users/api/logging.go
> +		message := fmt.Sprintf("Method update_user_info for user %s took %s to complete", u.Email, time.Since(begin))
Change to `update_user`

2019-10-31 13:56 UTC, anovakovic01 commented on users/api/metrics.go
> +		ms.counter.With("method", "update_user_info").Add(1)
Change to `update_user`.

2019-10-31 14:44 UTC, anovakovic01 approved these changes
LGTM!

2019-10-31 14:47 UTC, drasko approved these changes
LGTM

2019-10-31 14:53 UTC, drasko requested changes
Tests need to be added for this new endpoint.

2019-10-31 15:34 UTC, manuio commented
Add missing tests in this issue: https://github.com/mainflux/mainflux/pull/923

2019-10-31 15:36 UTC, drasko approved these changes

2019-10-31 15:36 UTC, merged