NOISSUE - fix email template logic
absmach/magistrala pull request #944
Opened 2019-11-09 06:11 UTC by mteodor

### Which issue(s) does this PR fix/relate to?
Resolves #942

### Did you document any new/modified functionality?
Yes

2019-11-09 06:14 UTC, blokovi submitted a review, later dismissed

2019-11-10 01:44 UTC, drasko requested changes

2019-11-10 01:44 UTC, drasko commented on users/README.md
> +| MF_TOKEN_SECRET           | Password reset token signing secret                    |                |
Align this properly

2019-11-10 01:44 UTC, drasko commented on users/README.md
> +if 'MF_EMAIL_TEMPLATE' doesn't point to any file service will function but password reset functionality will not work
Sentences start with capital letter.

Use backticks (``) rather than single qoutes.

2019-11-10 13:55 UTC, manuio approved these changes

2019-11-11 10:24 UTC, anovakovic01 approved these changes
LGTM!

2019-11-11 10:27 UTC, nmarcetic approved these changes

2019-11-11 10:28 UTC, manuio approved these changes
LGTM

2019-11-11 11:13 UTC, drasko approved these changes
LGTM

2019-11-11 11:13 UTC, merged

2019-11-11 11:15 UTC, dborovcanin approved these changes