NOISSUE - Add opcua-adapter conn route-map, use ServerURI and NodeID
absmach/magistrala pull request #975
Opened 2019-12-04 03:56 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

2019-12-04 17:40 UTC, drasko requested changes

2019-12-04 17:40 UTC, drasko commented on cmd/opcua/main.go
> +		if len(l) < 2 {
What is this magic number? Consider moving it in the const documented with a comment.

2019-12-05 08:45 UTC, anovakovic01 submitted a review, later dismissed
LGTM!

2019-12-06 15:04 UTC, nmarcetic approved these changes

2019-12-09 22:16 UTC, drasko approved these changes
LGTM

2019-12-09 22:16 UTC, merged