Add /identity
absmach/magistrala pull request #99
Opened 2017-09-24 17:46 UTC by drasko

Signed-off-by: Drasko DRASKOVIC <drasko.draskovic@gmail.com>

2017-09-24 18:10 UTC, mijicd requested changes

2017-09-24 18:10 UTC, mijicd commented on manager/api/resources.go
> +	ClientID string `json:"id"`
Rename to `ID`.

2017-09-24 18:10 UTC, mijicd commented on manager/api/resources.go
> +	return map[string]string{}
We might consider returning it as a header to optimize the flow.

2017-09-24 18:10 UTC, mijicd commented on manager/api/transport.go
> +func decodeIdentity(_ context.Context, r *http.Request) (interface{}, error) {
The same remark applies to requests: utilise headers to pass the token and identity.

2017-09-26 18:17 UTC, drasko commented
Re-pushed. Please review.

2017-09-27 11:36 UTC, mijicd requested changes

2017-09-27 11:36 UTC, mijicd commented on manager/api/endpoint.go
> +		res := identityRes{}
Move after if, and "inline":

```
res := identityRes{
  id: id
}
```

2017-09-27 11:36 UTC, mijicd commented on manager/api/resources.go
> +		"Location": res.id,
`Location` should be used to provide resource URL, absolute or relative (in our case only the relative ones were used). I would recommend using a custom header for this, for example `X-client-id`.

2017-09-27 11:36 UTC, mijicd commented on manager/swagger.yaml
> +            Location:
Update according to the change recommended above.

2017-09-27 11:43 UTC, mijicd requested changes

2017-09-27 11:43 UTC, mijicd commented on manager/mocks/security.go
> +	if id == "mySecretJwtToken" {
Unnecessary.

2017-09-27 13:07 UTC, mijicd approved these changes

2017-09-27 13:07 UTC, merged